package cn.rjtech.model.main;

import cn.jbolt.core.annotation.JBoltAutoCache;
import cn.rjtech.model.main.base.BaseApplication;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 应用系统
 * Generated by JBolt.
 */
@JBoltAutoCache
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "base_application" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Application extends BaseApplication<Application> {
}

