package cn.rjtech.model.main;

import cn.rjtech.model.main.base.BaseAppversion;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 应用版本
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "base_appversion" , primaryKey = "AutoID" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Appversion extends BaseAppversion<Appversion> {
}

