package cn.rjtech.model.main;

import cn.rjtech.model.main.base.BaseMessageUser;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "jb_message_user" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class MessageUser extends BaseMessageUser<MessageUser> {
}

