CREATE TABLE "JBOLT"."JB_SENSITIVE_WORD" (
 "ID" NUMBER(19,0) NOT NULL,
 "CONTENT" NVARCHAR2(40) NOT NULL,
 "ENABLE" CHAR(1) DEFAULT '1' NOT NULL
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_SENSITIVE_WORD"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_SENSITIVE_WORD"."NAME" IS '敏感词内容';
COMMENT ON COLUMN "JBOLT"."JB_SENSITIVE_WORD"."ENABLE" IS '启用';
COMMENT ON TABLE "JBOLT"."JB_SENSITIVE_WORD" IS '敏感词词库';

-- ----------------------------
-- Primary Key structure for table JB_SENSITIVE_WORD
-- ----------------------------
ALTER TABLE "JBOLT"."JB_SENSITIVE_WORD" ADD CONSTRAINT "JBOLT_SENSITIVE_WORD_ID" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JBOLT_SENSITIVE_WORD
-- ----------------------------
ALTER TABLE "JBOLT"."JB_SENSITIVE_WORD" ADD CONSTRAINT "JBOLT_SENSITIVE_WORD_ID_1" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_SENSITIVE_WORD" ADD CONSTRAINT "JBOLT_SENSITIVE_WORD_CONTENT" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_SENSITIVE_WORD" ADD CONSTRAINT "JBOLT_SENSITIVE_WORD_ENABLE" CHECK ("ENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
