package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseAnnualOrderD;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 年度计划-年度计划订单年汇总
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Co_AnnualOrderD" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class AnnualOrderD extends BaseAnnualOrderD<AnnualOrderD> {
}

