package cn.rjtech.model.momdata;

import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.rjtech.model.momdata.base.BaseApprovaldRoleusers;

/**
 * 系统配置-审批节点角色用户
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Bd_ApprovalD_RoleUsers" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class ApprovaldRoleusers extends BaseApprovaldRoleusers<ApprovaldRoleusers> {
}

