package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseApsWeekschedule;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 生产计划-月周生产计划排产
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Aps_WeekSchedule" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class ApsWeekschedule extends BaseApsWeekschedule<ApsWeekschedule> {
}

