package cn.rjtech.model.momdata;

import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.rjtech.model.momdata.base.BaseBarcodeencodingm;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "mes" , table = "BD_BARCODEENCODINGM" , primaryKey = "iautoid" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Barcodeencodingm extends BaseBarcodeencodingm<Barcodeencodingm> {

}

