package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseBomCompare;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 物料建模-Bom清单
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Bd_BomCompare" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class BomCompare extends BaseBomCompare<BomCompare> {
}

