package cn.rjtech.model.momdata;

import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.rjtech.model.momdata.base.BaseBomMasterInv;

/**
 * 基础档案-母件物料存货集（新增/修改版本变更时处理，定时处理更新）
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Bd_BomMasterInv" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class BomMasterInv extends BaseBomMasterInv<BomMasterInv> {
}

