package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseCodingRuleM;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 系统配置-编码规则
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Bd_CodingRuleM" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class CodingRuleM extends BaseCodingRuleM<CodingRuleM> {
}

