package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseCusfieldsmappingForm;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 系统配置-导入字段映射表单
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Bd_CusFieldsMapping_Form" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class CusfieldsmappingForm extends BaseCusfieldsmappingForm<CusfieldsmappingForm> {
}

