package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseCusOrderSum;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 客户订单-客户计划汇总
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Co_CusOrderSum" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class CusOrderSum extends BaseCusOrderSum<CusOrderSum> {
}

