package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseCustomerAddr;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 客户档案-联系地址
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Bd_CustomerAddr" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class CustomerAddr extends BaseCustomerAddr<CustomerAddr> {
}

