package cn.rjtech.model.momdata;

import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.rjtech.model.momdata.base.BaseDescflexsegvaluesetvalue;

/**
 * 扩展字段值集
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Bd_DescFlexSegValueSetValue" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Descflexsegvaluesetvalue extends BaseDescflexsegvaluesetvalue<Descflexsegvaluesetvalue> {
}

