package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseForgeignCurrency;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 币种档案
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Bd_ForeignCurrency" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class ForgeignCurrency extends BaseForgeignCurrency<ForgeignCurrency> {
}

