package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseFormApprovalD;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 系统设置-单据审批审批节点
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Bd_FormApprovalD" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class FormApprovalD extends BaseFormApprovalD<FormApprovalD> {
}

