package cn.rjtech.model.momdata;

import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.rjtech.model.momdata.base.BaseInvestmentPlanItemd;

/**
 * 投资计划项目明细表
 * Generated by JBolt.
 */
@TableBind(dataSource = "momdata" , table = "PL_Investment_Plan_ItemD" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class InvestmentPlanItemd extends BaseInvestmentPlanItemd<InvestmentPlanItemd> {
}

