package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseManualOrderM;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 客户订单-手配订单主表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Co_ManualOrderM" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class ManualOrderM extends BaseManualOrderM<ManualOrderM> {
}

