package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseMoMaterialscanusedlogm;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 制造工单-材料耗用主表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Mo_MaterialScanUsedLogM" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class MoMaterialscanusedlogm extends BaseMoMaterialscanusedlogm<MoMaterialscanusedlogm> {
}

