package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseMoMopatchweldm;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 制造工单-补焊记录
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Mo_MoPatchWeldM" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class MoMopatchweldm extends BaseMoMopatchweldm<MoMopatchweldm> {
}

