package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseMoMoroutingequipment;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 制造工单-工艺设备集
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Mo_MoRoutingEquipment" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class MoMoroutingequipment extends BaseMoMoroutingequipment<MoMoroutingequipment> {
}

