package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseMoWorkShiftD;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 制造工单-指定日期班次人员信息明细
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Mo_MoWorkShiftD" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class MoWorkShiftD extends BaseMoWorkShiftD<MoWorkShiftD> {
}

