package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseMrpDemandcomputed;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 需求计划管理-物料需求计划计算明细
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Mrp_DemandComputeD" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class MrpDemandcomputed extends BaseMrpDemandcomputed<MrpDemandcomputed> {
}

