package cn.rjtech.model.momdata;

import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.rjtech.model.momdata.base.BaseMrpDemandcomputem;

/**
 * 需求计划管理-物料需求计划计算主表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Mrp_DemandComputeM" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class MrpDemandcomputem extends BaseMrpDemandcomputem<MrpDemandcomputem> {
}

