package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseOtherOut;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 其它出库单
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "T_Sys_OtherOut" , primaryKey = "AutoID" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class OtherOut extends BaseOtherOut<OtherOut> {
}

