package cn.rjtech.model.momdata;

import cn.jbolt.core.annotation.JBoltAutoCache;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.rjtech.model.momdata.base.BasePerson;

/**
 * 人员档案
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@JBoltAutoCache(keyCache = true,column = "iAutoId")
@TableBind(dataSource = "momdata" , table = "Bd_Person" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Person extends BasePerson<Person> {

    private String username;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}

