package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseProdFormTableItem;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 生产表单设置-生产表单表格行记录
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Bd_ProdFormTableItem" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class ProdFormTableItem extends BaseProdFormTableItem<ProdFormTableItem> {
}

