package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseProdForm;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 生产表单设置-生产表单
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Bd_ProdForm" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class ProdForm extends BaseProdForm<ProdForm> {
}

