package cn.rjtech.model.momdata;

import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.rjtech.model.momdata.base.BaseProposalm;

/**
 * 禀议书主表
 * Generated by JBolt.
 */
@TableBind(dataSource = "momdata" , table = "PL_ProposalM" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Proposalm extends BaseProposalm<Proposalm> {
}

