package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BasePurchaseOrderRef;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 采购/委外-采购订单与到货计划关联
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "PS_PurchaseOrderRef" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class PurchaseOrderRef extends BasePurchaseOrderRef<PurchaseOrderRef> {
}

