package cn.rjtech.model.momdata;

import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.rjtech.model.momdata.base.BasePurchased;

/**
 * 申购单明细表
 * Generated by JBolt.
 */
@TableBind(dataSource = "momdata", table = "PL_PurchaseD", primaryKey = "iAutoId", idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Purchased extends BasePurchased<Purchased> {
}