package cn.rjtech.model.momdata;

import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.rjtech.model.momdata.base.BasePurchasem;

/**
 * 申购单主表
 * Generated by JBolt.
 */
@TableBind(dataSource = "momdata" , table = "PL_PurchaseM" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Purchasem extends BasePurchasem<Purchasem> {
}

