package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseRcvDocQcFormD;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 质量管理-来料检单行配置
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "PL_RcvDocQcFormD" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class RcvDocQcFormD extends BaseRcvDocQcFormD<RcvDocQcFormD> {
}

