package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseSaleType;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 基础档案-销售类型
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Bd_SaleType" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class SaleType extends BaseSaleType<SaleType> {
}

