package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseSpotCheckFormD;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 制造管理-点检表单行配置
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "PL_SpotCheckFormD" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class SpotCheckFormD extends BaseSpotCheckFormD<SpotCheckFormD> {
}

