package cn.rjtech.model.momdata;

import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.rjtech.model.momdata.base.BaseStockCheckVouch;

/**
 * 库存盘点-主表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "T_Sys_StockCheckVouch" , primaryKey = "Autoid" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class StockCheckVouch extends BaseStockCheckVouch<StockCheckVouch> {
}

