package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseSubcontractorderdQty;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 采购/委外订单-采购订单明细数量
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "PS_SubcontractOrderD_Qty" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class SubcontractorderdQty extends BaseSubcontractorderdQty<SubcontractorderdQty> {
}

