package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseSubjectd;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 科目对照细表
 * Generated by JBolt.
 */
@TableBind(dataSource = "momdata" , table = "Bas_SubjectD" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Subjectd extends BaseSubjectd<Subjectd> {
}

