package cn.rjtech.model.momdata;

import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.rjtech.model.momdata.base.BaseSysBillno;

/**
 * 单号
 * Generated by JBolt.
 */
@TableBind(dataSource = "momdata" , table = "Sys_BillNo" , primaryKey = "PAT,OrgID" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class SysBillno extends BaseSysBillno<SysBillno> {
}

