package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseSysMaterialsprepare;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 材料备料表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "T_Sys_MaterialsPrepare" , primaryKey = "AutoID" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class SysMaterialsprepare extends BaseSysMaterialsprepare<SysMaterialsprepare> {
}

