package cn.rjtech.model.momdata;

import cn.rjtech.model.momdata.base.BaseSysProductindetail;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 产成品入库单明细
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "T_Sys_ProductInDetail" , primaryKey = "AutoID" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class SysProductindetail extends BaseSysProductindetail<SysProductindetail> {
}

