package cn.rjtech.model.momdata;

import cn.jbolt.core.annotation.JBoltAutoCache;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.rjtech.model.momdata.base.BaseWorkregionm;


/**
 * 工段档案主表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@JBoltAutoCache(keyCache = true,column = "iAutoId")
@TableBind(dataSource = "momdata" , table = "Bd_WorkRegionM" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Workregionm extends BaseWorkregionm<Workregionm> {
}

