package cn.rjtech.model.mopick;

import cn.rjtech.model.mopick.base.BaseMoMopickitemdBatch;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 生产订单-备料单存货现品票明细
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "Mo_MoPickItemD_Batch" , primaryKey = "iAutoId" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class MoMopickitemdBatch extends BaseMoMopickitemdBatch<MoMopickitemdBatch> {
}

