package cn.rjtech.model.momdata.base;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 生产计划-年度计划排产日期数量
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("unchecked")
public abstract class BaseApsAnnualplandQty<M extends BaseApsAnnualplandQty<M>> extends JBoltBaseModel<M>{
    /**主键ID*/
    public static final String IAUTOID = "iAutoId";
    /**年度计划明细ID*/
    public static final String IANNUALPLANDID = "iAnnualPlanDid";
    /**类型：1. 计划使用 2. 计划数量 3. 计划在库*/
    public static final String ITYPE = "iType";
    /**年*/
    public static final String IYEAR = "iYear";
    /**月*/
    public static final String IMONTH = "iMonth";
    /**日*/
    public static final String IDATE = "iDate";
    /**数量*/
    public static final String IQTY = "iQty";
	/**
	 * 主键ID
	 */
	public M setIAutoId(java.lang.Long iAutoId) {
		set("iAutoId", iAutoId);
		return (M)this;
	}

	/**
	 * 主键ID
	 */
	@JBoltField(name="iautoid" ,columnName="iAutoId",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(name = "iautoid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAutoId() {
		return getLong("iAutoId");
	}

	/**
	 * 年度计划明细ID
	 */
	public M setIAnnualPlanDid(java.lang.Long iAnnualPlanDid) {
		set("iAnnualPlanDid", iAnnualPlanDid);
		return (M)this;
	}

	/**
	 * 年度计划明细ID
	 */
	@JBoltField(name="iannualplandid" ,columnName="iAnnualPlanDid",type="Long", remark="年度计划明细ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(name = "iannualplandid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAnnualPlanDid() {
		return getLong("iAnnualPlanDid");
	}

	/**
	 * 类型：1. 计划使用 2. 计划数量 3. 计划在库
	 */
	public M setIType(java.lang.Integer iType) {
		set("iType", iType);
		return (M)this;
	}

	/**
	 * 类型：1. 计划使用 2. 计划数量 3. 计划在库
	 */
	@JBoltField(name="itype" ,columnName="iType",type="Integer", remark="类型：1. 计划使用 2. 计划数量 3. 计划在库", required=true, maxLength=10, fixed=0, order=3)
	@JSONField(name = "itype")
	public java.lang.Integer getIType() {
		return getInt("iType");
	}

	/**
	 * 年
	 */
	public M setIYear(java.lang.Integer iYear) {
		set("iYear", iYear);
		return (M)this;
	}

	/**
	 * 年
	 */
	@JBoltField(name="iyear" ,columnName="iYear",type="Integer", remark="年", required=true, maxLength=10, fixed=0, order=4)
	@JSONField(name = "iyear")
	public java.lang.Integer getIYear() {
		return getInt("iYear");
	}

	/**
	 * 月
	 */
	public M setIMonth(java.lang.Integer iMonth) {
		set("iMonth", iMonth);
		return (M)this;
	}

	/**
	 * 月
	 */
	@JBoltField(name="imonth" ,columnName="iMonth",type="Integer", remark="月", required=true, maxLength=10, fixed=0, order=5)
	@JSONField(name = "imonth")
	public java.lang.Integer getIMonth() {
		return getInt("iMonth");
	}

	/**
	 * 日
	 */
	public M setIDate(java.lang.Integer iDate) {
		set("iDate", iDate);
		return (M)this;
	}

	/**
	 * 日
	 */
	@JBoltField(name="idate" ,columnName="iDate",type="Integer", remark="日", required=false, maxLength=10, fixed=0, order=6)
	@JSONField(name = "idate")
	public java.lang.Integer getIDate() {
		return getInt("iDate");
	}

	/**
	 * 数量
	 */
	public M setIQty(java.lang.Integer iQty) {
		set("iQty", iQty);
		return (M)this;
	}

	/**
	 * 数量
	 */
	@JBoltField(name="iqty" ,columnName="iQty",type="Integer", remark="数量", required=true, maxLength=10, fixed=0, order=7)
	@JSONField(name = "iqty")
	public java.lang.Integer getIQty() {
		return getInt("iQty");
	}

}

