package cn.rjtech.model.momdata.base;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 费用预算主表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("unchecked")
public abstract class BaseExpenseBudget<M extends BaseExpenseBudget<M>> extends JBoltBaseModel<M>{
    
    /**主键ID*/
    public static final String IAUTOID = "iAutoId";
    /**组织ID*/
    public static final String IORGID = "iOrgId";
    /**组织编码*/
    public static final String CORGCODE = "cOrgCode";
    /**部门编码*/
    public static final String CDEPCODE = "cDepCode";
    /**预算类型(1.全年预算 2.下期修改)*/
    public static final String IBUDGETTYPE = "iBudgetType";
    /**期间*/
    public static final String IPERIODID = "iPeriodId";
    /**开始年月*/
    public static final String CBEGINDATE = "cBeginDate";
    /**结束年月*/
    public static final String CENDDATE = "cEndDate";
    /**备注*/
    public static final String CMEMO = "cMemo";
    /**审核状态*/
    public static final String IAUDITSTATUS = "iAuditStatus";
    /**审核时间*/
    public static final String DAUDITTIME = "dAuditTime";
    /**创建时间*/
    public static final String DCREATETIME = "dCreateTime";
    /**更新时间*/
    public static final String DUPDATETIME = "dUpdateTime";
    /**创建人*/
    public static final String ICREATEBY = "iCreateBy";
    /**更新人*/
    public static final String IUPDATEBY = "iUpdateBy";
    /**预算年度*/
    public static final String IBUDGETYEAR = "iBudgetYear";
    /**生效状态(1.未生效 2.已生效 3.失效)*/
    public static final String IEFFECTIVESTATUS = "iEffectiveStatus";
    /**审批方式：1. 审批状态 2. 审批流*/
    public static final String IAUDITWAY = "iAuditWay";
    /**提审时间*/
    public static final String DSUBMITTIME = "dSubmitTime";
    /**审核人ID，不走审批流时有该值*/
    public static final String IAUDITBY = "iAuditBy";
    /**审核人名称，不走审批流时有该值*/
    public static final String CAUDITNAME = "cAuditName";
    /**删除状态：0. 未删除 1. 已删除*/
    public static final String ISDELETED = "IsDeleted";
	/**
	 * 主键ID
	 */
	public M setIAutoId(java.lang.Long iAutoId) {
		set("iAutoId", iAutoId);
		return (M)this;
	}

	/**
	 * 主键ID
	 */
	@JBoltField(name="iautoid" ,columnName="iAutoId",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(name = "iautoid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAutoId() {
		return getLong("iAutoId");
	}

	/**
	 * 组织ID
	 */
	public M setIOrgId(java.lang.Long iOrgId) {
		set("iOrgId", iOrgId);
		return (M)this;
	}

	/**
	 * 组织ID
	 */
	@JBoltField(name="iorgid" ,columnName="iOrgId",type="Long", remark="组织ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(name = "iorgid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIOrgId() {
		return getLong("iOrgId");
	}

	/**
	 * 组织编码
	 */
	public M setCOrgCode(java.lang.String cOrgCode) {
		set("cOrgCode", cOrgCode);
		return (M)this;
	}

	/**
	 * 组织编码
	 */
	@JBoltField(name="corgcode" ,columnName="cOrgCode",type="String", remark="组织编码", required=true, maxLength=20, fixed=0, order=3)
	@JSONField(name = "corgcode")
	public java.lang.String getCOrgCode() {
		return getStr("cOrgCode");
	}

	/**
	 * 部门编码
	 */
	public M setCDepCode(java.lang.String cDepCode) {
		set("cDepCode", cDepCode);
		return (M)this;
	}

	/**
	 * 部门编码
	 */
	@JBoltField(name="cdepcode" ,columnName="cDepCode",type="String", remark="部门编码", required=true, maxLength=20, fixed=0, order=4)
	@JSONField(name = "cdepcode")
	public java.lang.String getCDepCode() {
		return getStr("cDepCode");
	}

	/**
	 * 预算类型(1.全年预算 2.下期修改)
	 */
	public M setIBudgetType(java.lang.Integer iBudgetType) {
		set("iBudgetType", iBudgetType);
		return (M)this;
	}

	/**
	 * 预算类型(1.全年预算 2.下期修改)
	 */
	@JBoltField(name="ibudgettype" ,columnName="iBudgetType",type="Integer", remark="预算类型(1.全年预算 2.下期修改)", required=true, maxLength=10, fixed=0, order=5)
	@JSONField(name = "ibudgettype")
	public java.lang.Integer getIBudgetType() {
		return getInt("iBudgetType");
	}

	/**
	 * 期间
	 */
	public M setIPeriodId(java.lang.Long iPeriodId) {
		set("iPeriodId", iPeriodId);
		return (M)this;
	}

	/**
	 * 期间
	 */
	@JBoltField(name="iperiodid" ,columnName="iPeriodId",type="Long", remark="期间", required=false, maxLength=19, fixed=0, order=6)
	@JSONField(name = "iperiodid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIPeriodId() {
		return getLong("iPeriodId");
	}

	/**
	 * 开始年月
	 */
	public M setCBeginDate(java.util.Date cBeginDate) {
		set("cBeginDate", cBeginDate);
		return (M)this;
	}

	/**
	 * 开始年月
	 */
	@JBoltField(name="cbegindate" ,columnName="cBeginDate",type="Date", remark="开始年月", required=false, maxLength=23, fixed=3, order=7)
	@JSONField(name = "cbegindate")
	public java.util.Date getCBeginDate() {
		return getDate("cBeginDate");
	}

	/**
	 * 结束年月
	 */
	public M setCEndDate(java.util.Date cEndDate) {
		set("cEndDate", cEndDate);
		return (M)this;
	}

	/**
	 * 结束年月
	 */
	@JBoltField(name="cenddate" ,columnName="cEndDate",type="Date", remark="结束年月", required=false, maxLength=23, fixed=3, order=8)
	@JSONField(name = "cenddate")
	public java.util.Date getCEndDate() {
		return getDate("cEndDate");
	}

	/**
	 * 备注
	 */
	public M setCMemo(java.lang.String cMemo) {
		set("cMemo", cMemo);
		return (M)this;
	}

	/**
	 * 备注
	 */
	@JBoltField(name="cmemo" ,columnName="cMemo",type="String", remark="备注", required=false, maxLength=200, fixed=0, order=9)
	@JSONField(name = "cmemo")
	public java.lang.String getCMemo() {
		return getStr("cMemo");
	}

	/**
	 * 审核状态
	 */
	public M setIAuditStatus(java.lang.Integer iAuditStatus) {
		set("iAuditStatus", iAuditStatus);
		return (M)this;
	}

	/**
	 * 审核状态
	 */
	@JBoltField(name="iauditstatus" ,columnName="iAuditStatus",type="Integer", remark="审核状态", required=true, maxLength=10, fixed=0, order=10)
	@JSONField(name = "iauditstatus")
	public java.lang.Integer getIAuditStatus() {
		return getInt("iAuditStatus");
	}

	/**
	 * 审核时间
	 */
	public M setDAuditTime(java.util.Date dAuditTime) {
		set("dAuditTime", dAuditTime);
		return (M)this;
	}

	/**
	 * 审核时间
	 */
	@JBoltField(name="daudittime" ,columnName="dAuditTime",type="Date", remark="审核时间", required=false, maxLength=23, fixed=3, order=11)
	@JSONField(name = "daudittime")
	public java.util.Date getDAuditTime() {
		return getDate("dAuditTime");
	}

	/**
	 * 创建时间
	 */
	public M setDCreateTime(java.util.Date dCreateTime) {
		set("dCreateTime", dCreateTime);
		return (M)this;
	}

	/**
	 * 创建时间
	 */
	@JBoltField(name="dcreatetime" ,columnName="dCreateTime",type="Date", remark="创建时间", required=true, maxLength=23, fixed=3, order=12)
	@JSONField(name = "dcreatetime")
	public java.util.Date getDCreateTime() {
		return getDate("dCreateTime");
	}

	/**
	 * 更新时间
	 */
	public M setDUpdateTime(java.util.Date dUpdateTime) {
		set("dUpdateTime", dUpdateTime);
		return (M)this;
	}

	/**
	 * 更新时间
	 */
	@JBoltField(name="dupdatetime" ,columnName="dUpdateTime",type="Date", remark="更新时间", required=false, maxLength=23, fixed=3, order=13)
	@JSONField(name = "dupdatetime")
	public java.util.Date getDUpdateTime() {
		return getDate("dUpdateTime");
	}

	/**
	 * 创建人
	 */
	public M setICreateBy(java.lang.Long iCreateBy) {
		set("iCreateBy", iCreateBy);
		return (M)this;
	}

	/**
	 * 创建人
	 */
	@JBoltField(name="icreateby" ,columnName="iCreateBy",type="Long", remark="创建人", required=true, maxLength=19, fixed=0, order=14)
	@JSONField(name = "icreateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getICreateBy() {
		return getLong("iCreateBy");
	}

	/**
	 * 更新人
	 */
	public M setIUpdateBy(java.lang.Long iUpdateBy) {
		set("iUpdateBy", iUpdateBy);
		return (M)this;
	}

	/**
	 * 更新人
	 */
	@JBoltField(name="iupdateby" ,columnName="iUpdateBy",type="Long", remark="更新人", required=false, maxLength=19, fixed=0, order=15)
	@JSONField(name = "iupdateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIUpdateBy() {
		return getLong("iUpdateBy");
	}

	/**
	 * 预算年度
	 */
	public M setIBudgetYear(java.lang.Integer iBudgetYear) {
		set("iBudgetYear", iBudgetYear);
		return (M)this;
	}

	/**
	 * 预算年度
	 */
	@JBoltField(name="ibudgetyear" ,columnName="iBudgetYear",type="Integer", remark="预算年度", required=true, maxLength=10, fixed=0, order=16)
	@JSONField(name = "ibudgetyear")
	public java.lang.Integer getIBudgetYear() {
		return getInt("iBudgetYear");
	}

	/**
	 * 生效状态(1.未生效 2.已生效 3.失效)
	 */
	public M setIEffectiveStatus(java.lang.Integer iEffectiveStatus) {
		set("iEffectiveStatus", iEffectiveStatus);
		return (M)this;
	}

	/**
	 * 生效状态(1.未生效 2.已生效 3.失效)
	 */
	@JBoltField(name="ieffectivestatus" ,columnName="iEffectiveStatus",type="Integer", remark="生效状态(1.未生效 2.已生效 3.失效)", required=true, maxLength=10, fixed=0, order=17)
	@JSONField(name = "ieffectivestatus")
	public java.lang.Integer getIEffectiveStatus() {
		return getInt("iEffectiveStatus");
	}

	/**
	 * 审批方式：1. 审批状态 2. 审批流
	 */
	public M setIAuditWay(java.lang.Integer iAuditWay) {
		set("iAuditWay", iAuditWay);
		return (M)this;
	}

	/**
	 * 审批方式：1. 审批状态 2. 审批流
	 */
	@JBoltField(name="iauditway" ,columnName="iAuditWay",type="Integer", remark="审批方式：1. 审批状态 2. 审批流", required=false, maxLength=10, fixed=0, order=18)
	@JSONField(name = "iauditway")
	public java.lang.Integer getIAuditWay() {
		return getInt("iAuditWay");
	}

	/**
	 * 提审时间
	 */
	public M setDSubmitTime(java.util.Date dSubmitTime) {
		set("dSubmitTime", dSubmitTime);
		return (M)this;
	}

	/**
	 * 提审时间
	 */
	@JBoltField(name="dsubmittime" ,columnName="dSubmitTime",type="Date", remark="提审时间", required=false, maxLength=23, fixed=3, order=19)
	@JSONField(name = "dsubmittime")
	public java.util.Date getDSubmitTime() {
		return getDate("dSubmitTime");
	}

	/**
	 * 审核人ID，不走审批流时有该值
	 */
	public M setIAuditBy(java.lang.Long iAuditBy) {
		set("iAuditBy", iAuditBy);
		return (M)this;
	}

	/**
	 * 审核人ID，不走审批流时有该值
	 */
	@JBoltField(name="iauditby" ,columnName="iAuditBy",type="Long", remark="审核人ID，不走审批流时有该值", required=false, maxLength=19, fixed=0, order=20)
	@JSONField(name = "iauditby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAuditBy() {
		return getLong("iAuditBy");
	}

	/**
	 * 审核人名称，不走审批流时有该值
	 */
	public M setCAuditName(java.util.Date cAuditName) {
		set("cAuditName", cAuditName);
		return (M)this;
	}

	/**
	 * 审核人名称，不走审批流时有该值
	 */
	@JBoltField(name="cauditname" ,columnName="cAuditName",type="Date", remark="审核人名称，不走审批流时有该值", required=false, maxLength=23, fixed=3, order=21)
	@JSONField(name = "cauditname")
	public java.util.Date getCAuditName() {
		return getDate("cAuditName");
	}

	/**
	 * 删除状态：0. 未删除 1. 已删除
	 */
	public M setIsDeleted(java.lang.Boolean IsDeleted) {
		set("IsDeleted", IsDeleted);
		return (M)this;
	}

	/**
	 * 删除状态：0. 未删除 1. 已删除
	 */
	@JBoltField(name="isdeleted" ,columnName="IsDeleted",type="Boolean", remark="删除状态：0. 未删除 1. 已删除", required=true, maxLength=1, fixed=0, order=22)
	@JSONField(name = "isdeleted")
	public java.lang.Boolean getIsDeleted() {
		return getBoolean("IsDeleted");
	}

}

