package cn.rjtech.model.momdata.base;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 制造管理-生产表单行配置
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("unchecked")
public abstract class BaseProdFormD<M extends BaseProdFormD<M>> extends JBoltBaseModel<M>{
    
    /**主键ID*/
    public static final String IAUTOID = "iAutoId";
    /**生产表单主表ID*/
    public static final String IPRODFORMMID = "iProdFormMid";
    /**生产表格ID*/
    public static final String IPRODFORMID = "iProdFormId";
    /**项目ID，Bd_ProdFormTableParam.iAutoId*/
    public static final String IPRODFORMPARAMID = "iProdFormParamId";
    /**项目次序，固定取参数项目名为“项目”的参数名称次序值*/
    public static final String ISEQ = "iSeq";
    /**参数值ID，允许为空（拼接“-”）多个逗号分隔*/
    public static final String CPRODFORMPARAMIDS = "cProdFormParamIds";
    /**参数录入方式：1. CPK数值 2. 文本框 3. 选择（√，/，×，△，◎） 4. 单选 5. 复选 6. 下拉列表 7. 日期 8. 时间*/
    public static final String ITYPE = "iType";
    /**标准值*/
    public static final String ISTDVAL = "iStdVal";
    /**最大设定值*/
    public static final String IMAXVAL = "iMaxVal";
    /**最小设定值*/
    public static final String IMINVAL = "iMinVal";
    /**列表可选值;多个“,”分隔*/
    public static final String COPTIONS = "cOptions";
	/**
	 * 主键ID
	 */
	public M setIAutoId(java.lang.Long iAutoId) {
		set("iAutoId", iAutoId);
		return (M)this;
	}

	/**
	 * 主键ID
	 */
	@JBoltField(name="iautoid" ,columnName="iAutoId",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(name = "iautoid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAutoId() {
		return getLong("iAutoId");
	}

	/**
	 * 生产表单主表ID
	 */
	public M setIProdFormMid(java.lang.Long iProdFormMid) {
		set("iProdFormMid", iProdFormMid);
		return (M)this;
	}

	/**
	 * 生产表单主表ID
	 */
	@JBoltField(name="iprodformmid" ,columnName="iProdFormMid",type="Long", remark="生产表单主表ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(name = "iprodformmid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIProdFormMid() {
		return getLong("iProdFormMid");
	}

	/**
	 * 生产表格ID
	 */
	public M setIProdFormId(java.lang.Long iProdFormId) {
		set("iProdFormId", iProdFormId);
		return (M)this;
	}

	/**
	 * 生产表格ID
	 */
	@JBoltField(name="iprodformid" ,columnName="iProdFormId",type="Long", remark="生产表格ID", required=true, maxLength=19, fixed=0, order=3)
	@JSONField(name = "iprodformid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIProdFormId() {
		return getLong("iProdFormId");
	}

	/**
	 * 项目ID，Bd_ProdFormTableParam.iAutoId
	 */
	public M setIProdFormParamId(java.lang.Long iProdFormParamId) {
		set("iProdFormParamId", iProdFormParamId);
		return (M)this;
	}

	/**
	 * 项目ID，Bd_ProdFormTableParam.iAutoId
	 */
	@JBoltField(name="iprodformparamid" ,columnName="iProdFormParamId",type="Long", remark="项目ID，Bd_ProdFormTableParam.iAutoId", required=true, maxLength=19, fixed=0, order=4)
	@JSONField(name = "iprodformparamid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIProdFormParamId() {
		return getLong("iProdFormParamId");
	}

	/**
	 * 项目次序，固定取参数项目名为“项目”的参数名称次序值
	 */
	public M setISeq(java.lang.Integer iSeq) {
		set("iSeq", iSeq);
		return (M)this;
	}

	/**
	 * 项目次序，固定取参数项目名为“项目”的参数名称次序值
	 */
	@JBoltField(name="iseq" ,columnName="iSeq",type="Integer", remark="项目次序，固定取参数项目名为“项目”的参数名称次序值", required=true, maxLength=10, fixed=0, order=5)
	@JSONField(name = "iseq")
	public java.lang.Integer getISeq() {
		return getInt("iSeq");
	}

	/**
	 * 参数值ID，允许为空（拼接“-”）多个逗号分隔
	 */
	public M setCProdFormParamIds(java.lang.String cProdFormParamIds) {
		set("cProdFormParamIds", cProdFormParamIds);
		return (M)this;
	}

	/**
	 * 参数值ID，允许为空（拼接“-”）多个逗号分隔
	 */
	@JBoltField(name="cprodformparamids" ,columnName="cProdFormParamIds",type="String", remark="参数值ID，允许为空（拼接“-”）多个逗号分隔", required=false, maxLength=500, fixed=0, order=6)
	@JSONField(name = "cprodformparamids")
	public java.lang.String getCProdFormParamIds() {
		return getStr("cProdFormParamIds");
	}

	/**
	 * 参数录入方式：1. CPK数值 2. 文本框 3. 选择（√，/，×，△，◎） 4. 单选 5. 复选 6. 下拉列表 7. 日期 8. 时间
	 */
	public M setIType(java.lang.Integer iType) {
		set("iType", iType);
		return (M)this;
	}

	/**
	 * 参数录入方式：1. CPK数值 2. 文本框 3. 选择（√，/，×，△，◎） 4. 单选 5. 复选 6. 下拉列表 7. 日期 8. 时间
	 */
	@JBoltField(name="itype" ,columnName="iType",type="Integer", remark="参数录入方式：1. CPK数值 2. 文本框 3. 选择（√，/，×，△，◎） 4. 单选 5. 复选 6. 下拉列表 7. 日期 8. 时间", required=false, maxLength=10, fixed=0, order=7)
	@JSONField(name = "itype")
	public java.lang.Integer getIType() {
		return getInt("iType");
	}

	/**
	 * 标准值
	 */
	public M setIStdVal(java.math.BigDecimal iStdVal) {
		set("iStdVal", iStdVal);
		return (M)this;
	}

	/**
	 * 标准值
	 */
	@JBoltField(name="istdval" ,columnName="iStdVal",type="BigDecimal", remark="标准值", required=false, maxLength=24, fixed=6, order=8)
	@JSONField(name = "istdval")
	public java.math.BigDecimal getIStdVal() {
		return getBigDecimal("iStdVal");
	}

	/**
	 * 最大设定值
	 */
	public M setIMaxVal(java.math.BigDecimal iMaxVal) {
		set("iMaxVal", iMaxVal);
		return (M)this;
	}

	/**
	 * 最大设定值
	 */
	@JBoltField(name="imaxval" ,columnName="iMaxVal",type="BigDecimal", remark="最大设定值", required=false, maxLength=24, fixed=6, order=9)
	@JSONField(name = "imaxval")
	public java.math.BigDecimal getIMaxVal() {
		return getBigDecimal("iMaxVal");
	}

	/**
	 * 最小设定值
	 */
	public M setIMinVal(java.math.BigDecimal iMinVal) {
		set("iMinVal", iMinVal);
		return (M)this;
	}

	/**
	 * 最小设定值
	 */
	@JBoltField(name="iminval" ,columnName="iMinVal",type="BigDecimal", remark="最小设定值", required=false, maxLength=24, fixed=6, order=10)
	@JSONField(name = "iminval")
	public java.math.BigDecimal getIMinVal() {
		return getBigDecimal("iMinVal");
	}

	/**
	 * 列表可选值;多个“,”分隔
	 */
	public M setCOptions(java.lang.String cOptions) {
		set("cOptions", cOptions);
		return (M)this;
	}

	/**
	 * 列表可选值;多个“,”分隔
	 */
	@JBoltField(name="coptions" ,columnName="cOptions",type="String", remark="列表可选值;多个“,”分隔", required=false, maxLength=500, fixed=0, order=11)
	@JSONField(name = "coptions")
	public java.lang.String getCOptions() {
		return getStr("cOptions");
	}

}

