package cn.rjtech.model.momdata.base;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 系统管理里-枚举值
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEnumVals<M extends BaseEnumVals<M>> extends JBoltBaseModel<M>{
    /**主键ID*/
    public static final String IAUTOID = "iAutoId";
    /**枚举类型ID*/
    public static final String IENUMTYPEID = "iEnumTypeId";
    /**枚举编码*/
    public static final String CENUMCODE = "cEnumCode";
    /**枚举名称*/
    public static final String CENUMNAME = "cEnumName";
	/**
	 * 主键ID
	 */
	public M setIAutoId(java.lang.Long iAutoId) {
		set("iAutoId", iAutoId);
		return (M)this;
	}

	/**
	 * 主键ID
	 */
	@JBoltField(name="iautoid" ,columnName="iAutoId",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(name = "iautoid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAutoId() {
		return getLong("iAutoId");
	}

	/**
	 * 枚举类型ID
	 */
	public M setIEnumTypeId(java.lang.Long iEnumTypeId) {
		set("iEnumTypeId", iEnumTypeId);
		return (M)this;
	}

	/**
	 * 枚举类型ID
	 */
	@JBoltField(name="ienumtypeid" ,columnName="iEnumTypeId",type="Long", remark="枚举类型ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(name = "ienumtypeid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIEnumTypeId() {
		return getLong("iEnumTypeId");
	}

	/**
	 * 枚举编码
	 */
	public M setCEnumCode(java.lang.String cEnumCode) {
		set("cEnumCode", cEnumCode);
		return (M)this;
	}

	/**
	 * 枚举编码
	 */
	@JBoltField(name="cenumcode" ,columnName="cEnumCode",type="String", remark="枚举编码", required=true, maxLength=60, fixed=0, order=3)
	@JSONField(name = "cenumcode")
	public java.lang.String getCEnumCode() {
		return getStr("cEnumCode");
	}

	/**
	 * 枚举名称
	 */
	public M setCEnumName(java.lang.String cEnumName) {
		set("cEnumName", cEnumName);
		return (M)this;
	}

	/**
	 * 枚举名称
	 */
	@JBoltField(name="cenumname" ,columnName="cEnumName",type="String", remark="枚举名称", required=true, maxLength=60, fixed=0, order=4)
	@JSONField(name = "cenumname")
	public java.lang.String getCEnumName() {
		return getStr("cEnumName");
	}

}

