package cn.rjtech.model.momdata.base;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 生产表单设置-生产表单表格行记录
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("unchecked")
public abstract class BaseProdFormTableItem<M extends BaseProdFormTableItem<M>> extends JBoltBaseModel<M>{
    
    /**主键ID*/
    public static final String IAUTOID = "iAutoId";
    /**生产项目ID*/
    public static final String IPRODFORMITEMID = "iProdFormItemId";
    /**生产参数ID*/
    public static final String IPRODFORMPARAMID = "iProdFormParamId";
    /**生产表格行ID*/
    public static final String IPRODFORMTABLEPARAMID = "iProdFormTableParamId";
    /**生产表格ID*/
    public static final String IPRODFORMID = "iProdFormId";
	/**
	 * 主键ID
	 */
	public M setIAutoId(java.lang.Long iAutoId) {
		set("iAutoId", iAutoId);
		return (M)this;
	}

	/**
	 * 主键ID
	 */
	@JBoltField(name="iautoid" ,columnName="iAutoId",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(name = "iautoid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAutoId() {
		return getLong("iAutoId");
	}

	/**
	 * 生产项目ID
	 */
	public M setIProdFormItemId(java.lang.Long iProdFormItemId) {
		set("iProdFormItemId", iProdFormItemId);
		return (M)this;
	}

	/**
	 * 生产项目ID
	 */
	@JBoltField(name="iprodformitemid" ,columnName="iProdFormItemId",type="Long", remark="生产项目ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(name = "iprodformitemid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIProdFormItemId() {
		return getLong("iProdFormItemId");
	}

	/**
	 * 生产参数ID
	 */
	public M setIProdFormParamId(java.lang.Long iProdFormParamId) {
		set("iProdFormParamId", iProdFormParamId);
		return (M)this;
	}

	/**
	 * 生产参数ID
	 */
	@JBoltField(name="iprodformparamid" ,columnName="iProdFormParamId",type="Long", remark="生产参数ID", required=false, maxLength=19, fixed=0, order=3)
	@JSONField(name = "iprodformparamid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIProdFormParamId() {
		return getLong("iProdFormParamId");
	}

	/**
	 * 生产表格行ID
	 */
	public M setIProdFormTableParamId(java.lang.Long iProdFormTableParamId) {
		set("iProdFormTableParamId", iProdFormTableParamId);
		return (M)this;
	}

	/**
	 * 生产表格行ID
	 */
	@JBoltField(name="iprodformtableparamid" ,columnName="iProdFormTableParamId",type="Long", remark="生产表格行ID", required=true, maxLength=19, fixed=0, order=4)
	@JSONField(name = "iprodformtableparamid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIProdFormTableParamId() {
		return getLong("iProdFormTableParamId");
	}

	/**
	 * 生产表格ID
	 */
	public M setIProdFormId(java.lang.Long iProdFormId) {
		set("iProdFormId", iProdFormId);
		return (M)this;
	}

	/**
	 * 生产表格ID
	 */
	@JBoltField(name="iprodformid" ,columnName="iProdFormId",type="Long", remark="生产表格ID", required=true, maxLength=19, fixed=0, order=5)
	@JSONField(name = "iprodformid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIProdFormId() {
		return getLong("iProdFormId");
	}

}

