package cn.rjtech.model.momdata.base;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 组织建模-部门档案
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("unchecked")
public abstract class BaseDepartment<M extends BaseDepartment<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "momdata";
    /**主键ID*/
    public static final String IAUTOID = "iAutoId";
    /**组织ID*/
    public static final String IORGID = "iOrgId";
    /**组织编码*/
    public static final String CORGCODE = "cOrgCode";
    /**部门编码*/
    public static final String CDEPCODE = "cDepCode";
    /**是否末级：0. 否 1. 是*/
    public static final String BDEPEND = "bDepEnd";
    /**部门名称*/
    public static final String CDEPNAME = "cDepName";
    /**编码级次*/
    public static final String IDEPGRADE = "iDepGrade";
    /**负责人编码*/
    public static final String CDEPPERSON = "cDepPerson";
    /**部门属性*/
    public static final String CDEPPROP = "cDepProp";
    /**电话*/
    public static final String CDEPPHONE = "cDepPhone";
    /**地址*/
    public static final String CDEPADDRESS = "cDepAddress";
    /**备注*/
    public static final String CDEPMEMO = "cDepMemo";
    /**信用额度*/
    public static final String ICRELINE = "iCreLine";
    /**信用等级*/
    public static final String CCREGRADE = "cCreGrade";
    /**信用天数*/
    public static final String ICREDATE = "iCreDate";
    /**销售贡献等级*/
    public static final String COFFERGRADE = "cOfferGrade";
    /**销售贡献率*/
    public static final String IOFFERRATE = "iOfferRate";
    /**成立日期*/
    public static final String DDEPBEGINDATE = "dDepBeginDate";
    /**撤销日期*/
    public static final String DDEPENDDATE = "dDepEndDate";
    /**批准文号 */
    public static final String VAUTHORIZEDOC = "vAuthorizeDoc";
    /**批准单位 */
    public static final String VAUTHORIZEUNIT = "vAuthorizeUnit";
    /**部门类型*/
    public static final String CDEPTYPE = "cDepType";
    /**继承默认班次*/
    public static final String BINHERITDUTYBASIC = "bInheritDutyBasic";
    /**继承工作日历*/
    public static final String BINHERITWORKCALENDAR = "bInheritWorkCalendar";
    /**默认班次*/
    public static final String CDUTYCODE = "cDutyCode";
    /**英文名称*/
    public static final String CDEPNAMEEN = "cDepNameEn";
    /**部门全称*/
    public static final String CDEPFULLNAME = "cDepFullName";
    /**部门序号*/
    public static final String IDEPORDER = "iDepOrder";
    /**分管领导*/
    public static final String CDEPLEADER = "cDepLeader";
    /**类型：字典配置，参照jb_dept的类型*/
    public static final String CTYPE = "cType";
    /**是否启用：0. 否 1. 是*/
    public static final String ISENABLED = "isEnabled";
    /**是否参与排产：0. 否 1. 是*/
    public static final String ISAPSINVOLED = "isApsInvoled";
    /**负责人，用户ID*/
    public static final String IDUTYUSERID = "iDutyUserId";
    /**创建人ID*/
    public static final String ICREATEBY = "iCreateBy";
    /**创建人名称*/
    public static final String CCREATENAME = "cCreateName";
    /**创建时间*/
    public static final String DCREATETIME = "dCreateTime";
    /**更新人ID*/
    public static final String IUPDATEBY = "iUpdateBy";
    /**更新人名称*/
    public static final String CUPDATENAME = "cUpdateName";
    /**更新时间*/
    public static final String DUPDATETIME = "dUpdateTime";
    /**删除状态：0. 未删除 1. 已删除*/
    public static final String ISDELETED = "isDeleted";
    /**电子邮件*/
    public static final String CDEPEMAIL = "cDepEmail";
    /**邮政编码*/
    public static final String CDEPPOSTCODE = "cDepPostCode";
    /**传真*/
    public static final String CDEPFAX = "cDepFax";
    /**上级部门ID*/
    public static final String IPID = "iPid";
    /**来源: 1. MES 2. U8*/
    public static final String ISOURCE = "iSource";
    /**来源ID*/
    public static final String ISOURCEID = "iSourceId";
    /**是否禀议：0. 否 1. 是*/
    public static final String ISPROPOSAL = "isProposal";
    /**推单U8部门ID*/
    public static final String IREFDEPID = "iRefDepId";
    /**(不填,动态查询)负责人名称*/
    public static final String CDEPPERSONNAME = "cDepPersonName";
	/**
	 * 主键ID
	 */
	public M setIAutoId(java.lang.Long iAutoId) {
		set("iAutoId", iAutoId);
		return (M)this;
	}

	/**
	 * 主键ID
	 */
	@JBoltField(name="iautoid" ,columnName="iAutoId",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(name = "iautoid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAutoId() {
		return getLong("iAutoId");
	}

	/**
	 * 组织ID
	 */
	public M setIOrgId(java.lang.Long iOrgId) {
		set("iOrgId", iOrgId);
		return (M)this;
	}

	/**
	 * 组织ID
	 */
	@JBoltField(name="iorgid" ,columnName="iOrgId",type="Long", remark="组织ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(name = "iorgid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIOrgId() {
		return getLong("iOrgId");
	}

	/**
	 * 组织编码
	 */
	public M setCOrgCode(java.lang.String cOrgCode) {
		set("cOrgCode", cOrgCode);
		return (M)this;
	}

	/**
	 * 组织编码
	 */
	@JBoltField(name="corgcode" ,columnName="cOrgCode",type="String", remark="组织编码", required=true, maxLength=40, fixed=0, order=3)
	@JSONField(name = "corgcode")
	public java.lang.String getCOrgCode() {
		return getStr("cOrgCode");
	}

	/**
	 * 部门编码
	 */
	public M setCDepCode(java.lang.String cDepCode) {
		set("cDepCode", cDepCode);
		return (M)this;
	}

	/**
	 * 部门编码
	 */
	@JBoltField(name="cdepcode" ,columnName="cDepCode",type="String", remark="部门编码", required=true, maxLength=12, fixed=0, order=4)
	@JSONField(name = "cdepcode")
	public java.lang.String getCDepCode() {
		return getStr("cDepCode");
	}

	/**
	 * 是否末级：0. 否 1. 是
	 */
	public M setBDepEnd(java.lang.Boolean bDepEnd) {
		set("bDepEnd", bDepEnd);
		return (M)this;
	}

	/**
	 * 是否末级：0. 否 1. 是
	 */
	@JBoltField(name="bdepend" ,columnName="bDepEnd",type="Boolean", remark="是否末级：0. 否 1. 是", required=false, maxLength=1, fixed=0, order=5)
	@JSONField(name = "bdepend")
	public java.lang.Boolean getBDepEnd() {
		return getBoolean("bDepEnd");
	}

	/**
	 * 部门名称
	 */
	public M setCDepName(java.lang.String cDepName) {
		set("cDepName", cDepName);
		return (M)this;
	}

	/**
	 * 部门名称
	 */
	@JBoltField(name="cdepname" ,columnName="cDepName",type="String", remark="部门名称", required=true, maxLength=255, fixed=0, order=6)
	@JSONField(name = "cdepname")
	public java.lang.String getCDepName() {
		return getStr("cDepName");
	}

	/**
	 * 编码级次
	 */
	public M setIDepGrade(java.lang.Short iDepGrade) {
		set("iDepGrade", iDepGrade);
		return (M)this;
	}

	/**
	 * 编码级次
	 */
	@JBoltField(name="idepgrade" ,columnName="iDepGrade",type="", remark="编码级次", required=false, maxLength=3, fixed=0, order=7)
	@JSONField(name = "idepgrade")
	public java.lang.Short getIDepGrade() {
		return getShort("iDepGrade");
	}

	/**
	 * 负责人编码
	 */
	public M setCDepPerson(java.lang.String cDepPerson) {
		set("cDepPerson", cDepPerson);
		return (M)this;
	}

	/**
	 * 负责人编码
	 */
	@JBoltField(name="cdepperson" ,columnName="cDepPerson",type="String", remark="负责人编码", required=false, maxLength=20, fixed=0, order=8)
	@JSONField(name = "cdepperson")
	public java.lang.String getCDepPerson() {
		return getStr("cDepPerson");
	}

	/**
	 * 部门属性
	 */
	public M setCDepProp(java.lang.String cDepProp) {
		set("cDepProp", cDepProp);
		return (M)this;
	}

	/**
	 * 部门属性
	 */
	@JBoltField(name="cdepprop" ,columnName="cDepProp",type="String", remark="部门属性", required=false, maxLength=10, fixed=0, order=9)
	@JSONField(name = "cdepprop")
	public java.lang.String getCDepProp() {
		return getStr("cDepProp");
	}

	/**
	 * 电话
	 */
	public M setCDepPhone(java.lang.String cDepPhone) {
		set("cDepPhone", cDepPhone);
		return (M)this;
	}

	/**
	 * 电话
	 */
	@JBoltField(name="cdepphone" ,columnName="cDepPhone",type="String", remark="电话", required=false, maxLength=100, fixed=0, order=10)
	@JSONField(name = "cdepphone")
	public java.lang.String getCDepPhone() {
		return getStr("cDepPhone");
	}

	/**
	 * 地址
	 */
	public M setCDepAddress(java.lang.String cDepAddress) {
		set("cDepAddress", cDepAddress);
		return (M)this;
	}

	/**
	 * 地址
	 */
	@JBoltField(name="cdepaddress" ,columnName="cDepAddress",type="String", remark="地址", required=false, maxLength=255, fixed=0, order=11)
	@JSONField(name = "cdepaddress")
	public java.lang.String getCDepAddress() {
		return getStr("cDepAddress");
	}

	/**
	 * 备注
	 */
	public M setCDepMemo(java.lang.String cDepMemo) {
		set("cDepMemo", cDepMemo);
		return (M)this;
	}

	/**
	 * 备注
	 */
	@JBoltField(name="cdepmemo" ,columnName="cDepMemo",type="String", remark="备注", required=false, maxLength=20, fixed=0, order=12)
	@JSONField(name = "cdepmemo")
	public java.lang.String getCDepMemo() {
		return getStr("cDepMemo");
	}

	/**
	 * 信用额度
	 */
	public M setICreLine(java.lang.Double iCreLine) {
		set("iCreLine", iCreLine);
		return (M)this;
	}

	/**
	 * 信用额度
	 */
	@JBoltField(name="icreline" ,columnName="iCreLine",type="Double", remark="信用额度", required=false, maxLength=53, fixed=0, order=13)
	@JSONField(name = "icreline")
	public java.lang.Double getICreLine() {
		return getDouble("iCreLine");
	}

	/**
	 * 信用等级
	 */
	public M setCCreGrade(java.lang.String cCreGrade) {
		set("cCreGrade", cCreGrade);
		return (M)this;
	}

	/**
	 * 信用等级
	 */
	@JBoltField(name="ccregrade" ,columnName="cCreGrade",type="String", remark="信用等级", required=false, maxLength=20, fixed=0, order=14)
	@JSONField(name = "ccregrade")
	public java.lang.String getCCreGrade() {
		return getStr("cCreGrade");
	}

	/**
	 * 信用天数
	 */
	public M setICreDate(java.lang.Integer iCreDate) {
		set("iCreDate", iCreDate);
		return (M)this;
	}

	/**
	 * 信用天数
	 */
	@JBoltField(name="icredate" ,columnName="iCreDate",type="Integer", remark="信用天数", required=false, maxLength=10, fixed=0, order=15)
	@JSONField(name = "icredate")
	public java.lang.Integer getICreDate() {
		return getInt("iCreDate");
	}

	/**
	 * 销售贡献等级
	 */
	public M setCOfferGrade(java.lang.String cOfferGrade) {
		set("cOfferGrade", cOfferGrade);
		return (M)this;
	}

	/**
	 * 销售贡献等级
	 */
	@JBoltField(name="coffergrade" ,columnName="cOfferGrade",type="String", remark="销售贡献等级", required=false, maxLength=20, fixed=0, order=16)
	@JSONField(name = "coffergrade")
	public java.lang.String getCOfferGrade() {
		return getStr("cOfferGrade");
	}

	/**
	 * 销售贡献率
	 */
	public M setIOfferRate(java.lang.Double iOfferRate) {
		set("iOfferRate", iOfferRate);
		return (M)this;
	}

	/**
	 * 销售贡献率
	 */
	@JBoltField(name="iofferrate" ,columnName="iOfferRate",type="Double", remark="销售贡献率", required=false, maxLength=53, fixed=0, order=17)
	@JSONField(name = "iofferrate")
	public java.lang.Double getIOfferRate() {
		return getDouble("iOfferRate");
	}

	/**
	 * 成立日期
	 */
	public M setDDepBeginDate(java.util.Date dDepBeginDate) {
		set("dDepBeginDate", dDepBeginDate);
		return (M)this;
	}

	/**
	 * 成立日期
	 */
	@JBoltField(name="ddepbegindate" ,columnName="dDepBeginDate",type="Date", remark="成立日期", required=false, maxLength=23, fixed=3, order=18)
	@JSONField(name = "ddepbegindate")
	public java.util.Date getDDepBeginDate() {
		return getDate("dDepBeginDate");
	}

	/**
	 * 撤销日期
	 */
	public M setDDepEndDate(java.util.Date dDepEndDate) {
		set("dDepEndDate", dDepEndDate);
		return (M)this;
	}

	/**
	 * 撤销日期
	 */
	@JBoltField(name="ddependdate" ,columnName="dDepEndDate",type="Date", remark="撤销日期", required=false, maxLength=23, fixed=3, order=19)
	@JSONField(name = "ddependdate")
	public java.util.Date getDDepEndDate() {
		return getDate("dDepEndDate");
	}

	/**
	 * 批准文号 
	 */
	public M setVAuthorizeDoc(java.lang.String vAuthorizeDoc) {
		set("vAuthorizeDoc", vAuthorizeDoc);
		return (M)this;
	}

	/**
	 * 批准文号 
	 */
	@JBoltField(name="vauthorizedoc" ,columnName="vAuthorizeDoc",type="String", remark="批准文号 ", required=false, maxLength=50, fixed=0, order=20)
	@JSONField(name = "vauthorizedoc")
	public java.lang.String getVAuthorizeDoc() {
		return getStr("vAuthorizeDoc");
	}

	/**
	 * 批准单位 
	 */
	public M setVAuthorizeUnit(java.lang.String vAuthorizeUnit) {
		set("vAuthorizeUnit", vAuthorizeUnit);
		return (M)this;
	}

	/**
	 * 批准单位 
	 */
	@JBoltField(name="vauthorizeunit" ,columnName="vAuthorizeUnit",type="String", remark="批准单位 ", required=false, maxLength=100, fixed=0, order=21)
	@JSONField(name = "vauthorizeunit")
	public java.lang.String getVAuthorizeUnit() {
		return getStr("vAuthorizeUnit");
	}

	/**
	 * 部门类型
	 */
	public M setCDepType(java.lang.String cDepType) {
		set("cDepType", cDepType);
		return (M)this;
	}

	/**
	 * 部门类型
	 */
	@JBoltField(name="cdeptype" ,columnName="cDepType",type="String", remark="部门类型", required=false, maxLength=20, fixed=0, order=22)
	@JSONField(name = "cdeptype")
	public java.lang.String getCDepType() {
		return getStr("cDepType");
	}

	/**
	 * 继承默认班次
	 */
	public M setBInheritDutyBasic(java.lang.Integer bInheritDutyBasic) {
		set("bInheritDutyBasic", bInheritDutyBasic);
		return (M)this;
	}

	/**
	 * 继承默认班次
	 */
	@JBoltField(name="binheritdutybasic" ,columnName="bInheritDutyBasic",type="Integer", remark="继承默认班次", required=false, maxLength=10, fixed=0, order=23)
	@JSONField(name = "binheritdutybasic")
	public java.lang.Integer getBInheritDutyBasic() {
		return getInt("bInheritDutyBasic");
	}

	/**
	 * 继承工作日历
	 */
	public M setBInheritWorkCalendar(java.lang.Integer bInheritWorkCalendar) {
		set("bInheritWorkCalendar", bInheritWorkCalendar);
		return (M)this;
	}

	/**
	 * 继承工作日历
	 */
	@JBoltField(name="binheritworkcalendar" ,columnName="bInheritWorkCalendar",type="Integer", remark="继承工作日历", required=false, maxLength=10, fixed=0, order=24)
	@JSONField(name = "binheritworkcalendar")
	public java.lang.Integer getBInheritWorkCalendar() {
		return getInt("bInheritWorkCalendar");
	}

	/**
	 * 默认班次
	 */
	public M setCDutyCode(java.lang.String cDutyCode) {
		set("cDutyCode", cDutyCode);
		return (M)this;
	}

	/**
	 * 默认班次
	 */
	@JBoltField(name="cdutycode" ,columnName="cDutyCode",type="String", remark="默认班次", required=false, maxLength=50, fixed=0, order=25)
	@JSONField(name = "cdutycode")
	public java.lang.String getCDutyCode() {
		return getStr("cDutyCode");
	}

	/**
	 * 英文名称
	 */
	public M setCDepNameEn(java.lang.String cDepNameEn) {
		set("cDepNameEn", cDepNameEn);
		return (M)this;
	}

	/**
	 * 英文名称
	 */
	@JBoltField(name="cdepnameen" ,columnName="cDepNameEn",type="String", remark="英文名称", required=false, maxLength=255, fixed=0, order=26)
	@JSONField(name = "cdepnameen")
	public java.lang.String getCDepNameEn() {
		return getStr("cDepNameEn");
	}

	/**
	 * 部门全称
	 */
	public M setCDepFullName(java.lang.String cDepFullName) {
		set("cDepFullName", cDepFullName);
		return (M)this;
	}

	/**
	 * 部门全称
	 */
	@JBoltField(name="cdepfullname" ,columnName="cDepFullName",type="String", remark="部门全称", required=false, maxLength=800, fixed=0, order=27)
	@JSONField(name = "cdepfullname")
	public java.lang.String getCDepFullName() {
		return getStr("cDepFullName");
	}

	/**
	 * 部门序号
	 */
	public M setIDepOrder(java.lang.Integer iDepOrder) {
		set("iDepOrder", iDepOrder);
		return (M)this;
	}

	/**
	 * 部门序号
	 */
	@JBoltField(name="ideporder" ,columnName="iDepOrder",type="Integer", remark="部门序号", required=false, maxLength=10, fixed=0, order=28)
	@JSONField(name = "ideporder")
	public java.lang.Integer getIDepOrder() {
		return getInt("iDepOrder");
	}

	/**
	 * 分管领导
	 */
	public M setCDepLeader(java.lang.String cDepLeader) {
		set("cDepLeader", cDepLeader);
		return (M)this;
	}

	/**
	 * 分管领导
	 */
	@JBoltField(name="cdepleader" ,columnName="cDepLeader",type="String", remark="分管领导", required=false, maxLength=20, fixed=0, order=29)
	@JSONField(name = "cdepleader")
	public java.lang.String getCDepLeader() {
		return getStr("cDepLeader");
	}

	/**
	 * 类型：字典配置，参照jb_dept的类型
	 */
	public M setCType(java.lang.String cType) {
		set("cType", cType);
		return (M)this;
	}

	/**
	 * 类型：字典配置，参照jb_dept的类型
	 */
	@JBoltField(name="ctype" ,columnName="cType",type="String", remark="类型：字典配置，参照jb_dept的类型", required=true, maxLength=10, fixed=0, order=30)
	@JSONField(name = "ctype")
	public java.lang.String getCType() {
		return getStr("cType");
	}

	/**
	 * 是否启用：0. 否 1. 是
	 */
	public M setIsEnabled(java.lang.Boolean isEnabled) {
		set("isEnabled", isEnabled);
		return (M)this;
	}

	/**
	 * 是否启用：0. 否 1. 是
	 */
	@JBoltField(name="isenabled" ,columnName="isEnabled",type="Boolean", remark="是否启用：0. 否 1. 是", required=true, maxLength=1, fixed=0, order=31)
	@JSONField(name = "isenabled")
	public java.lang.Boolean getIsEnabled() {
		return getBoolean("isEnabled");
	}

	/**
	 * 是否参与排产：0. 否 1. 是
	 */
	public M setIsApsInvoled(java.lang.Boolean isApsInvoled) {
		set("isApsInvoled", isApsInvoled);
		return (M)this;
	}

	/**
	 * 是否参与排产：0. 否 1. 是
	 */
	@JBoltField(name="isapsinvoled" ,columnName="isApsInvoled",type="Boolean", remark="是否参与排产：0. 否 1. 是", required=true, maxLength=1, fixed=0, order=32)
	@JSONField(name = "isapsinvoled")
	public java.lang.Boolean getIsApsInvoled() {
		return getBoolean("isApsInvoled");
	}

	/**
	 * 负责人，用户ID
	 */
	public M setIDutyUserId(java.lang.Long iDutyUserId) {
		set("iDutyUserId", iDutyUserId);
		return (M)this;
	}

	/**
	 * 负责人，用户ID
	 */
	@JBoltField(name="idutyuserid" ,columnName="iDutyUserId",type="Long", remark="负责人，用户ID", required=false, maxLength=19, fixed=0, order=33)
	@JSONField(name = "idutyuserid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIDutyUserId() {
		return getLong("iDutyUserId");
	}

	/**
	 * 创建人ID
	 */
	public M setICreateBy(java.lang.Long iCreateBy) {
		set("iCreateBy", iCreateBy);
		return (M)this;
	}

	/**
	 * 创建人ID
	 */
	@JBoltField(name="icreateby" ,columnName="iCreateBy",type="Long", remark="创建人ID", required=true, maxLength=19, fixed=0, order=34)
	@JSONField(name = "icreateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getICreateBy() {
		return getLong("iCreateBy");
	}

	/**
	 * 创建人名称
	 */
	public M setCCreateName(java.lang.String cCreateName) {
		set("cCreateName", cCreateName);
		return (M)this;
	}

	/**
	 * 创建人名称
	 */
	@JBoltField(name="ccreatename" ,columnName="cCreateName",type="String", remark="创建人名称", required=true, maxLength=50, fixed=0, order=35)
	@JSONField(name = "ccreatename")
	public java.lang.String getCCreateName() {
		return getStr("cCreateName");
	}

	/**
	 * 创建时间
	 */
	public M setDCreateTime(java.util.Date dCreateTime) {
		set("dCreateTime", dCreateTime);
		return (M)this;
	}

	/**
	 * 创建时间
	 */
	@JBoltField(name="dcreatetime" ,columnName="dCreateTime",type="Date", remark="创建时间", required=true, maxLength=23, fixed=3, order=36)
	@JSONField(name = "dcreatetime")
	public java.util.Date getDCreateTime() {
		return getDate("dCreateTime");
	}

	/**
	 * 更新人ID
	 */
	public M setIUpdateBy(java.lang.Long iUpdateBy) {
		set("iUpdateBy", iUpdateBy);
		return (M)this;
	}

	/**
	 * 更新人ID
	 */
	@JBoltField(name="iupdateby" ,columnName="iUpdateBy",type="Long", remark="更新人ID", required=true, maxLength=19, fixed=0, order=37)
	@JSONField(name = "iupdateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIUpdateBy() {
		return getLong("iUpdateBy");
	}

	/**
	 * 更新人名称
	 */
	public M setCUpdateName(java.lang.String cUpdateName) {
		set("cUpdateName", cUpdateName);
		return (M)this;
	}

	/**
	 * 更新人名称
	 */
	@JBoltField(name="cupdatename" ,columnName="cUpdateName",type="String", remark="更新人名称", required=true, maxLength=50, fixed=0, order=38)
	@JSONField(name = "cupdatename")
	public java.lang.String getCUpdateName() {
		return getStr("cUpdateName");
	}

	/**
	 * 更新时间
	 */
	public M setDUpdateTime(java.util.Date dUpdateTime) {
		set("dUpdateTime", dUpdateTime);
		return (M)this;
	}

	/**
	 * 更新时间
	 */
	@JBoltField(name="dupdatetime" ,columnName="dUpdateTime",type="Date", remark="更新时间", required=true, maxLength=23, fixed=3, order=39)
	@JSONField(name = "dupdatetime")
	public java.util.Date getDUpdateTime() {
		return getDate("dUpdateTime");
	}

	/**
	 * 删除状态：0. 未删除 1. 已删除
	 */
	public M setIsDeleted(java.lang.Boolean isDeleted) {
		set("isDeleted", isDeleted);
		return (M)this;
	}

	/**
	 * 删除状态：0. 未删除 1. 已删除
	 */
	@JBoltField(name="isdeleted" ,columnName="isDeleted",type="Boolean", remark="删除状态：0. 未删除 1. 已删除", required=true, maxLength=1, fixed=0, order=40)
	@JSONField(name = "isdeleted")
	public java.lang.Boolean getIsDeleted() {
		return getBoolean("isDeleted");
	}

	/**
	 * 电子邮件
	 */
	public M setCDepEmail(java.lang.String cDepEmail) {
		set("cDepEmail", cDepEmail);
		return (M)this;
	}

	/**
	 * 电子邮件
	 */
	@JBoltField(name="cdepemail" ,columnName="cDepEmail",type="String", remark="电子邮件", required=false, maxLength=50, fixed=0, order=41)
	@JSONField(name = "cdepemail")
	public java.lang.String getCDepEmail() {
		return getStr("cDepEmail");
	}

	/**
	 * 邮政编码
	 */
	public M setCDepPostCode(java.lang.String cDepPostCode) {
		set("cDepPostCode", cDepPostCode);
		return (M)this;
	}

	/**
	 * 邮政编码
	 */
	@JBoltField(name="cdeppostcode" ,columnName="cDepPostCode",type="String", remark="邮政编码", required=false, maxLength=6, fixed=0, order=42)
	@JSONField(name = "cdeppostcode")
	public java.lang.String getCDepPostCode() {
		return getStr("cDepPostCode");
	}

	/**
	 * 传真
	 */
	public M setCDepFax(java.lang.String cDepFax) {
		set("cDepFax", cDepFax);
		return (M)this;
	}

	/**
	 * 传真
	 */
	@JBoltField(name="cdepfax" ,columnName="cDepFax",type="String", remark="传真", required=false, maxLength=20, fixed=0, order=43)
	@JSONField(name = "cdepfax")
	public java.lang.String getCDepFax() {
		return getStr("cDepFax");
	}

	/**
	 * 上级部门ID
	 */
	public M setIPid(java.lang.Long iPid) {
		set("iPid", iPid);
		return (M)this;
	}

	/**
	 * 上级部门ID
	 */
	@JBoltField(name="ipid" ,columnName="iPid",type="Long", remark="上级部门ID", required=false, maxLength=19, fixed=0, order=44)
	@JSONField(name = "ipid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIPid() {
		return getLong("iPid");
	}

	/**
	 * 来源: 1. MES 2. U8
	 */
	public M setISource(java.lang.Integer iSource) {
		set("iSource", iSource);
		return (M)this;
	}

	/**
	 * 来源: 1. MES 2. U8
	 */
	@JBoltField(name="isource" ,columnName="iSource",type="Integer", remark="来源: 1. MES 2. U8", required=true, maxLength=10, fixed=0, order=45)
	@JSONField(name = "isource")
	public java.lang.Integer getISource() {
		return getInt("iSource");
	}

	/**
	 * 来源ID
	 */
	public M setISourceId(java.lang.String iSourceId) {
		set("iSourceId", iSourceId);
		return (M)this;
	}

	/**
	 * 来源ID
	 */
	@JBoltField(name="isourceid" ,columnName="iSourceId",type="String", remark="来源ID", required=false, maxLength=32, fixed=0, order=46)
	@JSONField(name = "isourceid")
	public java.lang.String getISourceId() {
		return getStr("iSourceId");
	}

	/**
	 * 是否禀议：0. 否 1. 是
	 */
	public M setIsProposal(java.lang.Boolean isProposal) {
		set("isProposal", isProposal);
		return (M)this;
	}

	/**
	 * 是否禀议：0. 否 1. 是
	 */
	@JBoltField(name="isproposal" ,columnName="isProposal",type="Boolean", remark="是否禀议：0. 否 1. 是", required=true, maxLength=1, fixed=0, order=47)
	@JSONField(name = "isproposal")
	public java.lang.Boolean getIsProposal() {
		return getBoolean("isProposal");
	}

	/**
	 * 推单U8部门ID
	 */
	public M setIRefDepId(java.lang.Long iRefDepId) {
		set("iRefDepId", iRefDepId);
		return (M)this;
	}

	/**
	 * 推单U8部门ID
	 */
	@JBoltField(name="irefdepid" ,columnName="iRefDepId",type="Long", remark="推单U8部门ID", required=false, maxLength=19, fixed=0, order=48)
	@JSONField(name = "irefdepid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIRefDepId() {
		return getLong("iRefDepId");
	}

	/**
	 * (不填,动态查询)负责人名称
	 */
	public M setCDepPersonName(java.lang.String cDepPersonName) {
		set("cDepPersonName", cDepPersonName);
		return (M)this;
	}

	/**
	 * (不填,动态查询)负责人名称
	 */
	@JBoltField(name="cdeppersonname" ,columnName="cDepPersonName",type="String", remark="(不填,动态查询)负责人名称", required=false, maxLength=255, fixed=0, order=49)
	@JSONField(name = "cdeppersonname")
	public java.lang.String getCDepPersonName() {
		return getStr("cDepPersonName");
	}

}

