package cn.rjtech.model.momdata.base;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 申购单附件表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("unchecked")
public abstract class BasePurchaseAttachment<M extends BasePurchaseAttachment<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "momdata";
    /**主键ID*/
    public static final String IAUTOID = "iAutoId";
    /**申购单主表ID*/
    public static final String IPURCHASEMID = "iPurchaseMId";
    /**附件名称*/
    public static final String ATTACHMENTNAME = "AttachmentName";
    /**附件路径*/
    public static final String ATTACHMENTURI = "AttachmentUri";
	/**
	 * 主键ID
	 */
	public M setIAutoId(java.lang.Long iAutoId) {
		set("iAutoId", iAutoId);
		return (M)this;
	}

	/**
	 * 主键ID
	 */
	@JBoltField(name="iautoid" ,columnName="iAutoId",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(name = "iautoid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAutoId() {
		return getLong("iAutoId");
	}

	/**
	 * 申购单主表ID
	 */
	public M setIPurchaseMId(java.lang.Long iPurchaseMId) {
		set("iPurchaseMId", iPurchaseMId);
		return (M)this;
	}

	/**
	 * 申购单主表ID
	 */
	@JBoltField(name="ipurchasemid" ,columnName="iPurchaseMId",type="Long", remark="申购单主表ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(name = "ipurchasemid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIPurchaseMId() {
		return getLong("iPurchaseMId");
	}

	/**
	 * 附件名称
	 */
	public M setAttachmentName(java.lang.String AttachmentName) {
		set("AttachmentName", AttachmentName);
		return (M)this;
	}

	/**
	 * 附件名称
	 */
	@JBoltField(name="attachmentname" ,columnName="AttachmentName",type="String", remark="附件名称", required=false, maxLength=200, fixed=0, order=3)
	@JSONField(name = "attachmentname")
	public java.lang.String getAttachmentName() {
		return getStr("AttachmentName");
	}

	/**
	 * 附件路径
	 */
	public M setAttachmentUri(java.lang.String AttachmentUri) {
		set("AttachmentUri", AttachmentUri);
		return (M)this;
	}

	/**
	 * 附件路径
	 */
	@JBoltField(name="attachmenturi" ,columnName="AttachmentUri",type="String", remark="附件路径", required=false, maxLength=200, fixed=0, order=4)
	@JSONField(name = "attachmenturi")
	public java.lang.String getAttachmentUri() {
		return getStr("AttachmentUri");
	}

}

