package cn.rjtech.model.momdata.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 生产订单-备料单主表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMoPickItemM<M extends BaseMoPickItemM<M>> extends JBoltBaseModel<M>{
    /**主键ID*/
    public static final String IAUTOID = "iAutoId";
    /**组织ID*/
    public static final String IORGID = "iOrgId";
    /**组织编码*/
    public static final String CORGCODE = "cOrgCode";
    /**组织名称*/
    public static final String CORGNAME = "cOrgName";
    /**类型;1. 生产备料*/
    public static final String ITYPE = "iType";
    /**领料单号*/
    public static final String CMOPICKNO = "cMoPickNo";
    /**生产订单ID*/
    public static final String IMODOCID = "iMoDocId";
    /**生产订单号*/
    public static final String CMODOCNO = "cMoDocNo";
    /**计划日期*/
    public static final String DPLANDATE = "dPlanDate";
    /**计划数量*/
    public static final String IPLANQTY = "iPlanQty";
    /**状态;1. 待备料 2.备料中 3.已完成*/
    public static final String ISTATUS = "iStatus";
    /**创建人ID*/
    public static final String ICREATEBY = "iCreateBy";
    /**创建人名称*/
    public static final String CCREATENAME = "cCreateName";
    /**创建时间*/
    public static final String DCREATETIME = "dCreateTime";
    /**更新人ID*/
    public static final String IUPDATEBY = "iUpdateBy";
    /**更新人名称*/
    public static final String CUPDATENAME = "cUpdateName";
    /**更新时间*/
    public static final String DUPDATETIME = "dUpdateTime";
	/**
	 * 主键ID
	 */
	public M setIAutoId(java.lang.Long iAutoId) {
		set("iAutoId", iAutoId);
		return (M)this;
	}

	/**
	 * 主键ID
	 */
	@JBoltField(name="iautoid" ,columnName="iAutoId",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(name = "iautoid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAutoId() {
		return getLong("iAutoId");
	}

	/**
	 * 组织ID
	 */
	public M setIOrgId(java.lang.Long iOrgId) {
		set("iOrgId", iOrgId);
		return (M)this;
	}

	/**
	 * 组织ID
	 */
	@JBoltField(name="iorgid" ,columnName="iOrgId",type="Long", remark="组织ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(name = "iorgid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIOrgId() {
		return getLong("iOrgId");
	}

	/**
	 * 组织编码
	 */
	public M setCOrgCode(java.lang.String cOrgCode) {
		set("cOrgCode", cOrgCode);
		return (M)this;
	}

	/**
	 * 组织编码
	 */
	@JBoltField(name="corgcode" ,columnName="cOrgCode",type="String", remark="组织编码", required=true, maxLength=40, fixed=0, order=3)
	@JSONField(name = "corgcode")
	public java.lang.String getCOrgCode() {
		return getStr("cOrgCode");
	}

	/**
	 * 组织名称
	 */
	public M setCOrgName(java.lang.String cOrgName) {
		set("cOrgName", cOrgName);
		return (M)this;
	}

	/**
	 * 组织名称
	 */
	@JBoltField(name="corgname" ,columnName="cOrgName",type="String", remark="组织名称", required=true, maxLength=50, fixed=0, order=4)
	@JSONField(name = "corgname")
	public java.lang.String getCOrgName() {
		return getStr("cOrgName");
	}

	/**
	 * 类型;1. 生产备料
	 */
	public M setIType(java.lang.Integer iType) {
		set("iType", iType);
		return (M)this;
	}

	/**
	 * 类型;1. 生产备料
	 */
	@JBoltField(name="itype" ,columnName="iType",type="Integer", remark="类型;1. 生产备料", required=true, maxLength=10, fixed=0, order=5)
	@JSONField(name = "itype")
	public java.lang.Integer getIType() {
		return getInt("iType");
	}

	/**
	 * 领料单号
	 */
	public M setCMoPickNo(java.lang.String cMoPickNo) {
		set("cMoPickNo", cMoPickNo);
		return (M)this;
	}

	/**
	 * 领料单号
	 */
	@JBoltField(name="cmopickno" ,columnName="cMoPickNo",type="String", remark="领料单号", required=true, maxLength=40, fixed=0, order=6)
	@JSONField(name = "cmopickno")
	public java.lang.String getCMoPickNo() {
		return getStr("cMoPickNo");
	}

	/**
	 * 生产订单ID
	 */
	public M setIMoDocId(java.lang.Long iMoDocId) {
		set("iMoDocId", iMoDocId);
		return (M)this;
	}

	/**
	 * 生产订单ID
	 */
	@JBoltField(name="imodocid" ,columnName="iMoDocId",type="Long", remark="生产订单ID", required=true, maxLength=19, fixed=0, order=7)
	@JSONField(name = "imodocid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIMoDocId() {
		return getLong("iMoDocId");
	}

	/**
	 * 生产订单号
	 */
	public M setCMoDocNo(java.lang.String cMoDocNo) {
		set("cMoDocNo", cMoDocNo);
		return (M)this;
	}

	/**
	 * 生产订单号
	 */
	@JBoltField(name="cmodocno" ,columnName="cMoDocNo",type="String", remark="生产订单号", required=true, maxLength=40, fixed=0, order=8)
	@JSONField(name = "cmodocno")
	public java.lang.String getCMoDocNo() {
		return getStr("cMoDocNo");
	}

	/**
	 * 计划日期
	 */
	public M setDPlanDate(java.util.Date dPlanDate) {
		set("dPlanDate", dPlanDate);
		return (M)this;
	}

	/**
	 * 计划日期
	 */
	@JBoltField(name="dplandate" ,columnName="dPlanDate",type="Date", remark="计划日期", required=true, maxLength=10, fixed=0, order=9)
	@JSONField(name = "dplandate")
	public java.util.Date getDPlanDate() {
		return getDate("dPlanDate");
	}

	/**
	 * 计划数量
	 */
	public M setIPlanQty(java.math.BigDecimal iPlanQty) {
		set("iPlanQty", iPlanQty);
		return (M)this;
	}

	/**
	 * 计划数量
	 */
	@JBoltField(name="iplanqty" ,columnName="iPlanQty",type="BigDecimal", remark="计划数量", required=true, maxLength=24, fixed=6, order=10)
	@JSONField(name = "iplanqty")
	public java.math.BigDecimal getIPlanQty() {
		return getBigDecimal("iPlanQty");
	}

	/**
	 * 状态;1. 待备料 2.备料中 3.已完成
	 */
	public M setIStatus(java.lang.Integer iStatus) {
		set("iStatus", iStatus);
		return (M)this;
	}

	/**
	 * 状态;1. 待备料 2.备料中 3.已完成
	 */
	@JBoltField(name="istatus" ,columnName="iStatus",type="Integer", remark="状态;1. 待备料 2.备料中 3.已完成", required=true, maxLength=10, fixed=0, order=11)
	@JSONField(name = "istatus")
	public java.lang.Integer getIStatus() {
		return getInt("iStatus");
	}

	/**
	 * 创建人ID
	 */
	public M setICreateBy(java.lang.Long iCreateBy) {
		set("iCreateBy", iCreateBy);
		return (M)this;
	}

	/**
	 * 创建人ID
	 */
	@JBoltField(name="icreateby" ,columnName="iCreateBy",type="Long", remark="创建人ID", required=true, maxLength=19, fixed=0, order=12)
	@JSONField(name = "icreateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getICreateBy() {
		return getLong("iCreateBy");
	}

	/**
	 * 创建人名称
	 */
	public M setCCreateName(java.lang.String cCreateName) {
		set("cCreateName", cCreateName);
		return (M)this;
	}

	/**
	 * 创建人名称
	 */
	@JBoltField(name="ccreatename" ,columnName="cCreateName",type="String", remark="创建人名称", required=true, maxLength=40, fixed=0, order=13)
	@JSONField(name = "ccreatename")
	public java.lang.String getCCreateName() {
		return getStr("cCreateName");
	}

	/**
	 * 创建时间
	 */
	public M setDCreateTime(java.util.Date dCreateTime) {
		set("dCreateTime", dCreateTime);
		return (M)this;
	}

	/**
	 * 创建时间
	 */
	@JBoltField(name="dcreatetime" ,columnName="dCreateTime",type="Date", remark="创建时间", required=true, maxLength=23, fixed=3, order=14)
	@JSONField(name = "dcreatetime")
	public java.util.Date getDCreateTime() {
		return getDate("dCreateTime");
	}

	/**
	 * 更新人ID
	 */
	public M setIUpdateBy(java.lang.Long iUpdateBy) {
		set("iUpdateBy", iUpdateBy);
		return (M)this;
	}

	/**
	 * 更新人ID
	 */
	@JBoltField(name="iupdateby" ,columnName="iUpdateBy",type="Long", remark="更新人ID", required=true, maxLength=19, fixed=0, order=15)
	@JSONField(name = "iupdateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIUpdateBy() {
		return getLong("iUpdateBy");
	}

	/**
	 * 更新人名称
	 */
	public M setCUpdateName(java.lang.String cUpdateName) {
		set("cUpdateName", cUpdateName);
		return (M)this;
	}

	/**
	 * 更新人名称
	 */
	@JBoltField(name="cupdatename" ,columnName="cUpdateName",type="String", remark="更新人名称", required=true, maxLength=40, fixed=0, order=16)
	@JSONField(name = "cupdatename")
	public java.lang.String getCUpdateName() {
		return getStr("cUpdateName");
	}

	/**
	 * 更新时间
	 */
	public M setDUpdateTime(java.util.Date dUpdateTime) {
		set("dUpdateTime", dUpdateTime);
		return (M)this;
	}

	/**
	 * 更新时间
	 */
	@JBoltField(name="dupdatetime" ,columnName="dUpdateTime",type="Date", remark="更新时间", required=true, maxLength=23, fixed=3, order=17)
	@JSONField(name = "dupdatetime")
	public java.util.Date getDUpdateTime() {
		return getDate("dUpdateTime");
	}

}

