package cn.rjtech.model.momdata.base;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 形态转换单条码
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("unchecked")
public abstract class BaseSysAssembarcode<M extends BaseSysAssembarcode<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "momdata";
    /**AutoID*/
    public static final String AUTOID = "AutoID";
    /**明细表id*/
    public static final String MASID = "MasID";
    /**行号*/
    public static final String ROWNO = "RowNo";
    /**数量*/
    public static final String QTY = "Qty";
    /**条码*/
    public static final String BARCODE = "Barcode";
    /**存货编码*/
    public static final String INVCODE = "InvCode";
    /**是否删除：0. 否 1. 是*/
    public static final String ISDELETED = "isDeleted";
    /**创建人id*/
    public static final String ICREATEBY = "Icreateby";
    /**创建人名称*/
    public static final String CCREATENAME = "Ccreatename";
    /**创建时间*/
    public static final String DCREATETIME = "Dcreatetime";
    /**修改人id*/
    public static final String IUPDATEBY = "Iupdateby";
    /**修改人名称*/
    public static final String CUPDATENAME = "Cupdatename";
    /**修改时间*/
    public static final String DUPDATETIME = "Dupdatetime";
	/**
	 * AutoID
	 */
	public M setAutoID(java.lang.String AutoID) {
		set("AutoID", AutoID);
		return (M)this;
	}

	/**
	 * AutoID
	 */
	@JBoltField(name="autoid" ,columnName="AutoID",type="String", remark="AutoID", required=true, maxLength=30, fixed=0, order=1)
	@JSONField(name = "autoid")
	public java.lang.String getAutoID() {
		return getStr("AutoID");
	}

	/**
	 * 明细表id
	 */
	public M setMasID(java.lang.String MasID) {
		set("MasID", MasID);
		return (M)this;
	}

	/**
	 * 明细表id
	 */
	@JBoltField(name="masid" ,columnName="MasID",type="String", remark="明细表id", required=false, maxLength=30, fixed=0, order=2)
	@JSONField(name = "masid")
	public java.lang.String getMasID() {
		return getStr("MasID");
	}

	/**
	 * 行号
	 */
	public M setRowNo(java.lang.Integer RowNo) {
		set("RowNo", RowNo);
		return (M)this;
	}

	/**
	 * 行号
	 */
	@JBoltField(name="rowno" ,columnName="RowNo",type="Integer", remark="行号", required=false, maxLength=10, fixed=0, order=3)
	@JSONField(name = "rowno")
	public java.lang.Integer getRowNo() {
		return getInt("RowNo");
	}

	/**
	 * 数量
	 */
	public M setQty(java.math.BigDecimal Qty) {
		set("Qty", Qty);
		return (M)this;
	}

	/**
	 * 数量
	 */
	@JBoltField(name="qty" ,columnName="Qty",type="BigDecimal", remark="数量", required=false, maxLength=18, fixed=2, order=4)
	@JSONField(name = "qty")
	public java.math.BigDecimal getQty() {
		return getBigDecimal("Qty");
	}

	/**
	 * 条码
	 */
	public M setBarcode(java.lang.String Barcode) {
		set("Barcode", Barcode);
		return (M)this;
	}

	/**
	 * 条码
	 */
	@JBoltField(name="barcode" ,columnName="Barcode",type="String", remark="条码", required=false, maxLength=30, fixed=0, order=5)
	@JSONField(name = "barcode")
	public java.lang.String getBarcode() {
		return getStr("Barcode");
	}

	/**
	 * 存货编码
	 */
	public M setInvCode(java.lang.String InvCode) {
		set("InvCode", InvCode);
		return (M)this;
	}

	/**
	 * 存货编码
	 */
	@JBoltField(name="invcode" ,columnName="InvCode",type="String", remark="存货编码", required=false, maxLength=255, fixed=0, order=6)
	@JSONField(name = "invcode")
	public java.lang.String getInvCode() {
		return getStr("InvCode");
	}

	/**
	 * 是否删除：0. 否 1. 是
	 */
	public M setIsDeleted(java.lang.Boolean isDeleted) {
		set("isDeleted", isDeleted);
		return (M)this;
	}

	/**
	 * 是否删除：0. 否 1. 是
	 */
	@JBoltField(name="isdeleted" ,columnName="isDeleted",type="Boolean", remark="是否删除：0. 否 1. 是", required=false, maxLength=1, fixed=0, order=7)
	@JSONField(name = "isdeleted")
	public java.lang.Boolean getIsDeleted() {
		return getBoolean("isDeleted");
	}

	/**
	 * 创建人id
	 */
	public M setIcreateby(java.lang.Long Icreateby) {
		set("Icreateby", Icreateby);
		return (M)this;
	}

	/**
	 * 创建人id
	 */
	@JBoltField(name="icreateby" ,columnName="Icreateby",type="Long", remark="创建人id", required=false, maxLength=19, fixed=0, order=8)
	@JSONField(name = "icreateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIcreateby() {
		return getLong("Icreateby");
	}

	/**
	 * 创建人名称
	 */
	public M setCcreatename(java.lang.String Ccreatename) {
		set("Ccreatename", Ccreatename);
		return (M)this;
	}

	/**
	 * 创建人名称
	 */
	@JBoltField(name="ccreatename" ,columnName="Ccreatename",type="String", remark="创建人名称", required=false, maxLength=30, fixed=0, order=9)
	@JSONField(name = "ccreatename")
	public java.lang.String getCcreatename() {
		return getStr("Ccreatename");
	}

	/**
	 * 创建时间
	 */
	public M setDcreatetime(java.util.Date Dcreatetime) {
		set("Dcreatetime", Dcreatetime);
		return (M)this;
	}

	/**
	 * 创建时间
	 */
	@JBoltField(name="dcreatetime" ,columnName="Dcreatetime",type="Date", remark="创建时间", required=false, maxLength=23, fixed=3, order=10)
	@JSONField(name = "dcreatetime")
	public java.util.Date getDcreatetime() {
		return getDate("Dcreatetime");
	}

	/**
	 * 修改人id
	 */
	public M setIupdateby(java.lang.Long Iupdateby) {
		set("Iupdateby", Iupdateby);
		return (M)this;
	}

	/**
	 * 修改人id
	 */
	@JBoltField(name="iupdateby" ,columnName="Iupdateby",type="Long", remark="修改人id", required=false, maxLength=19, fixed=0, order=11)
	@JSONField(name = "iupdateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIupdateby() {
		return getLong("Iupdateby");
	}

	/**
	 * 修改人名称
	 */
	public M setCupdatename(java.lang.String Cupdatename) {
		set("Cupdatename", Cupdatename);
		return (M)this;
	}

	/**
	 * 修改人名称
	 */
	@JBoltField(name="cupdatename" ,columnName="Cupdatename",type="String", remark="修改人名称", required=false, maxLength=30, fixed=0, order=12)
	@JSONField(name = "cupdatename")
	public java.lang.String getCupdatename() {
		return getStr("Cupdatename");
	}

	/**
	 * 修改时间
	 */
	public M setDupdatetime(java.util.Date Dupdatetime) {
		set("Dupdatetime", Dupdatetime);
		return (M)this;
	}

	/**
	 * 修改时间
	 */
	@JBoltField(name="dupdatetime" ,columnName="Dupdatetime",type="Date", remark="修改时间", required=false, maxLength=23, fixed=3, order=13)
	@JSONField(name = "dupdatetime")
	public java.util.Date getDupdatetime() {
		return getDate("Dupdatetime");
	}

}

