package cn.rjtech.model.momdata.base;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 制造工单-工单工序作业指导书
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMoMoroutingsop<M extends BaseMoMoroutingsop<M>> extends JBoltBaseModel<M>{
    /**主键*/
    public static final String IAUTOID = "iAutoId";
    /**生产工单工艺ID*/
    public static final String IMOROUTINGCONFIGID = "iMoRoutingConfigId";
    /**料品工艺档案配置ID*/
    public static final String IINVENTORYROUTINGCONFIGID = "iInventoryRoutingConfigId";
    /**名称*/
    public static final String CNAME = "cName";
    /**路径*/
    public static final String CPATH = "cPath";
    /**文件类型*/
    public static final String CSUFFIX = "cSuffix";
    /**大小*/
    public static final String ISIZE = "iSize";
    /**版本号*/
    public static final String IVERSION = "iVersion";
    /**启用时间*/
    public static final String DFROMDATE = "dFromDate";
    /**停用时间*/
    public static final String DTODATE = "dToDate";
	/**
	 * 主键
	 */
	public M setIAutoId(Long iAutoId) {
		set("iAutoId", iAutoId);
		return (M)this;
	}

	/**
	 * 主键
	 */
	@JBoltField(name="iautoid" ,columnName="iAutoId",type="Long", remark="主键", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(name = "iautoid", serializeUsing = ToStringSerializer.class)
	public Long getIAutoId() {
		return getLong("iAutoId");
	}

	/**
	 * 生产工单工艺ID
	 */
	public M setIMoRoutingConfigId(Long iMoRoutingConfigId) {
		set("iMoRoutingConfigId", iMoRoutingConfigId);
		return (M)this;
	}

	/**
	 * 生产工单工艺ID
	 */
	@JBoltField(name="imoroutingconfigid" ,columnName="iMoRoutingConfigId",type="Long", remark="生产工单工艺ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(name = "imoroutingconfigid", serializeUsing = ToStringSerializer.class)
	public Long getIMoRoutingConfigId() {
		return getLong("iMoRoutingConfigId");
	}

	/**
	 * 料品工艺档案配置ID
	 */
	public M setIInventoryRoutingConfigId(Long iInventoryRoutingConfigId) {
		set("iInventoryRoutingConfigId", iInventoryRoutingConfigId);
		return (M)this;
	}

	/**
	 * 料品工艺档案配置ID
	 */
	@JBoltField(name="iinventoryroutingconfigid" ,columnName="iInventoryRoutingConfigId",type="Long", remark="料品工艺档案配置ID", required=true, maxLength=19, fixed=0, order=3)
	@JSONField(name = "iinventoryroutingconfigid", serializeUsing = ToStringSerializer.class)
	public Long getIInventoryRoutingConfigId() {
		return getLong("iInventoryRoutingConfigId");
	}

	/**
	 * 名称
	 */
	public M setCName(String cName) {
		set("cName", cName);
		return (M)this;
	}

	/**
	 * 名称
	 */
	@JBoltField(name="cname" ,columnName="cName",type="String", remark="名称", required=true, maxLength=255, fixed=0, order=4)
	@JSONField(name = "cname")
	public String getCName() {
		return getStr("cName");
	}

	/**
	 * 路径
	 */
	public M setCPath(String cPath) {
		set("cPath", cPath);
		return (M)this;
	}

	/**
	 * 路径
	 */
	@JBoltField(name="cpath" ,columnName="cPath",type="String", remark="路径", required=true, maxLength=255, fixed=0, order=5)
	@JSONField(name = "cpath")
	public String getCPath() {
		return getStr("cPath");
	}

	/**
	 * 文件类型
	 */
	public M setCSuffix(String cSuffix) {
		set("cSuffix", cSuffix);
		return (M)this;
	}

	/**
	 * 文件类型
	 */
	@JBoltField(name="csuffix" ,columnName="cSuffix",type="String", remark="文件类型", required=true, maxLength=255, fixed=0, order=6)
	@JSONField(name = "csuffix")
	public String getCSuffix() {
		return getStr("cSuffix");
	}

	/**
	 * 大小
	 */
	public M setISize(Integer iSize) {
		set("iSize", iSize);
		return (M)this;
	}

	/**
	 * 大小
	 */
	@JBoltField(name="isize" ,columnName="iSize",type="Integer", remark="大小", required=true, maxLength=10, fixed=0, order=7)
	@JSONField(name = "isize")
	public Integer getISize() {
		return getInt("iSize");
	}

	/**
	 * 版本号
	 */
	public M setIVersion(String iVersion) {
		set("iVersion", iVersion);
		return (M)this;
	}

	/**
	 * 版本号
	 */
	@JBoltField(name="iversion" ,columnName="iVersion",type="String", remark="版本号", required=true, maxLength=255, fixed=0, order=8)
	@JSONField(name = "iversion")
	public String getIVersion() {
		return getStr("iVersion");
	}

	/**
	 * 启用时间
	 */
	public M setDFromDate(java.util.Date dFromDate) {
		set("dFromDate", dFromDate);
		return (M)this;
	}

	/**
	 * 启用时间
	 */
	@JBoltField(name="dfromdate" ,columnName="dFromDate",type="Date", remark="启用时间", required=true, maxLength=23, fixed=3, order=9)
	@JSONField(name = "dfromdate")
	public java.util.Date getDFromDate() {
		return getDate("dFromDate");
	}

	/**
	 * 停用时间
	 */
	public M setDToDate(java.util.Date dToDate) {
		set("dToDate", dToDate);
		return (M)this;
	}

	/**
	 * 停用时间
	 */
	@JBoltField(name="dtodate" ,columnName="dToDate",type="Date", remark="停用时间", required=true, maxLength=23, fixed=3, order=10)
	@JSONField(name = "dtodate")
	public java.util.Date getDToDate() {
		return getDate("dToDate");
	}

}

