package cn.rjtech.model.momdata.base;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 产线刷卡记录
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("unchecked")
public abstract class BasePersonswipelog<M extends BasePersonswipelog<M>> extends JBoltBaseModel<M>{
    /**主键ID*/
    public static final String IAUTOID = "iAutoId";
    /**组织ID*/
    public static final String IORGID = "iOrgId";
    /**组织编码*/
    public static final String CORGCODE = "cOrgCode";
    /**组织名称*/
    public static final String CORGNAME = "cOrgName";
    /**人员ID*/
    public static final String IPERSONID = "iPersonId";
    /**用户ID*/
    public static final String IUSERID = "iUserId";
    /**卡号*/
    public static final String CECARDNO = "cEcardNo";
    /**用户名*/
    public static final String USERNAME = "username";
    /**姓名*/
    public static final String CPSN_NAME = "cPsn_Name";
    /**IP*/
    public static final String CIP = "cIp";
    /**创建人ID*/
    public static final String ICREATEBY = "iCreateBy";
    /**创建人名称*/
    public static final String CCREATENAME = "cCreateName";
    /**创建时间*/
    public static final String DCREATETIME = "dCreateTime";
    /**更新人ID*/
    public static final String IUPDATEBY = "iUpdateBy";
    /**更新人名称*/
    public static final String CUPDATENAME = "cUpdateName";
    /**更新时间*/
    public static final String DUPDATETIME = "dUpdateTime";
    /**删除状态;0. 未删除 1. 已删除*/
    public static final String ISDELETED = "isDeleted";
    /**结果*/
    public static final String CRESULT = "cResult";
    /**原因*/
    public static final String CCAUSE = "cCause";
    /**平板名称*/
    public static final String CPADNAME = "cPadName";
    /**平板编码*/
    public static final String CPADCODE = "cPadCode";
    /**产线名称*/
    public static final String CWORKNAME = "cWorkName";
    /**生产部门*/
    public static final String CDEPNAME = "cDepName";
	/**
	 * 主键ID
	 */
	public M setIAutoId(java.lang.Long iAutoId) {
		set("iAutoId", iAutoId);
		return (M)this;
	}

	/**
	 * 主键ID
	 */
	@JBoltField(name="iautoid" ,columnName="iAutoId",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(name = "iautoid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAutoId() {
		return getLong("iAutoId");
	}

	/**
	 * 组织ID
	 */
	public M setIOrgId(java.lang.Long iOrgId) {
		set("iOrgId", iOrgId);
		return (M)this;
	}

	/**
	 * 组织ID
	 */
	@JBoltField(name="iorgid" ,columnName="iOrgId",type="Long", remark="组织ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(name = "iorgid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIOrgId() {
		return getLong("iOrgId");
	}

	/**
	 * 组织编码
	 */
	public M setCOrgCode(java.lang.String cOrgCode) {
		set("cOrgCode", cOrgCode);
		return (M)this;
	}

	/**
	 * 组织编码
	 */
	@JBoltField(name="corgcode" ,columnName="cOrgCode",type="String", remark="组织编码", required=true, maxLength=40, fixed=0, order=3)
	@JSONField(name = "corgcode")
	public java.lang.String getCOrgCode() {
		return getStr("cOrgCode");
	}

	/**
	 * 组织名称
	 */
	public M setCOrgName(java.lang.String cOrgName) {
		set("cOrgName", cOrgName);
		return (M)this;
	}

	/**
	 * 组织名称
	 */
	@JBoltField(name="corgname" ,columnName="cOrgName",type="String", remark="组织名称", required=true, maxLength=40, fixed=0, order=4)
	@JSONField(name = "corgname")
	public java.lang.String getCOrgName() {
		return getStr("cOrgName");
	}

	/**
	 * 人员ID
	 */
	public M setIPersonId(java.lang.Long iPersonId) {
		set("iPersonId", iPersonId);
		return (M)this;
	}

	/**
	 * 人员ID
	 */
	@JBoltField(name="ipersonid" ,columnName="iPersonId",type="Long", remark="人员ID", required=true, maxLength=19, fixed=0, order=5)
	@JSONField(name = "ipersonid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIPersonId() {
		return getLong("iPersonId");
	}

	/**
	 * 用户ID
	 */
	public M setIUserId(java.lang.Long iUserId) {
		set("iUserId", iUserId);
		return (M)this;
	}

	/**
	 * 用户ID
	 */
	@JBoltField(name="iuserid" ,columnName="iUserId",type="Long", remark="用户ID", required=true, maxLength=19, fixed=0, order=6)
	@JSONField(name = "iuserid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIUserId() {
		return getLong("iUserId");
	}

	/**
	 * 卡号
	 */
	public M setCEcardNo(java.lang.String cEcardNo) {
		set("cEcardNo", cEcardNo);
		return (M)this;
	}

	/**
	 * 卡号
	 */
	@JBoltField(name="cecardno" ,columnName="cEcardNo",type="String", remark="卡号", required=true, maxLength=40, fixed=0, order=7)
	@JSONField(name = "cecardno")
	public java.lang.String getCEcardNo() {
		return getStr("cEcardNo");
	}

	/**
	 * 用户名
	 */
	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	/**
	 * 用户名
	 */
	@JBoltField(name="username" ,columnName="username",type="String", remark="用户名", required=true, maxLength=40, fixed=0, order=8)
	@JSONField(name = "username")
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * 姓名
	 */
	public M setCpsnName(java.lang.String cpsnName) {
		set("cPsn_Name", cpsnName);
		return (M)this;
	}

	/**
	 * 姓名
	 */
	@JBoltField(name="cpsnname" ,columnName="cPsn_Name",type="String", remark="姓名", required=true, maxLength=40, fixed=0, order=9)
	@JSONField(name = "cpsnname")
	public java.lang.String getCpsnName() {
		return getStr("cPsn_Name");
	}

	/**
	 * IP
	 */
	public M setCIp(java.lang.String cIp) {
		set("cIp", cIp);
		return (M)this;
	}

	/**
	 * IP
	 */
	@JBoltField(name="cip" ,columnName="cIp",type="String", remark="IP", required=true, maxLength=40, fixed=0, order=10)
	@JSONField(name = "cip")
	public java.lang.String getCIp() {
		return getStr("cIp");
	}

	/**
	 * 创建人ID
	 */
	public M setICreateBy(java.lang.Long iCreateBy) {
		set("iCreateBy", iCreateBy);
		return (M)this;
	}

	/**
	 * 创建人ID
	 */
	@JBoltField(name="icreateby" ,columnName="iCreateBy",type="Long", remark="创建人ID", required=true, maxLength=19, fixed=0, order=11)
	@JSONField(name = "icreateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getICreateBy() {
		return getLong("iCreateBy");
	}

	/**
	 * 创建人名称
	 */
	public M setCCreateName(java.lang.String cCreateName) {
		set("cCreateName", cCreateName);
		return (M)this;
	}

	/**
	 * 创建人名称
	 */
	@JBoltField(name="ccreatename" ,columnName="cCreateName",type="String", remark="创建人名称", required=true, maxLength=40, fixed=0, order=12)
	@JSONField(name = "ccreatename")
	public java.lang.String getCCreateName() {
		return getStr("cCreateName");
	}

	/**
	 * 创建时间
	 */
	public M setDCreateTime(java.util.Date dCreateTime) {
		set("dCreateTime", dCreateTime);
		return (M)this;
	}

	/**
	 * 创建时间
	 */
	@JBoltField(name="dcreatetime" ,columnName="dCreateTime",type="Date", remark="创建时间", required=true, maxLength=23, fixed=3, order=13)
	@JSONField(name = "dcreatetime")
	public java.util.Date getDCreateTime() {
		return getDate("dCreateTime");
	}

	/**
	 * 更新人ID
	 */
	public M setIUpdateBy(java.lang.Long iUpdateBy) {
		set("iUpdateBy", iUpdateBy);
		return (M)this;
	}

	/**
	 * 更新人ID
	 */
	@JBoltField(name="iupdateby" ,columnName="iUpdateBy",type="Long", remark="更新人ID", required=false, maxLength=19, fixed=0, order=14)
	@JSONField(name = "iupdateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIUpdateBy() {
		return getLong("iUpdateBy");
	}

	/**
	 * 更新人名称
	 */
	public M setCUpdateName(java.lang.String cUpdateName) {
		set("cUpdateName", cUpdateName);
		return (M)this;
	}

	/**
	 * 更新人名称
	 */
	@JBoltField(name="cupdatename" ,columnName="cUpdateName",type="String", remark="更新人名称", required=false, maxLength=40, fixed=0, order=15)
	@JSONField(name = "cupdatename")
	public java.lang.String getCUpdateName() {
		return getStr("cUpdateName");
	}

	/**
	 * 更新时间
	 */
	public M setDUpdateTime(java.util.Date dUpdateTime) {
		set("dUpdateTime", dUpdateTime);
		return (M)this;
	}

	/**
	 * 更新时间
	 */
	@JBoltField(name="dupdatetime" ,columnName="dUpdateTime",type="Date", remark="更新时间", required=false, maxLength=23, fixed=3, order=16)
	@JSONField(name = "dupdatetime")
	public java.util.Date getDUpdateTime() {
		return getDate("dUpdateTime");
	}

	/**
	 * 删除状态;0. 未删除 1. 已删除
	 */
	public M setIsDeleted(java.lang.Boolean isDeleted) {
		set("isDeleted", isDeleted);
		return (M)this;
	}

	/**
	 * 删除状态;0. 未删除 1. 已删除
	 */
	@JBoltField(name="isdeleted" ,columnName="isDeleted",type="Boolean", remark="删除状态;0. 未删除 1. 已删除", required=true, maxLength=1, fixed=0, order=17)
	@JSONField(name = "isdeleted")
	public java.lang.Boolean getIsDeleted() {
		return getBoolean("isDeleted");
	}

	/**
	 * 结果
	 */
	public M setCResult(java.lang.String cResult) {
		set("cResult", cResult);
		return (M)this;
	}

	/**
	 * 结果
	 */
	@JBoltField(name="cresult" ,columnName="cResult",type="String", remark="结果", required=true, maxLength=255, fixed=0, order=18)
	@JSONField(name = "cresult")
	public java.lang.String getCResult() {
		return getStr("cResult");
	}

	/**
	 * 原因
	 */
	public M setCCause(java.lang.String cCause) {
		set("cCause", cCause);
		return (M)this;
	}

	/**
	 * 原因
	 */
	@JBoltField(name="ccause" ,columnName="cCause",type="String", remark="原因", required=false, maxLength=255, fixed=0, order=19)
	@JSONField(name = "ccause")
	public java.lang.String getCCause() {
		return getStr("cCause");
	}

	/**
	 * 平板名称
	 */
	public M setCPadName(java.lang.String cPadName) {
		set("cPadName", cPadName);
		return (M)this;
	}

	/**
	 * 平板名称
	 */
	@JBoltField(name="cpadname" ,columnName="cPadName",type="String", remark="平板名称", required=true, maxLength=50, fixed=0, order=20)
	@JSONField(name = "cpadname")
	public java.lang.String getCPadName() {
		return getStr("cPadName");
	}

	/**
	 * 平板编码
	 */
	public M setCPadCode(java.lang.String cPadCode) {
		set("cPadCode", cPadCode);
		return (M)this;
	}

	/**
	 * 平板编码
	 */
	@JBoltField(name="cpadcode" ,columnName="cPadCode",type="String", remark="平板编码", required=true, maxLength=40, fixed=0, order=21)
	@JSONField(name = "cpadcode")
	public java.lang.String getCPadCode() {
		return getStr("cPadCode");
	}

	/**
	 * 产线名称
	 */
	public M setCWorkName(java.lang.String cWorkName) {
		set("cWorkName", cWorkName);
		return (M)this;
	}

	/**
	 * 产线名称
	 */
	@JBoltField(name="cworkname" ,columnName="cWorkName",type="String", remark="产线名称", required=true, maxLength=255, fixed=0, order=22)
	@JSONField(name = "cworkname")
	public java.lang.String getCWorkName() {
		return getStr("cWorkName");
	}

	/**
	 * 生产部门
	 */
	public M setCDepName(java.lang.String cDepName) {
		set("cDepName", cDepName);
		return (M)this;
	}

	/**
	 * 生产部门
	 */
	@JBoltField(name="cdepname" ,columnName="cDepName",type="String", remark="生产部门", required=true, maxLength=255, fixed=0, order=23)
	@JSONField(name = "cdepname")
	public java.lang.String getCDepName() {
		return getStr("cDepName");
	}

}

