package cn.rjtech.model.momdata.base;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 制造工单-生产退料明细
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("unchecked")
public abstract class BaseMoMaterialsreturnd<M extends BaseMoMaterialsreturnd<M>> extends JBoltBaseModel<M>{
    /**主键ID*/
    public static final String IAUTOID = "iAutoId";
    /**生产退料单ID*/
    public static final String IMATERIALSRETURNMID = "iMaterialsReturnMid";
    /**生产工单ID*/
    public static final String IMODOCID = "iMoDocId";
    /**存货ID*/
    public static final String IINVENTORYID = "iInventoryId";
    /**数量*/
    public static final String IQTY = "iQty";
	/** 编码**/
	private  static  String CBARCODE="cBarcode";
	/**
	 * 主键ID
	 */
	public M setIAutoId(java.lang.Long iAutoId) {
		set("iAutoId", iAutoId);
		return (M)this;
	}

	/**
	 * 主键ID
	 */
	@JBoltField(name="iautoid" ,columnName="iAutoId",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(name = "iautoid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAutoId() {
		return getLong("iAutoId");
	}

	/**
	 * 生产退料单ID
	 */
	public M setIMaterialsReturnMid(java.lang.Long iMaterialsReturnMid) {
		set("iMaterialsReturnMid", iMaterialsReturnMid);
		return (M)this;
	}

	/**
	 * 生产退料单ID
	 */
	@JBoltField(name="imaterialsreturnmid" ,columnName="iMaterialsReturnMid",type="Long", remark="生产退料单ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(name = "imaterialsreturnmid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIMaterialsReturnMid() {
		return getLong("iMaterialsReturnMid");
	}

	/**
	 * 生产工单ID
	 */
	public M setIMoDocId(java.lang.Long iMoDocId) {
		set("iMoDocId", iMoDocId);
		return (M)this;
	}

	/**
	 * 生产工单ID
	 */
	@JBoltField(name="imodocid" ,columnName="iMoDocId",type="Long", remark="生产工单ID", required=true, maxLength=19, fixed=0, order=3)
	@JSONField(name = "imodocid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIMoDocId() {
		return getLong("iMoDocId");
	}

	/**
	 * 存货ID
	 */
	public M setIInventoryId(java.lang.Long iInventoryId) {
		set("iInventoryId", iInventoryId);
		return (M)this;
	}

	/**
	 * 存货ID
	 */
	@JBoltField(name="iinventoryid" ,columnName="iInventoryId",type="Long", remark="存货ID", required=true, maxLength=19, fixed=0, order=4)
	@JSONField(name = "iinventoryid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIInventoryId() {
		return getLong("iInventoryId");
	}

	/**
	 * 数量
	 */
	public M setIQty(java.math.BigDecimal iQty) {
		set("iQty", iQty);
		return (M)this;
	}

	/**
	 * 数量
	 */
	@JBoltField(name="iqty" ,columnName="iQty",type="BigDecimal", remark="数量", required=true, maxLength=18, fixed=2, order=5)
	@JSONField(name = "iqty")
	public java.math.BigDecimal getIQty() {
		return getBigDecimal("iQty");
	}

	/**
	 * 条码
	 */
	public M setCbarcode(java.lang.String cBarcode) {
		set("cBarcode", cBarcode);
		return (M)this;
	}

	/**
	 * 条码
	 */
	@JBoltField(name="cBarcode" ,columnName="cBarcode",type="String", remark="条码", required=false, maxLength=200, fixed=0, order=10)
	@JSONField(name = "cBarcode")
	public java.lang.String getCbarcode() {
		return getStr("cBarcode");
	}


}

