package cn.rjtech.model.momdata.base;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 采购/委外-委外订单与到货计划关联
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSubcontractOrderRef<M extends BaseSubcontractOrderRef<M>> extends JBoltBaseModel<M>{
    /**主键ID*/
    public static final String IAUTOID = "iAutoId";
    /**销售订单明细ID*/
    public static final String ISUBCONTRACTORDERDID = "iSubContractOrderDid";
    /**到货计划明细ID*/
    public static final String IDEMANDPLANDID = "iDemandPlanDid";
	/**
	 * 主键ID
	 */
	public M setIAutoId(java.lang.Long iAutoId) {
		set("iAutoId", iAutoId);
		return (M)this;
	}

	/**
	 * 主键ID
	 */
	@JBoltField(name="iautoid" ,columnName="iAutoId",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(name = "iautoid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAutoId() {
		return getLong("iAutoId");
	}

	/**
	 * 销售订单明细ID
	 */
	public M setISubContractOrderDid(java.lang.Long iSubContractOrderDid) {
		set("iSubContractOrderDid", iSubContractOrderDid);
		return (M)this;
	}

	/**
	 * 销售订单明细ID
	 */
	@JBoltField(name="isubcontractorderdid" ,columnName="iSubContractOrderDid",type="Long", remark="销售订单明细ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(name = "isubcontractorderdid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getISubContractOrderDid() {
		return getLong("iSubContractOrderDid");
	}

	/**
	 * 到货计划明细ID
	 */
	public M setIDemandPlanDid(java.lang.Long iDemandPlanDid) {
		set("iDemandPlanDid", iDemandPlanDid);
		return (M)this;
	}

	/**
	 * 到货计划明细ID
	 */
	@JBoltField(name="idemandplandid" ,columnName="iDemandPlanDid",type="Long", remark="到货计划明细ID", required=true, maxLength=19, fixed=0, order=3)
	@JSONField(name = "idemandplandid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIDemandPlanDid() {
		return getLong("iDemandPlanDid");
	}

}

