package cn.rjtech.model.momdata.base;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 系统配置-编码规则
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("unchecked")
public abstract class BaseCodingRuleM<M extends BaseCodingRuleM<M>> extends JBoltBaseModel<M>{
    /**主键ID*/
    public static final String IAUTOID = "iAutoId";
    /**组织ID*/
    public static final String IORGID = "iOrgId";
    /**组织编码*/
    public static final String CORGCODE = "cOrgCode";
    /**组织名称*/
    public static final String CORGNAME = "cOrgName";
    /**业务对象类型;1. 单据类型 2. 条码号*/
    public static final String CFORMTYPESN = "cFormTypeSn";
    /**条码类型;1. 物料现品票 2.工单现品票*/
    public static final String CBARCODETYPESN = "cBarcodeTypeSn";
    /**表单ID*/
    public static final String IFORMID = "iFormId";
    /**编码方式;1. 自动生成编码，允许手工修改 2. 完全手工编码*/
    public static final String ICODINGTYPE = "iCodingType";
    /**编码示例*/
    public static final String CDEMO = "cDemo";
    /**创建人ID*/
    public static final String ICREATEBY = "iCreateBy";
    /**创建人名称*/
    public static final String CCREATENAME = "cCreateName";
    /**创建时间*/
    public static final String DCREATETIME = "dCreateTime";
    /**更新人ID*/
    public static final String IUPDATEBY = "iUpdateBy";
    /**更新人名称*/
    public static final String CUPDATENAME = "cUpdateName";
    /**更新时间*/
    public static final String DUPDATETIME = "dUpdateTime";
    /**删除状态;0. 未删除 1. 已删除*/
    public static final String ISDELETED = "IsDeleted";
	/**
	 * 主键ID
	 */
	public M setIAutoId(java.lang.Long iAutoId) {
		set("iAutoId", iAutoId);
		return (M)this;
	}

	/**
	 * 主键ID
	 */
	@JBoltField(name="iautoid" ,columnName="iAutoId",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(name = "iautoid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAutoId() {
		return getLong("iAutoId");
	}

	/**
	 * 组织ID
	 */
	public M setIOrgId(java.lang.Long iOrgId) {
		set("iOrgId", iOrgId);
		return (M)this;
	}

	/**
	 * 组织ID
	 */
	@JBoltField(name="iorgid" ,columnName="iOrgId",type="Long", remark="组织ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(name = "iorgid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIOrgId() {
		return getLong("iOrgId");
	}

	/**
	 * 组织编码
	 */
	public M setCOrgCode(java.lang.String cOrgCode) {
		set("cOrgCode", cOrgCode);
		return (M)this;
	}

	/**
	 * 组织编码
	 */
	@JBoltField(name="corgcode" ,columnName="cOrgCode",type="String", remark="组织编码", required=true, maxLength=40, fixed=0, order=3)
	@JSONField(name = "corgcode")
	public java.lang.String getCOrgCode() {
		return getStr("cOrgCode");
	}

	/**
	 * 组织名称
	 */
	public M setCOrgName(java.lang.String cOrgName) {
		set("cOrgName", cOrgName);
		return (M)this;
	}

	/**
	 * 组织名称
	 */
	@JBoltField(name="corgname" ,columnName="cOrgName",type="String", remark="组织名称", required=true, maxLength=40, fixed=0, order=4)
	@JSONField(name = "corgname")
	public java.lang.String getCOrgName() {
		return getStr("cOrgName");
	}

	/**
	 * 业务对象类型;1. 单据类型 2. 条码号
	 */
	public M setCFormTypeSn(java.lang.String cFormTypeSn) {
		set("cFormTypeSn", cFormTypeSn);
		return (M)this;
	}

	/**
	 * 业务对象类型;1. 单据类型 2. 条码号
	 */
	@JBoltField(name="cformtypesn" ,columnName="cFormTypeSn",type="String", remark="业务对象类型;1. 单据类型 2. 条码号", required=true, maxLength=10, fixed=0, order=5)
	@JSONField(name = "cformtypesn")
	public java.lang.String getCFormTypeSn() {
		return getStr("cFormTypeSn");
	}

	/**
	 * 条码类型;1. 物料现品票 2.工单现品票
	 */
	public M setCBarcodeTypeSn(java.lang.String cBarcodeTypeSn) {
		set("cBarcodeTypeSn", cBarcodeTypeSn);
		return (M)this;
	}

	/**
	 * 条码类型;1. 物料现品票 2.工单现品票
	 */
	@JBoltField(name="cbarcodetypesn" ,columnName="cBarcodeTypeSn",type="String", remark="条码类型;1. 物料现品票 2.工单现品票", required=false, maxLength=10, fixed=0, order=6)
	@JSONField(name = "cbarcodetypesn")
	public java.lang.String getCBarcodeTypeSn() {
		return getStr("cBarcodeTypeSn");
	}

	/**
	 * 表单ID
	 */
	public M setIFormId(java.lang.Long iFormId) {
		set("iFormId", iFormId);
		return (M)this;
	}

	/**
	 * 表单ID
	 */
	@JBoltField(name="iformid" ,columnName="iFormId",type="Long", remark="表单ID", required=false, maxLength=19, fixed=0, order=7)
	@JSONField(name = "iformid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIFormId() {
		return getLong("iFormId");
	}

	/**
	 * 编码方式;1. 自动生成编码，允许手工修改 2. 完全手工编码
	 */
	public M setICodingType(java.lang.Integer iCodingType) {
		set("iCodingType", iCodingType);
		return (M)this;
	}

	/**
	 * 编码方式;1. 自动生成编码，允许手工修改 2. 完全手工编码
	 */
	@JBoltField(name="icodingtype" ,columnName="iCodingType",type="Integer", remark="编码方式;1. 自动生成编码，允许手工修改 2. 完全手工编码", required=true, maxLength=10, fixed=0, order=8)
	@JSONField(name = "icodingtype")
	public java.lang.Integer getICodingType() {
		return getInt("iCodingType");
	}

	/**
	 * 编码示例
	 */
	public M setCDemo(java.lang.String cDemo) {
		set("cDemo", cDemo);
		return (M)this;
	}

	/**
	 * 编码示例
	 */
	@JBoltField(name="cdemo" ,columnName="cDemo",type="String", remark="编码示例", required=false, maxLength=100, fixed=0, order=9)
	@JSONField(name = "cdemo")
	public java.lang.String getCDemo() {
		return getStr("cDemo");
	}

	/**
	 * 创建人ID
	 */
	public M setICreateBy(java.lang.Long iCreateBy) {
		set("iCreateBy", iCreateBy);
		return (M)this;
	}

	/**
	 * 创建人ID
	 */
	@JBoltField(name="icreateby" ,columnName="iCreateBy",type="Long", remark="创建人ID", required=true, maxLength=19, fixed=0, order=10)
	@JSONField(name = "icreateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getICreateBy() {
		return getLong("iCreateBy");
	}

	/**
	 * 创建人名称
	 */
	public M setCCreateName(java.lang.String cCreateName) {
		set("cCreateName", cCreateName);
		return (M)this;
	}

	/**
	 * 创建人名称
	 */
	@JBoltField(name="ccreatename" ,columnName="cCreateName",type="String", remark="创建人名称", required=true, maxLength=60, fixed=0, order=11)
	@JSONField(name = "ccreatename")
	public java.lang.String getCCreateName() {
		return getStr("cCreateName");
	}

	/**
	 * 创建时间
	 */
	public M setDCreateTime(java.util.Date dCreateTime) {
		set("dCreateTime", dCreateTime);
		return (M)this;
	}

	/**
	 * 创建时间
	 */
	@JBoltField(name="dcreatetime" ,columnName="dCreateTime",type="Date", remark="创建时间", required=true, maxLength=23, fixed=3, order=12)
	@JSONField(name = "dcreatetime")
	public java.util.Date getDCreateTime() {
		return getDate("dCreateTime");
	}

	/**
	 * 更新人ID
	 */
	public M setIUpdateBy(java.lang.Long iUpdateBy) {
		set("iUpdateBy", iUpdateBy);
		return (M)this;
	}

	/**
	 * 更新人ID
	 */
	@JBoltField(name="iupdateby" ,columnName="iUpdateBy",type="Long", remark="更新人ID", required=true, maxLength=19, fixed=0, order=13)
	@JSONField(name = "iupdateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIUpdateBy() {
		return getLong("iUpdateBy");
	}

	/**
	 * 更新人名称
	 */
	public M setCUpdateName(java.lang.String cUpdateName) {
		set("cUpdateName", cUpdateName);
		return (M)this;
	}

	/**
	 * 更新人名称
	 */
	@JBoltField(name="cupdatename" ,columnName="cUpdateName",type="String", remark="更新人名称", required=true, maxLength=60, fixed=0, order=14)
	@JSONField(name = "cupdatename")
	public java.lang.String getCUpdateName() {
		return getStr("cUpdateName");
	}

	/**
	 * 更新时间
	 */
	public M setDUpdateTime(java.util.Date dUpdateTime) {
		set("dUpdateTime", dUpdateTime);
		return (M)this;
	}

	/**
	 * 更新时间
	 */
	@JBoltField(name="dupdatetime" ,columnName="dUpdateTime",type="Date", remark="更新时间", required=true, maxLength=23, fixed=3, order=15)
	@JSONField(name = "dupdatetime")
	public java.util.Date getDUpdateTime() {
		return getDate("dUpdateTime");
	}

	/**
	 * 删除状态;0. 未删除 1. 已删除
	 */
	public M setIsDeleted(java.lang.Boolean IsDeleted) {
		set("IsDeleted", IsDeleted);
		return (M)this;
	}

	/**
	 * 删除状态;0. 未删除 1. 已删除
	 */
	@JBoltField(name="isdeleted" ,columnName="IsDeleted",type="Boolean", remark="删除状态;0. 未删除 1. 已删除", required=true, maxLength=1, fixed=0, order=16)
	@JSONField(name = "isdeleted")
	public java.lang.Boolean getIsDeleted() {
		return getBoolean("IsDeleted");
	}

}

