package cn.rjtech.model.momdata.base;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 物料建模-Bom清单
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("unchecked")
public abstract class BaseBomCompare<M extends BaseBomCompare<M>> extends JBoltBaseModel<M>{
    /**主键ID*/
    public static final String IAUTOID = "iAutoId";
    /**组织ID*/
    public static final String IORGID = "iOrgId";
    /**组织编码*/
    public static final String CORGCODE = "cOrgCode";
    /**组织名称*/
    public static final String CORGNAME = "cOrgName";
    /**Bom母项ID*/
    public static final String IBOMMASTERID = "iBOMMasterId";
    /**料品档案ID*/
    public static final String IINVENTORYID = "iInventoryId";
    /**次序*/
    public static final String ISEQ = "iSeq";
    /**层级*/
    public static final String ILEVEL = "iLevel";
    /**层级文本，示例：1-1*/
    public static final String CINVLEV = "cInvLev";
    /**原材料类型：0.部品 1. 片料 2. 分条料 3. 卷料 */
    public static final String IRAWTYPE = "iRawType";
    /**单位用量/可制件数*/
    public static final String IQTY = "iQty";
    /**重量*/
    public static final String IWEIGHT = "iWeight";
    /**供应商ID*/
    public static final String IVENDORID = "iVendorId";
    /**是否外作：0. 否 1. 是*/
    public static final String ISOUTSOURCED = "isOutSourced";
    /**备注*/
    public static final String CMEMO = "cMemo";
    /**来源： 1.MES 2. U8*/
    public static final String ISOURCE = "iSource";
    /**来源标识ID*/
    public static final String ISOURCEID = "iSourceId";
    /**创建人ID*/
    public static final String ICREATEBY = "iCreateBy";
    /**创建人名称*/
    public static final String CCREATENAME = "cCreateName";
    /**创建时间*/
    public static final String DCREATETIME = "dCreateTime";
    /**更新人ID*/
    public static final String IUPDATEBY = "iUpdateBy";
    /**更新人名称*/
    public static final String CUPDATENAME = "cUpdateName";
    /**更新时间*/
    public static final String DUPDATETIME = "dUpdateTime";
    /**删除状态： 0. 未删除 1. 已删除*/
    public static final String ISDELETED = "isDeleted";
    
    public static final String IPID = "iPid";
	/**
	 * 主键ID
	 */
	public M setIAutoId(java.lang.Long iAutoId) {
		set("iAutoId", iAutoId);
		return (M)this;
	}

	/**
	 * 主键ID
	 */
	@JBoltField(name="iautoid" ,columnName="iAutoId",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(name = "iautoid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAutoId() {
		return getLong("iAutoId");
	}

	/**
	 * 组织ID
	 */
	public M setIOrgId(java.lang.Long iOrgId) {
		set("iOrgId", iOrgId);
		return (M)this;
	}

	/**
	 * 组织ID
	 */
	@JBoltField(name="iorgid" ,columnName="iOrgId",type="Long", remark="组织ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(name = "iorgid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIOrgId() {
		return getLong("iOrgId");
	}

	/**
	 * 组织编码
	 */
	public M setCOrgCode(java.lang.String cOrgCode) {
		set("cOrgCode", cOrgCode);
		return (M)this;
	}

	/**
	 * 组织编码
	 */
	@JBoltField(name="corgcode" ,columnName="cOrgCode",type="String", remark="组织编码", required=true, maxLength=40, fixed=0, order=3)
	@JSONField(name = "corgcode")
	public java.lang.String getCOrgCode() {
		return getStr("cOrgCode");
	}

	/**
	 * 组织名称
	 */
	public M setCOrgName(java.lang.String cOrgName) {
		set("cOrgName", cOrgName);
		return (M)this;
	}

	/**
	 * 组织名称
	 */
	@JBoltField(name="corgname" ,columnName="cOrgName",type="String", remark="组织名称", required=true, maxLength=50, fixed=0, order=4)
	@JSONField(name = "corgname")
	public java.lang.String getCOrgName() {
		return getStr("cOrgName");
	}

	/**
	 * Bom母项ID
	 */
	public M setIBOMMasterId(java.lang.Long iBOMMasterId) {
		set("iBOMMasterId", iBOMMasterId);
		return (M)this;
	}

	/**
	 * Bom母项ID
	 */
	@JBoltField(name="ibommasterid" ,columnName="iBOMMasterId",type="Long", remark="Bom母项ID", required=true, maxLength=19, fixed=0, order=5)
	@JSONField(name = "ibommasterid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIBOMMasterId() {
		return getLong("iBOMMasterId");
	}

	/**
	 * 料品档案ID
	 */
	public M setIInventoryId(java.lang.Long iInventoryId) {
		set("iInventoryId", iInventoryId);
		return (M)this;
	}

	/**
	 * 料品档案ID
	 */
	@JBoltField(name="iinventoryid" ,columnName="iInventoryId",type="Long", remark="料品档案ID", required=true, maxLength=19, fixed=0, order=6)
	@JSONField(name = "iinventoryid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIInventoryId() {
		return getLong("iInventoryId");
	}

	/**
	 * 次序
	 */
	public M setISeq(java.lang.Integer iSeq) {
		set("iSeq", iSeq);
		return (M)this;
	}

	/**
	 * 次序
	 */
	@JBoltField(name="iseq" ,columnName="iSeq",type="Integer", remark="次序", required=true, maxLength=10, fixed=0, order=7)
	@JSONField(name = "iseq")
	public java.lang.Integer getISeq() {
		return getInt("iSeq");
	}

	/**
	 * 层级
	 */
	public M setILevel(java.lang.Integer iLevel) {
		set("iLevel", iLevel);
		return (M)this;
	}

	/**
	 * 层级
	 */
	@JBoltField(name="ilevel" ,columnName="iLevel",type="Integer", remark="层级", required=true, maxLength=10, fixed=0, order=8)
	@JSONField(name = "ilevel")
	public java.lang.Integer getILevel() {
		return getInt("iLevel");
	}

	/**
	 * 层级文本，示例：1-1
	 */
	public M setCInvLev(java.lang.String cInvLev) {
		set("cInvLev", cInvLev);
		return (M)this;
	}

	/**
	 * 层级文本，示例：1-1
	 */
	@JBoltField(name="cinvlev" ,columnName="cInvLev",type="String", remark="层级文本，示例：1-1", required=true, maxLength=10, fixed=0, order=9)
	@JSONField(name = "cinvlev")
	public java.lang.String getCInvLev() {
		return getStr("cInvLev");
	}

	/**
	 * 原材料类型：0.部品 1. 片料 2. 分条料 3. 卷料
	 */
	public M setIRawType(java.lang.Integer iRawType) {
		set("iRawType", iRawType);
		return (M)this;
	}

	/**
	 * 原材料类型：0.部品 1. 片料 2. 分条料 3. 卷料
	 */
	@JBoltField(name="irawtype" ,columnName="iRawType",type="Integer", remark="原材料类型：0.部品 1. 片料 2. 分条料 3. 卷料 ", required=true, maxLength=10, fixed=0, order=10)
	@JSONField(name = "irawtype")
	public java.lang.Integer getIRawType() {
		return getInt("iRawType");
	}

	/**
	 * 单位用量/可制件数
	 */
	public M setIQty(java.math.BigDecimal iQty) {
		set("iQty", iQty);
		return (M)this;
	}

	/**
	 * 单位用量/可制件数
	 */
	@JBoltField(name="iqty" ,columnName="iQty",type="BigDecimal", remark="单位用量/可制件数", required=true, maxLength=24, fixed=6, order=11)
	@JSONField(name = "iqty")
	public java.math.BigDecimal getIQty() {
		return getBigDecimal("iQty");
	}

	/**
	 * 重量
	 */
	public M setIWeight(java.math.BigDecimal iWeight) {
		set("iWeight", iWeight);
		return (M)this;
	}

	/**
	 * 重量
	 */
	@JBoltField(name="iweight" ,columnName="iWeight",type="BigDecimal", remark="重量", required=false, maxLength=24, fixed=6, order=12)
	@JSONField(name = "iweight")
	public java.math.BigDecimal getIWeight() {
		return getBigDecimal("iWeight");
	}

	/**
	 * 供应商ID
	 */
	public M setIVendorId(java.lang.Long iVendorId) {
		set("iVendorId", iVendorId);
		return (M)this;
	}

	/**
	 * 供应商ID
	 */
	@JBoltField(name="ivendorid" ,columnName="iVendorId",type="Long", remark="供应商ID", required=false, maxLength=19, fixed=0, order=13)
	@JSONField(name = "ivendorid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIVendorId() {
		return getLong("iVendorId");
	}

	/**
	 * 是否外作：0. 否 1. 是
	 */
	public M setIsOutSourced(java.lang.Boolean isOutSourced) {
		set("isOutSourced", isOutSourced);
		return (M)this;
	}

	/**
	 * 是否外作：0. 否 1. 是
	 */
	@JBoltField(name="isoutsourced" ,columnName="isOutSourced",type="Boolean", remark="是否外作：0. 否 1. 是", required=true, maxLength=1, fixed=0, order=14)
	@JSONField(name = "isoutsourced")
	public java.lang.Boolean getIsOutSourced() {
		return getBoolean("isOutSourced");
	}

	/**
	 * 备注
	 */
	public M setCMemo(java.lang.String cMemo) {
		set("cMemo", cMemo);
		return (M)this;
	}

	/**
	 * 备注
	 */
	@JBoltField(name="cmemo" ,columnName="cMemo",type="String", remark="备注", required=false, maxLength=255, fixed=0, order=15)
	@JSONField(name = "cmemo")
	public java.lang.String getCMemo() {
		return getStr("cMemo");
	}

	/**
	 * 来源： 1.MES 2. U8
	 */
	public M setISource(java.lang.Integer iSource) {
		set("iSource", iSource);
		return (M)this;
	}

	/**
	 * 来源： 1.MES 2. U8
	 */
	@JBoltField(name="isource" ,columnName="iSource",type="Integer", remark="来源： 1.MES 2. U8", required=true, maxLength=10, fixed=0, order=16)
	@JSONField(name = "isource")
	public java.lang.Integer getISource() {
		return getInt("iSource");
	}

	/**
	 * 来源标识ID
	 */
	public M setISourceId(java.lang.String iSourceId) {
		set("iSourceId", iSourceId);
		return (M)this;
	}

	/**
	 * 来源标识ID
	 */
	@JBoltField(name="isourceid" ,columnName="iSourceId",type="String", remark="来源标识ID", required=false, maxLength=32, fixed=0, order=17)
	@JSONField(name = "isourceid")
	public java.lang.String getISourceId() {
		return getStr("iSourceId");
	}

	/**
	 * 创建人ID
	 */
	public M setICreateBy(java.lang.Long iCreateBy) {
		set("iCreateBy", iCreateBy);
		return (M)this;
	}

	/**
	 * 创建人ID
	 */
	@JBoltField(name="icreateby" ,columnName="iCreateBy",type="Long", remark="创建人ID", required=true, maxLength=19, fixed=0, order=18)
	@JSONField(name = "icreateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getICreateBy() {
		return getLong("iCreateBy");
	}

	/**
	 * 创建人名称
	 */
	public M setCCreateName(java.lang.String cCreateName) {
		set("cCreateName", cCreateName);
		return (M)this;
	}

	/**
	 * 创建人名称
	 */
	@JBoltField(name="ccreatename" ,columnName="cCreateName",type="String", remark="创建人名称", required=true, maxLength=50, fixed=0, order=19)
	@JSONField(name = "ccreatename")
	public java.lang.String getCCreateName() {
		return getStr("cCreateName");
	}

	/**
	 * 创建时间
	 */
	public M setDCreateTime(java.util.Date dCreateTime) {
		set("dCreateTime", dCreateTime);
		return (M)this;
	}

	/**
	 * 创建时间
	 */
	@JBoltField(name="dcreatetime" ,columnName="dCreateTime",type="Date", remark="创建时间", required=true, maxLength=23, fixed=3, order=20)
	@JSONField(name = "dcreatetime")
	public java.util.Date getDCreateTime() {
		return getDate("dCreateTime");
	}

	/**
	 * 更新人ID
	 */
	public M setIUpdateBy(java.lang.Long iUpdateBy) {
		set("iUpdateBy", iUpdateBy);
		return (M)this;
	}

	/**
	 * 更新人ID
	 */
	@JBoltField(name="iupdateby" ,columnName="iUpdateBy",type="Long", remark="更新人ID", required=true, maxLength=19, fixed=0, order=21)
	@JSONField(name = "iupdateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIUpdateBy() {
		return getLong("iUpdateBy");
	}

	/**
	 * 更新人名称
	 */
	public M setCUpdateName(java.lang.String cUpdateName) {
		set("cUpdateName", cUpdateName);
		return (M)this;
	}

	/**
	 * 更新人名称
	 */
	@JBoltField(name="cupdatename" ,columnName="cUpdateName",type="String", remark="更新人名称", required=true, maxLength=50, fixed=0, order=22)
	@JSONField(name = "cupdatename")
	public java.lang.String getCUpdateName() {
		return getStr("cUpdateName");
	}

	/**
	 * 更新时间
	 */
	public M setDUpdateTime(java.util.Date dUpdateTime) {
		set("dUpdateTime", dUpdateTime);
		return (M)this;
	}

	/**
	 * 更新时间
	 */
	@JBoltField(name="dupdatetime" ,columnName="dUpdateTime",type="Date", remark="更新时间", required=true, maxLength=23, fixed=3, order=23)
	@JSONField(name = "dupdatetime")
	public java.util.Date getDUpdateTime() {
		return getDate("dUpdateTime");
	}

	/**
	 * 删除状态： 0. 未删除 1. 已删除
	 */
	public M setIsDeleted(java.lang.Boolean isDeleted) {
		set("isDeleted", isDeleted);
		return (M)this;
	}

	/**
	 * 删除状态： 0. 未删除 1. 已删除
	 */
	@JBoltField(name="isdeleted" ,columnName="isDeleted",type="Boolean", remark="删除状态： 0. 未删除 1. 已删除", required=true, maxLength=1, fixed=0, order=24)
	@JSONField(name = "isdeleted")
	public java.lang.Boolean getIsDeleted() {
		return getBoolean("isDeleted");
	}
	
	/**
	 * 父id
	 */
	public M setIPid(java.lang.Long iPid) {
		set("iPid", iPid);
		return (M)this;
	}
	
	/**
	 * 父id
	 */
	@JBoltField(name="ipid" ,columnName="iPid",type="Long", remark="父id", required=true, maxLength=19, fixed=0, order=25)
	@JSONField(name = "ipid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIPid() {
		return getLong("iPid");
	}
}

