package cn.rjtech.model.momdata.base;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 稼动时间建模-稼动时间模板主表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("unchecked")
public abstract class BaseUptimeTplM<M extends BaseUptimeTplM<M>> extends JBoltBaseModel<M>{
    
    /**主键ID*/
    public static final String IAUTOID = "iAutoId";
    /**组织ID*/
    public static final String IORGID = "iOrgId";
    /**组织编码*/
    public static final String CORGCODE = "cOrgCode";
    /**组织名称*/
    public static final String CORGNAME = "cOrgName";
    /**产线ID*/
    public static final String IWORKREGIONMID = "iWorkRegionMid";
    /**班次ID*/
    public static final String IWORKSHIFTMID = "iWorkShiftMid";
    /**基本稼动时间（分钟）*/
    public static final String IBASEMINS = "iBaseMins";
    /**不稼动时间（分钟）*/
    public static final String ISTOPMINS = "iStopMins";
    /**机种切换时间（分钟）*/
    public static final String ISWITCHMINS = "iSwitchMins";
    /**加班时间（分钟）*/
    public static final String IOTMINS = "iOtMins";
    /**工作时间（分钟）*/
    public static final String IWORKMINS = "iWorkMins";
    /**创建人ID*/
    public static final String ICREATEBY = "iCreateBy";
    /**创建人名称*/
    public static final String CCREATENAME = "cCreateName";
    /**创建时间*/
    public static final String DCREATETIME = "dCreateTime";
    /**更新人ID*/
    public static final String IUPDATEBY = "iUpdateBy";
    /**更新人名称*/
    public static final String CUPDATENAME = "cUpdateName";
    /**更新时间*/
    public static final String DUPDATETIME = "dUpdateTime";
    /**删除状态;0. 未删除 1. 已删除*/
    public static final String ISDELETED = "isDeleted";
    /**是否启用：0. 否 1. 是*/
    public static final String ISENABLED = "isEnabled";
	/**
	 * 主键ID
	 */
	public M setIAutoId(java.lang.Long iAutoId) {
		set("iAutoId", iAutoId);
		return (M)this;
	}

	/**
	 * 主键ID
	 */
	@JBoltField(name="iautoid" ,columnName="iAutoId",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(name = "iautoid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIAutoId() {
		return getLong("iAutoId");
	}

	/**
	 * 组织ID
	 */
	public M setIOrgId(java.lang.Long iOrgId) {
		set("iOrgId", iOrgId);
		return (M)this;
	}

	/**
	 * 组织ID
	 */
	@JBoltField(name="iorgid" ,columnName="iOrgId",type="Long", remark="组织ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(name = "iorgid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIOrgId() {
		return getLong("iOrgId");
	}

	/**
	 * 组织编码
	 */
	public M setCOrgCode(java.lang.String cOrgCode) {
		set("cOrgCode", cOrgCode);
		return (M)this;
	}

	/**
	 * 组织编码
	 */
	@JBoltField(name="corgcode" ,columnName="cOrgCode",type="String", remark="组织编码", required=true, maxLength=40, fixed=0, order=3)
	@JSONField(name = "corgcode")
	public java.lang.String getCOrgCode() {
		return getStr("cOrgCode");
	}

	/**
	 * 组织名称
	 */
	public M setCOrgName(java.lang.String cOrgName) {
		set("cOrgName", cOrgName);
		return (M)this;
	}

	/**
	 * 组织名称
	 */
	@JBoltField(name="corgname" ,columnName="cOrgName",type="String", remark="组织名称", required=true, maxLength=40, fixed=0, order=4)
	@JSONField(name = "corgname")
	public java.lang.String getCOrgName() {
		return getStr("cOrgName");
	}

	/**
	 * 产线ID
	 */
	public M setIWorkRegionMid(java.lang.Long iWorkRegionMid) {
		set("iWorkRegionMid", iWorkRegionMid);
		return (M)this;
	}

	/**
	 * 产线ID
	 */
	@JBoltField(name="iworkregionmid" ,columnName="iWorkRegionMid",type="Long", remark="产线ID", required=true, maxLength=19, fixed=0, order=5)
	@JSONField(name = "iworkregionmid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIWorkRegionMid() {
		return getLong("iWorkRegionMid");
	}

	/**
	 * 班次ID
	 */
	public M setIWorkShiftMid(java.lang.Long iWorkShiftMid) {
		set("iWorkShiftMid", iWorkShiftMid);
		return (M)this;
	}

	/**
	 * 班次ID
	 */
	@JBoltField(name="iworkshiftmid" ,columnName="iWorkShiftMid",type="Long", remark="班次ID", required=true, maxLength=19, fixed=0, order=6)
	@JSONField(name = "iworkshiftmid", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIWorkShiftMid() {
		return getLong("iWorkShiftMid");
	}

	/**
	 * 基本稼动时间（分钟）
	 */
	public M setIBaseMins(java.lang.Integer iBaseMins) {
		set("iBaseMins", iBaseMins);
		return (M)this;
	}

	/**
	 * 基本稼动时间（分钟）
	 */
	@JBoltField(name="ibasemins" ,columnName="iBaseMins",type="Integer", remark="基本稼动时间（分钟）", required=true, maxLength=10, fixed=0, order=7)
	@JSONField(name = "ibasemins")
	public java.lang.Integer getIBaseMins() {
		return getInt("iBaseMins");
	}

	/**
	 * 不稼动时间（分钟）
	 */
	public M setIStopMins(java.lang.Integer iStopMins) {
		set("iStopMins", iStopMins);
		return (M)this;
	}

	/**
	 * 不稼动时间（分钟）
	 */
	@JBoltField(name="istopmins" ,columnName="iStopMins",type="Integer", remark="不稼动时间（分钟）", required=true, maxLength=10, fixed=0, order=8)
	@JSONField(name = "istopmins")
	public java.lang.Integer getIStopMins() {
		return getInt("iStopMins");
	}

	/**
	 * 机种切换时间（分钟）
	 */
	public M setISwitchMins(java.lang.Integer iSwitchMins) {
		set("iSwitchMins", iSwitchMins);
		return (M)this;
	}

	/**
	 * 机种切换时间（分钟）
	 */
	@JBoltField(name="iswitchmins" ,columnName="iSwitchMins",type="Integer", remark="机种切换时间（分钟）", required=true, maxLength=10, fixed=0, order=9)
	@JSONField(name = "iswitchmins")
	public java.lang.Integer getISwitchMins() {
		return getInt("iSwitchMins");
	}

	/**
	 * 加班时间（分钟）
	 */
	public M setIOtMins(java.lang.Integer iOtMins) {
		set("iOtMins", iOtMins);
		return (M)this;
	}

	/**
	 * 加班时间（分钟）
	 */
	@JBoltField(name="iotmins" ,columnName="iOtMins",type="Integer", remark="加班时间（分钟）", required=false, maxLength=10, fixed=0, order=10)
	@JSONField(name = "iotmins")
	public java.lang.Integer getIOtMins() {
		return getInt("iOtMins");
	}

	/**
	 * 工作时间（分钟）
	 */
	public M setIWorkMins(java.lang.Integer iWorkMins) {
		set("iWorkMins", iWorkMins);
		return (M)this;
	}

	/**
	 * 工作时间（分钟）
	 */
	@JBoltField(name="iworkmins" ,columnName="iWorkMins",type="Integer", remark="工作时间（分钟）", required=false, maxLength=10, fixed=0, order=11)
	@JSONField(name = "iworkmins")
	public java.lang.Integer getIWorkMins() {
		return getInt("iWorkMins");
	}

	/**
	 * 创建人ID
	 */
	public M setICreateBy(java.lang.Long iCreateBy) {
		set("iCreateBy", iCreateBy);
		return (M)this;
	}

	/**
	 * 创建人ID
	 */
	@JBoltField(name="icreateby" ,columnName="iCreateBy",type="Long", remark="创建人ID", required=true, maxLength=19, fixed=0, order=12)
	@JSONField(name = "icreateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getICreateBy() {
		return getLong("iCreateBy");
	}

	/**
	 * 创建人名称
	 */
	public M setCCreateName(java.lang.String cCreateName) {
		set("cCreateName", cCreateName);
		return (M)this;
	}

	/**
	 * 创建人名称
	 */
	@JBoltField(name="ccreatename" ,columnName="cCreateName",type="String", remark="创建人名称", required=true, maxLength=40, fixed=0, order=13)
	@JSONField(name = "ccreatename")
	public java.lang.String getCCreateName() {
		return getStr("cCreateName");
	}

	/**
	 * 创建时间
	 */
	public M setDCreateTime(java.util.Date dCreateTime) {
		set("dCreateTime", dCreateTime);
		return (M)this;
	}

	/**
	 * 创建时间
	 */
	@JBoltField(name="dcreatetime" ,columnName="dCreateTime",type="Date", remark="创建时间", required=true, maxLength=23, fixed=3, order=14)
	@JSONField(name = "dcreatetime")
	public java.util.Date getDCreateTime() {
		return getDate("dCreateTime");
	}

	/**
	 * 更新人ID
	 */
	public M setIUpdateBy(java.lang.Long iUpdateBy) {
		set("iUpdateBy", iUpdateBy);
		return (M)this;
	}

	/**
	 * 更新人ID
	 */
	@JBoltField(name="iupdateby" ,columnName="iUpdateBy",type="Long", remark="更新人ID", required=true, maxLength=19, fixed=0, order=15)
	@JSONField(name = "iupdateby", serializeUsing = ToStringSerializer.class)
	public java.lang.Long getIUpdateBy() {
		return getLong("iUpdateBy");
	}

	/**
	 * 更新人名称
	 */
	public M setCUpdateName(java.lang.String cUpdateName) {
		set("cUpdateName", cUpdateName);
		return (M)this;
	}

	/**
	 * 更新人名称
	 */
	@JBoltField(name="cupdatename" ,columnName="cUpdateName",type="String", remark="更新人名称", required=true, maxLength=40, fixed=0, order=16)
	@JSONField(name = "cupdatename")
	public java.lang.String getCUpdateName() {
		return getStr("cUpdateName");
	}

	/**
	 * 更新时间
	 */
	public M setDUpdateTime(java.util.Date dUpdateTime) {
		set("dUpdateTime", dUpdateTime);
		return (M)this;
	}

	/**
	 * 更新时间
	 */
	@JBoltField(name="dupdatetime" ,columnName="dUpdateTime",type="Date", remark="更新时间", required=true, maxLength=23, fixed=3, order=17)
	@JSONField(name = "dupdatetime")
	public java.util.Date getDUpdateTime() {
		return getDate("dUpdateTime");
	}

	/**
	 * 删除状态;0. 未删除 1. 已删除
	 */
	public M setIsDeleted(java.lang.Boolean isDeleted) {
		set("isDeleted", isDeleted);
		return (M)this;
	}

	/**
	 * 删除状态;0. 未删除 1. 已删除
	 */
	@JBoltField(name="isdeleted" ,columnName="isDeleted",type="Boolean", remark="删除状态;0. 未删除 1. 已删除", required=true, maxLength=1, fixed=0, order=18)
	@JSONField(name = "isdeleted")
	public java.lang.Boolean getIsDeleted() {
		return getBoolean("isDeleted");
	}

	/**
	 * 是否启用：0. 否 1. 是
	 */
	public M setIsEnabled(java.lang.Boolean isEnabled) {
		set("isEnabled", isEnabled);
		return (M)this;
	}

	/**
	 * 是否启用：0. 否 1. 是
	 */
	@JBoltField(name="isenabled" ,columnName="isEnabled",type="Boolean", remark="是否启用：0. 否 1. 是", required=true, maxLength=1, fixed=0, order=19)
	@JSONField(name = "isenabled")
	public java.lang.Boolean getIsEnabled() {
		return getBoolean("isEnabled");
	}

}

