package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseTodo;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.jbolt.core.cache.JBoltDictionaryCache;

/**
 * 待办事项
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "jb_todo" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Todo extends BaseTodo<Todo> {
	public String getTypeName() {
		return JBoltDictionaryCache.me.getNameBySn("todo_type", getType()+"");
	}
	public String getStateName() {
		return JBoltDictionaryCache.me.getNameBySn("todo_state", getState()+"");
	}
	public String getPriorityLevelName() {
		return JBoltDictionaryCache.me.getNameBySn("todo_priority_level", getPriorityLevel()+"");
	}
}
