package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWechatMedia;
import cn.jbolt.core.annotation.TableBind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "jb_wechat_media" , primaryKey = "id" , idGenMode = "snowflake")
public class WechatMedia extends BaseWechatMedia<WechatMedia> {
	public String getRealImgUrl() {
		return get("realImgUrl");
	}
	public String getRealVoiceUrl() {
		return get("realVoiceUrl");
	}
		
}
