package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWechatKeywords;
import cn.jbolt.core.annotation.TableBind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "jb_wechat_keywords" , primaryKey = "id" , idGenMode = "snowflake")
public class WechatKeywords extends BaseWechatKeywords<WechatKeywords> {

}
