package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWechatArticle;
import cn.jbolt.core.annotation.TableBind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "jb_wechat_article" , primaryKey = "id" , idGenMode = "snowflake")
public class WechatArticle extends BaseWechatArticle<WechatArticle> {
	
}
