package cn.rjtech.common.model;

import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.rjtech.common.model.base.BaseColumsmap;

/**
 * 字段映射主表
 * Generated by JBolt.
 */
@TableBind(dataSource = "momdata" , table = "T_Sys_ColumsMap" , primaryKey = "AutoID" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Columsmap extends BaseColumsmap<Columsmap> {
}

