package cn.rjtech.common.model;

import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.rjtech.common.model.base.BaseVouchProcessNote;

/**
 * 单据处理节点信息表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "momdata" , table = "T_Sys_VouchProcessNote" , primaryKey = "AutoID" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class VouchProcessNote extends BaseVouchProcessNote<VouchProcessNote> {
}

