package cn.jbolt.common.model.base;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

import cn.jbolt.core.gen.JBoltField;
import cn.jbolt.core.model.base.JBoltBaseModel;

/**
 * 系统操作日志表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSystemLog<M extends BaseSystemLog<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 标题
	 */
	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	/**
	 * 标题
	 */
	@JBoltField(name="title" ,columnName="title",type="String", remark="标题", required=false, maxLength=255, fixed=0, order=2)
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 操作类型 删除 更新 新增
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 操作类型 删除 更新 新增
	 */
	@JBoltField(name="type" ,columnName="type",type="Integer", remark="操作类型 删除 更新 新增", required=false, maxLength=10, fixed=0, order=3)
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 连接对象详情地址
	 */
	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	/**
	 * 连接对象详情地址
	 */
	@JBoltField(name="url" ,columnName="url",type="String", remark="连接对象详情地址", required=false, maxLength=255, fixed=0, order=4)
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 操作人ID
	 */
	public M setUserId(java.lang.Long userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 操作人ID
	 */
	@JBoltField(name="userId" ,columnName="user_id",type="Long", remark="操作人ID", required=false, maxLength=19, fixed=0, order=5)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	/**
	 * 操作人姓名
	 */
	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}
	
	/**
	 * 操作人姓名
	 */
	@JBoltField(name="userName" ,columnName="user_name",type="String", remark="操作人姓名", required=false, maxLength=255, fixed=0, order=6)
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	/**
	 * 操作对象类型
	 */
	public M setTargetType(java.lang.Integer targetType) {
		set("target_type", targetType);
		return (M)this;
	}
	
	/**
	 * 操作对象类型
	 */
	@JBoltField(name="targetType" ,columnName="target_type",type="Integer", remark="操作对象类型", required=false, maxLength=10, fixed=0, order=7)
	public java.lang.Integer getTargetType() {
		return getInt("target_type");
	}

	/**
	 * 记录创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 记录创建时间
	 */
	@JBoltField(name="createTime" ,columnName="create_time",type="Date", remark="记录创建时间", required=false, maxLength=19, fixed=0, order=8)
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 操作对象ID
	 */
	public M setTargetId(java.lang.Long targetId) {
		set("target_id", targetId);
		return (M)this;
	}
	
	/**
	 * 操作对象ID
	 */
	@JBoltField(name="targetId" ,columnName="target_id",type="Long", remark="操作对象ID", required=false, maxLength=19, fixed=0, order=9)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getTargetId() {
		return getLong("target_id");
	}

	/**
	 * 打开类型URL还是Dialog
	 */
	public M setOpenType(java.lang.Integer openType) {
		set("open_type", openType);
		return (M)this;
	}
	
	/**
	 * 打开类型URL还是Dialog
	 */
	@JBoltField(name="openType" ,columnName="open_type",type="Integer", remark="打开类型URL还是Dialog", required=false, maxLength=10, fixed=0, order=10)
	public java.lang.Integer getOpenType() {
		return getInt("open_type");
	}

}

