/*
 Navicat Premium Data Transfer

 Source Server         : oracle
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : localhost:1521
 Source Schema         : JBOLT_PLATFORM_MINI

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 20/06/2021 10:58:57
*/


-- ----------------------------
-- Table structure for JB_HIPRINT_TPL
-- ----------------------------
-- DROP TABLE "JBOLT"."JB_HIPRINT_TPL";
CREATE TABLE "JBOLT"."JB_HIPRINT_TPL" (
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(40) NOT NULL,
  "SN" NVARCHAR2(40) NOT NULL,
  "CONTENT" NCLOB NOT NULL,
  "REMARK" NVARCHAR2(255),
  "CREATE_TIME" TIMESTAMP(6) NOT NULL,
  "UPDATE_TIME" TIMESTAMP(6) NOT NULL,
  "CREATE_USER_ID" NUMBER(19,0) NOT NULL,
  "UPDATE_USER_ID" NUMBER(19,0) NOT NULL,
  "TEST_API_URL" NVARCHAR2(255),
  "TEST_JSON_DATA" NCLOB
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_HIPRINT_TPL"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_HIPRINT_TPL"."NAME" IS '模板名称';
COMMENT ON COLUMN "JBOLT"."JB_HIPRINT_TPL"."SN" IS '模板编码';
COMMENT ON COLUMN "JBOLT"."JB_HIPRINT_TPL"."CONTENT" IS '模板内容';
COMMENT ON COLUMN "JBOLT"."JB_HIPRINT_TPL"."REMARK" IS '备注';
COMMENT ON COLUMN "JBOLT"."JB_HIPRINT_TPL"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_HIPRINT_TPL"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "JBOLT"."JB_HIPRINT_TPL"."CREATE_USER_ID" IS '创建人';
COMMENT ON COLUMN "JBOLT"."JB_HIPRINT_TPL"."UPDATE_USER_ID" IS '更新人';
COMMENT ON COLUMN "JBOLT"."JB_HIPRINT_TPL"."TEST_API_URL" IS '测试API地址';
COMMENT ON COLUMN "JBOLT"."JB_HIPRINT_TPL"."TEST_JSON_DATA" IS '测试JSON数据';
COMMENT ON TABLE "JBOLT"."JB_HIPRINT_TPL" IS 'hiprint模板';

-- ----------------------------
-- Primary Key structure for table JB_HIPRINT_TPL
-- ----------------------------
ALTER TABLE "JBOLT"."JB_HIPRINT_TPL" ADD CONSTRAINT "SYS_C0010928" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_HIPRINT_TPL
-- ----------------------------
ALTER TABLE "JBOLT"."JB_HIPRINT_TPL" ADD CONSTRAINT "SYS_C0010920" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_HIPRINT_TPL" ADD CONSTRAINT "SYS_C0010921" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_HIPRINT_TPL" ADD CONSTRAINT "SYS_C0010922" CHECK ("SN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_HIPRINT_TPL" ADD CONSTRAINT "SYS_C0010923" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_HIPRINT_TPL" ADD CONSTRAINT "SYS_C0010924" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_HIPRINT_TPL" ADD CONSTRAINT "SYS_C0010925" CHECK ("UPDATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_HIPRINT_TPL" ADD CONSTRAINT "SYS_C0010926" CHECK ("CREATE_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_HIPRINT_TPL" ADD CONSTRAINT "SYS_C0010927" CHECK ("UPDATE_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;


-- ----------------------------
-- Table structure for JB_APPLICATION
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_APPLICATION";
CREATE TABLE "JBOLT"."JB_APPLICATION" (
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(255) NOT NULL,
  "BRIEF_INFO" NVARCHAR2(255),
  "APP_ID" NVARCHAR2(255) NOT NULL,
  "APP_SECRET" NVARCHAR2(255) NOT NULL,
  "ENABLE" CHAR(1) DEFAULT '0' NOT NULL,
  "CREATE_TIME" TIMESTAMP(6) NOT NULL,
  "UPDATE_TIME" TIMESTAMP(6) NOT NULL,
  "USER_ID" NUMBER(19,0) NOT NULL,
  "UPDATE_USER_ID" NUMBER(19,0) NOT NULL,
  "TYPE" NUMBER(9,0) NOT NULL,
  "NEED_CHECK_SIGN" CHAR(1) DEFAULT '0' NOT NULL,
  "IS_INNER" CHAR(1) DEFAULT '0' NOT NULL,
  "LINK_TARGET_ID" NUMBER(19,0)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_APPLICATION"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_APPLICATION"."NAME" IS '应用名称';
COMMENT ON COLUMN "JBOLT"."JB_APPLICATION"."BRIEF_INFO" IS '应用简介';
COMMENT ON COLUMN "JBOLT"."JB_APPLICATION"."APP_ID" IS '应用ID';
COMMENT ON COLUMN "JBOLT"."JB_APPLICATION"."APP_SECRET" IS '应用密钥';
COMMENT ON COLUMN "JBOLT"."JB_APPLICATION"."ENABLE" IS '是否启用';
COMMENT ON COLUMN "JBOLT"."JB_APPLICATION"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_APPLICATION"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "JBOLT"."JB_APPLICATION"."USER_ID" IS '创建用户ID';
COMMENT ON COLUMN "JBOLT"."JB_APPLICATION"."UPDATE_USER_ID" IS '更新用户ID';
COMMENT ON COLUMN "JBOLT"."JB_APPLICATION"."TYPE" IS 'app类型';
COMMENT ON COLUMN "JBOLT"."JB_APPLICATION"."NEED_CHECK_SIGN" IS '是否需要接口校验SIGN';
COMMENT ON COLUMN "JBOLT"."JB_APPLICATION"."IS_INNER" IS '是否系统内置';
COMMENT ON COLUMN "JBOLT"."JB_APPLICATION"."LINK_TARGET_ID" IS '关联目标ID';
COMMENT ON TABLE "JBOLT"."JB_APPLICATION" IS 'API应用中心的应用APP';
 
-- ----------------------------
-- Table structure for JB_DEPT
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_DEPT";
CREATE TABLE "JBOLT"."JB_DEPT" (
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(40) NOT NULL,
  "FULL_NAME" NVARCHAR2(40) NOT NULL,
  "PID" NUMBER(19,0),
  "TYPE" NVARCHAR2(40),
  "LEADER" NVARCHAR2(40),
  "PHONE" NVARCHAR2(40),
  "EMAIL" NVARCHAR2(100),
  "ADDRESS" NVARCHAR2(100),
  "ZIPCODE" NVARCHAR2(40),
  "REMARK" NVARCHAR2(255),
  "SN" NVARCHAR2(40),
  "SORT_RANK" NUMBER(9,0),
  "ENABLE" CHAR(1) DEFAULT '1' NOT NULL,
  "CREATE_TIME" TIMESTAMP(6),
  "UPDATE_TIME" TIMESTAMP(6)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."NAME" IS '部门名称';
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."FULL_NAME" IS '部门全称';
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."PID" IS '父级ID';
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."TYPE" IS '部门类型';
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."LEADER" IS '负责人';
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."PHONE" IS '手机';
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."EMAIL" IS '电子邮件';
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."ADDRESS" IS '地址';
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."ZIPCODE" IS '邮政编码';
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."REMARK" IS '备注';
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."SN" IS '部门编码';
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."SORT_RANK" IS '排序';
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."ENABLE" IS '启用';
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_DEPT"."UPDATE_TIME" IS '更新时间';
COMMENT ON TABLE "JBOLT"."JB_DEPT" IS '部门管理';

-- ----------------------------
-- Table structure for JB_DICTIONARY
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_DICTIONARY";
CREATE TABLE "JBOLT"."JB_DICTIONARY" (
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(255) NOT NULL,
  "TYPE_ID" NUMBER(19,0) NOT NULL,
  "PID" NUMBER(19,0) NOT NULL,
  "SORT_RANK" NUMBER(9,0) NOT NULL,
  "SN" NVARCHAR2(255),
  "TYPE_KEY" NVARCHAR2(40),
  "ENABLE" CHAR(1) DEFAULT '1' NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_DICTIONARY"."ID" IS '字典ID主键';
COMMENT ON COLUMN "JBOLT"."JB_DICTIONARY"."NAME" IS '名称';
COMMENT ON COLUMN "JBOLT"."JB_DICTIONARY"."TYPE_ID" IS '字典类型ID';
COMMENT ON COLUMN "JBOLT"."JB_DICTIONARY"."PID" IS '父类ID';
COMMENT ON COLUMN "JBOLT"."JB_DICTIONARY"."SORT_RANK" IS '排序';
COMMENT ON COLUMN "JBOLT"."JB_DICTIONARY"."SN" IS '编号编码';
COMMENT ON COLUMN "JBOLT"."JB_DICTIONARY"."TYPE_KEY" IS '字典类型KEY';
COMMENT ON COLUMN "JBOLT"."JB_DICTIONARY"."ENABLE" IS '是否启用';
COMMENT ON TABLE "JBOLT"."JB_DICTIONARY" IS '字典表';

-- ----------------------------
-- Table structure for JB_DICTIONARY_TYPE
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_DICTIONARY_TYPE";
CREATE TABLE "JBOLT"."JB_DICTIONARY_TYPE" (
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(255) NOT NULL,
  "MODE_LEVEL" NUMBER(9,0) NOT NULL,
  "TYPE_KEY" NVARCHAR2(255) NOT NULL,
  "ENABLE" CHAR(1) DEFAULT '1' NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_DICTIONARY_TYPE"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_DICTIONARY_TYPE"."MODE_LEVEL" IS '模式层级';
COMMENT ON COLUMN "JBOLT"."JB_DICTIONARY_TYPE"."TYPE_KEY" IS '标识KEY';
COMMENT ON COLUMN "JBOLT"."JB_DICTIONARY_TYPE"."ENABLE" IS '是否启用';
COMMENT ON TABLE "JBOLT"."JB_DICTIONARY_TYPE" IS '字典类型';


-- ----------------------------
-- Table structure for JB_GLOBAL_CONFIG
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_GLOBAL_CONFIG";
CREATE TABLE "JBOLT"."JB_GLOBAL_CONFIG" (
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(255) NOT NULL,
  "CONFIG_KEY" NVARCHAR2(255) NOT NULL,
  "CONFIG_VALUE" NVARCHAR2(255),
  "CREATE_TIME" TIMESTAMP(6) NOT NULL,
  "USER_ID" NUMBER(19,0),
  "UPDATE_TIME" TIMESTAMP(6) NOT NULL,
  "UPDATE_USER_ID" NUMBER(19,0) NOT NULL,
  "VALUE_TYPE" NVARCHAR2(40),
  "TYPE_KEY" NVARCHAR2(255),
  "TYPE_ID" NUMBER(19,0),
  "BUILT_IN" CHAR(1) DEFAULT '0' NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG"."NAME" IS '参数名';
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG"."CONFIG_KEY" IS '参数KEY';
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG"."CONFIG_VALUE" IS '参数值';
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG"."USER_ID" IS '创建用户ID';
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG"."UPDATE_USER_ID" IS '更新用户ID';
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG"."VALUE_TYPE" IS '值类型';
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG"."TYPE_KEY" IS '类型KEY';
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG"."TYPE_ID" IS '类型ID';
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG"."BUILT_IN" IS '系统内置';
COMMENT ON TABLE "JBOLT"."JB_GLOBAL_CONFIG" IS '全局配置';

-- ----------------------------
-- Table structure for JB_GLOBAL_CONFIG_TYPE
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_GLOBAL_CONFIG_TYPE";
CREATE TABLE "JBOLT"."JB_GLOBAL_CONFIG_TYPE" (
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(255) NOT NULL,
  "TYPE_KEY" NVARCHAR2(255) NOT NULL,
  "SORT_RANK" NUMBER(9,0) NOT NULL,
  "BUILT_IN" CHAR(1) DEFAULT '0' NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG_TYPE"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG_TYPE"."NAME" IS '参数名';
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG_TYPE"."TYPE_KEY" IS '类型KEY';
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG_TYPE"."SORT_RANK" IS '排序';
COMMENT ON COLUMN "JBOLT"."JB_GLOBAL_CONFIG_TYPE"."BUILT_IN" IS '系统内置';
COMMENT ON TABLE "JBOLT"."JB_GLOBAL_CONFIG_TYPE" IS '全局参数类型';


-- ----------------------------
-- Table structure for JB_JBOLT_FILE
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_JBOLT_FILE";
CREATE TABLE "JBOLT"."JB_JBOLT_FILE" (
  "ID" NUMBER(19,0) NOT NULL,
  "LOCAL_PATH" NVARCHAR2(255) NOT NULL,
  "LOCAL_URL" NVARCHAR2(255) NOT NULL,
  "CDN_URL" NVARCHAR2(255),
  "CREATE_TIME" TIMESTAMP(6) NOT NULL,
  "USER_ID" NUMBER(19,0),
  "FILE_NAME" NVARCHAR2(255) NOT NULL,
  "FILE_TYPE" NUMBER(9,0) NOT NULL,
  "FILE_SIZE" NUMBER(9,0) DEFAULT 0 NOT NULL,
  "FILE_SUFFIX" NVARCHAR2(255)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_JBOLT_FILE"."LOCAL_PATH" IS '保存物理地址';
COMMENT ON COLUMN "JBOLT"."JB_JBOLT_FILE"."LOCAL_URL" IS '本地可访问URL地址';
COMMENT ON COLUMN "JBOLT"."JB_JBOLT_FILE"."CDN_URL" IS '外部CDN地址';
COMMENT ON COLUMN "JBOLT"."JB_JBOLT_FILE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_JBOLT_FILE"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "JBOLT"."JB_JBOLT_FILE"."FILE_NAME" IS '文件名';
COMMENT ON COLUMN "JBOLT"."JB_JBOLT_FILE"."FILE_TYPE" IS '文件类型 图片 附件 视频 音频';
COMMENT ON COLUMN "JBOLT"."JB_JBOLT_FILE"."FILE_SIZE" IS '文件大小';
COMMENT ON COLUMN "JBOLT"."JB_JBOLT_FILE"."FILE_SUFFIX" IS '后缀名';
COMMENT ON TABLE "JBOLT"."JB_JBOLT_FILE" IS '文件库';

-- ----------------------------
-- Table structure for JB_LOGIN_LOG
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_LOGIN_LOG";
CREATE TABLE "JBOLT"."JB_LOGIN_LOG" (
  "ID" NUMBER(19,0) NOT NULL,
  "USER_ID" NUMBER(19,0),
  "USERNAME" NVARCHAR2(40) NOT NULL,
  "LOGIN_IP" NVARCHAR2(40),
  "LOGIN_TIME" TIMESTAMP(6) NOT NULL,
  "IS_BROWSER" CHAR(1 CHAR) DEFAULT 0,
  "BROWSER_VERSION" NVARCHAR2(40),
  "BROWSER_NAME" NVARCHAR2(100),
  "OS_NAME" NVARCHAR2(100),
  "LOGIN_CITY" NVARCHAR2(40),
  "LOGIN_ADDRESS" NVARCHAR2(255),
  "LOGIN_CITY_CODE" NVARCHAR2(40),
  "LOGIN_PROVINCE" NVARCHAR2(40),
  "LOGIN_COUNTRY" NVARCHAR2(40),
  "IS_MOBILE" CHAR(1 CHAR) DEFAULT 0,
  "OS_PLATFORM_NAME" NVARCHAR2(40),
  "BROWSER_ENGINE_NAME" NVARCHAR2(40),
  "BROWSER_ENGINE_VERSION" NVARCHAR2(40),
  "LOGIN_ADDRESS_LATITUDE" NVARCHAR2(40),
  "LOGIN_ADDRESS_LONGITUDE" NVARCHAR2(40),
  "IS_REMOTE_LOGIN" CHAR(1 CHAR) DEFAULT 0,
  "CREATE_TIME" TIMESTAMP(6),
  "LOGIN_STATE" NUMBER(9,0)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."USERNAME" IS '用户名';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."LOGIN_IP" IS 'IP地址';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."LOGIN_TIME" IS '登录时间';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."IS_BROWSER" IS '是否是浏览器访问';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."BROWSER_VERSION" IS '浏览器版本号';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."BROWSER_NAME" IS '浏览器';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."OS_NAME" IS '操作系统';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."LOGIN_CITY" IS '登录城市';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."LOGIN_ADDRESS" IS '登录位置详情';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."LOGIN_CITY_CODE" IS '登录城市代码';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."LOGIN_PROVINCE" IS '登录省份';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."LOGIN_COUNTRY" IS '登录国家';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."IS_MOBILE" IS '是否移动端';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."OS_PLATFORM_NAME" IS '平台名称';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."BROWSER_ENGINE_NAME" IS '浏览器引擎名';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."BROWSER_ENGINE_VERSION" IS '浏览器引擎版本';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."LOGIN_ADDRESS_LATITUDE" IS '登录地横坐标';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."LOGIN_ADDRESS_LONGITUDE" IS '登录地纵坐标';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."IS_REMOTE_LOGIN" IS '是否为异地异常登录';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."CREATE_TIME" IS '记录创建时间';
COMMENT ON COLUMN "JBOLT"."JB_LOGIN_LOG"."LOGIN_STATE" IS '登录状态';
COMMENT ON TABLE "JBOLT"."JB_LOGIN_LOG" IS '登录日志表';
 
-- ----------------------------
-- Table structure for JB_ONLINE_USER
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_ONLINE_USER";
CREATE TABLE "JBOLT"."JB_ONLINE_USER" (
  "ID" NUMBER(19,0) NOT NULL,
  "SESSION_ID" NVARCHAR2(255) NOT NULL,
  "USER_ID" NUMBER(19,0) NOT NULL,
  "LOGIN_LOG_ID" NUMBER(19,0) NOT NULL,
  "LOGIN_TIME" TIMESTAMP(6) NOT NULL,
  "UPDATE_TIME" TIMESTAMP(6) NOT NULL,
  "EXPIRATION_TIME" TIMESTAMP(6) NOT NULL,
  "SCREEN_LOCKED" CHAR(1) DEFAULT '0' NOT NULL,
  "ONLINE_STATE" NUMBER(9,0) NOT NULL,
  "OFFLINE_TIME" TIMESTAMP(6)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_ONLINE_USER"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_ONLINE_USER"."SESSION_ID" IS '会话ID';
COMMENT ON COLUMN "JBOLT"."JB_ONLINE_USER"."USER_ID" IS '用户';
COMMENT ON COLUMN "JBOLT"."JB_ONLINE_USER"."LOGIN_LOG_ID" IS '登录日志';
COMMENT ON COLUMN "JBOLT"."JB_ONLINE_USER"."LOGIN_TIME" IS '登录时间';
COMMENT ON COLUMN "JBOLT"."JB_ONLINE_USER"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "JBOLT"."JB_ONLINE_USER"."EXPIRATION_TIME" IS '过期时间';
COMMENT ON COLUMN "JBOLT"."JB_ONLINE_USER"."SCREEN_LOCKED" IS '是否锁屏';
COMMENT ON COLUMN "JBOLT"."JB_ONLINE_USER"."ONLINE_STATE" IS '在线状态';
COMMENT ON COLUMN "JBOLT"."JB_ONLINE_USER"."OFFLINE_TIME" IS '离线时间';

-- ----------------------------
-- Table structure for JB_PERMISSION
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_PERMISSION";
CREATE TABLE "JBOLT"."JB_PERMISSION" (
  "ID" NUMBER(19,0) NOT NULL,
  "TITLE" NVARCHAR2(40) NOT NULL,
  "PID" NUMBER(19,0) DEFAULT 0 NOT NULL,
  "URL" NVARCHAR2(255),
  "ICONS" NVARCHAR2(40),
  "SORT_RANK" NUMBER(9,0) NOT NULL,
  "PERMISSION_LEVEL" NUMBER(9,0) NOT NULL,
  "PERMISSION_KEY" NVARCHAR2(255) NOT NULL,
  "IS_MENU" CHAR(1) DEFAULT '0' NOT NULL,
  "IS_TARGET_BLANK" CHAR(1) DEFAULT '0' NOT NULL,
  "IS_SYSTEM_ADMIN_DEFAULT" CHAR(1) DEFAULT '0' NOT NULL,
  "OPEN_TYPE" NUMBER(9,0) DEFAULT 1,
  "OPEN_OPTION" NVARCHAR2(255)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_PERMISSION"."ID" IS '主键';
COMMENT ON COLUMN "JBOLT"."JB_PERMISSION"."URL" IS '地址';
COMMENT ON COLUMN "JBOLT"."JB_PERMISSION"."ICONS" IS '图标';
COMMENT ON COLUMN "JBOLT"."JB_PERMISSION"."SORT_RANK" IS '排序';
COMMENT ON COLUMN "JBOLT"."JB_PERMISSION"."PERMISSION_LEVEL" IS '层级';
COMMENT ON COLUMN "JBOLT"."JB_PERMISSION"."PERMISSION_KEY" IS '权限资源KEY';
COMMENT ON COLUMN "JBOLT"."JB_PERMISSION"."IS_MENU" IS '是否是菜单';
COMMENT ON COLUMN "JBOLT"."JB_PERMISSION"."IS_TARGET_BLANK" IS '是否新窗口打开';
COMMENT ON COLUMN "JBOLT"."JB_PERMISSION"."IS_SYSTEM_ADMIN_DEFAULT" IS '是否系统超级管理员默认拥有的权限';
COMMENT ON COLUMN "JBOLT"."JB_PERMISSION"."OPEN_TYPE" IS '打开类型 1 默认 2 iframe 3 dialog';
COMMENT ON COLUMN "JBOLT"."JB_PERMISSION"."OPEN_OPTION" IS '组件属性json';
COMMENT ON TABLE "JBOLT"."JB_PERMISSION" IS '权限资源定义';

-- ----------------------------
-- Table structure for JB_POST
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_POST";
CREATE TABLE "JBOLT"."JB_POST" (
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(40) NOT NULL,
  "TYPE" NVARCHAR2(40),
  "REMARK" NVARCHAR2(255),
  "SN" NVARCHAR2(40),
  "SORT_RANK" NUMBER(9,0),
  "ENABLE" CHAR(1) DEFAULT '1' NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_POST"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_POST"."NAME" IS '名称';
COMMENT ON COLUMN "JBOLT"."JB_POST"."TYPE" IS '类型';
COMMENT ON COLUMN "JBOLT"."JB_POST"."REMARK" IS '备注';
COMMENT ON COLUMN "JBOLT"."JB_POST"."SN" IS '编码';
COMMENT ON COLUMN "JBOLT"."JB_POST"."SORT_RANK" IS '排序';
COMMENT ON COLUMN "JBOLT"."JB_POST"."ENABLE" IS '启用';
COMMENT ON TABLE "JBOLT"."JB_POST" IS '岗位管理';

-- ----------------------------
-- Table structure for JB_PRIVATE_MESSAGE
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_PRIVATE_MESSAGE";
CREATE TABLE "JBOLT"."JB_PRIVATE_MESSAGE" (
  "ID" NUMBER(19,0) NOT NULL,
  "CONTENT" NCLOB NOT NULL,
  "CREATE_TIME" TIMESTAMP(6) NOT NULL,
  "FROM_USER_ID" NUMBER(19,0) NOT NULL,
  "TO_USER_ID" NUMBER(19,0) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_PRIVATE_MESSAGE"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_PRIVATE_MESSAGE"."CONTENT" IS '私信内容';
COMMENT ON COLUMN "JBOLT"."JB_PRIVATE_MESSAGE"."CREATE_TIME" IS '发送时间';
COMMENT ON COLUMN "JBOLT"."JB_PRIVATE_MESSAGE"."FROM_USER_ID" IS '发信人';
COMMENT ON COLUMN "JBOLT"."JB_PRIVATE_MESSAGE"."TO_USER_ID" IS '收信人';
COMMENT ON TABLE "JBOLT"."JB_PRIVATE_MESSAGE" IS '内部私信';

-- ----------------------------
-- Table structure for JB_REMOTE_LOGIN_LOG
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_REMOTE_LOGIN_LOG";
CREATE TABLE "JBOLT"."JB_REMOTE_LOGIN_LOG" (
  "ID" NUMBER(19,0) NOT NULL,
  "LAST_LOGIN_COUNTRY" NVARCHAR2(40),
  "LAST_LOGIN_PROVINCE" NVARCHAR2(40),
  "LAST_LOGIN_CITY" NVARCHAR2(40),
  "LAST_LOGIN_TIME" TIMESTAMP(6),
  "LOGIN_COUNTRY" NVARCHAR2(40),
  "LOGIN_PROVINCE" NVARCHAR2(40),
  "LOGIN_CITY" NVARCHAR2(40),
  "LOGIN_TIME" TIMESTAMP(6),
  "USER_ID" NUMBER(19,0),
  "USERNAME" NVARCHAR2(40),
  "IS_NEW" CHAR(1 CHAR) DEFAULT 1,
  "LAST_LOGIN_IP" NVARCHAR2(40),
  "LOGIN_IP" NVARCHAR2(40),
  "CREATE_TIME" TIMESTAMP(6)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_REMOTE_LOGIN_LOG"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_REMOTE_LOGIN_LOG"."LAST_LOGIN_COUNTRY" IS '最近一次登录国家';
COMMENT ON COLUMN "JBOLT"."JB_REMOTE_LOGIN_LOG"."LAST_LOGIN_PROVINCE" IS '最近一次登录省份';
COMMENT ON COLUMN "JBOLT"."JB_REMOTE_LOGIN_LOG"."LAST_LOGIN_CITY" IS '最近一次登录城市';
COMMENT ON COLUMN "JBOLT"."JB_REMOTE_LOGIN_LOG"."LAST_LOGIN_TIME" IS '最近一次登录时间';
COMMENT ON COLUMN "JBOLT"."JB_REMOTE_LOGIN_LOG"."LOGIN_COUNTRY" IS '新登录国家';
COMMENT ON COLUMN "JBOLT"."JB_REMOTE_LOGIN_LOG"."LOGIN_PROVINCE" IS '新登录省份';
COMMENT ON COLUMN "JBOLT"."JB_REMOTE_LOGIN_LOG"."LOGIN_CITY" IS '新登录城市';
COMMENT ON COLUMN "JBOLT"."JB_REMOTE_LOGIN_LOG"."LOGIN_TIME" IS '新登录时间';
COMMENT ON COLUMN "JBOLT"."JB_REMOTE_LOGIN_LOG"."USER_ID" IS '登录用户ID';
COMMENT ON COLUMN "JBOLT"."JB_REMOTE_LOGIN_LOG"."USERNAME" IS '登录用户名';
COMMENT ON COLUMN "JBOLT"."JB_REMOTE_LOGIN_LOG"."IS_NEW" IS '是否为最新一次';
COMMENT ON COLUMN "JBOLT"."JB_REMOTE_LOGIN_LOG"."LAST_LOGIN_IP" IS '最近一次登录IP';
COMMENT ON COLUMN "JBOLT"."JB_REMOTE_LOGIN_LOG"."LOGIN_IP" IS '新登录IP';
COMMENT ON COLUMN "JBOLT"."JB_REMOTE_LOGIN_LOG"."CREATE_TIME" IS '记录创建时间';
COMMENT ON TABLE "JBOLT"."JB_REMOTE_LOGIN_LOG" IS '异地登录日志记录';

-- ----------------------------
-- Table structure for JB_ROLE
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_ROLE";
CREATE TABLE "JBOLT"."JB_ROLE" (
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(20) NOT NULL,
  "SN" NVARCHAR2(40),
  "PID" NUMBER(19,0) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_ROLE"."ID" IS '主键';
COMMENT ON COLUMN "JBOLT"."JB_ROLE"."NAME" IS '名称';
COMMENT ON COLUMN "JBOLT"."JB_ROLE"."SN" IS '编码';
COMMENT ON COLUMN "JBOLT"."JB_ROLE"."PID" IS '父级角色ID';
COMMENT ON TABLE "JBOLT"."JB_ROLE" IS '角色表';

-- ----------------------------
-- Table structure for JB_ROLE_PERMISSION
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_ROLE_PERMISSION";
CREATE TABLE "JBOLT"."JB_ROLE_PERMISSION" (
  "ID" NUMBER(19,0) NOT NULL,
  "ROLE_ID" NUMBER(19,0) NOT NULL,
  "PERMISSION_ID" NUMBER(19,0) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_ROLE_PERMISSION"."ID" IS '主键';
COMMENT ON COLUMN "JBOLT"."JB_ROLE_PERMISSION"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "JBOLT"."JB_ROLE_PERMISSION"."PERMISSION_ID" IS '权限ID';
COMMENT ON TABLE "JBOLT"."JB_ROLE_PERMISSION" IS '角色功能列表';

-- ----------------------------
-- Table structure for JB_SYSTEM_LOG
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_SYSTEM_LOG";
CREATE TABLE "JBOLT"."JB_SYSTEM_LOG" (
  "ID" NUMBER(19,0) NOT NULL,
  "TITLE" NVARCHAR2(255),
  "TYPE" NUMBER(9,0),
  "URL" NVARCHAR2(255),
  "USER_ID" NUMBER(19,0),
  "USER_NAME" NVARCHAR2(255),
  "TARGET_TYPE" NUMBER(9,0),
  "CREATE_TIME" TIMESTAMP(6),
  "TARGET_ID" NUMBER(19,0),
  "OPEN_TYPE" NUMBER(9,0)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_SYSTEM_LOG"."ID" IS '主键';
COMMENT ON COLUMN "JBOLT"."JB_SYSTEM_LOG"."TITLE" IS '标题';
COMMENT ON COLUMN "JBOLT"."JB_SYSTEM_LOG"."TYPE" IS '操作类型 删除 更新 新增';
COMMENT ON COLUMN "JBOLT"."JB_SYSTEM_LOG"."URL" IS '连接对象详情地址';
COMMENT ON COLUMN "JBOLT"."JB_SYSTEM_LOG"."USER_ID" IS '操作人ID';
COMMENT ON COLUMN "JBOLT"."JB_SYSTEM_LOG"."USER_NAME" IS '操作人姓名';
COMMENT ON COLUMN "JBOLT"."JB_SYSTEM_LOG"."TARGET_TYPE" IS '操作对象类型';
COMMENT ON COLUMN "JBOLT"."JB_SYSTEM_LOG"."CREATE_TIME" IS '记录创建时间';
COMMENT ON COLUMN "JBOLT"."JB_SYSTEM_LOG"."TARGET_ID" IS '操作对象ID';
COMMENT ON COLUMN "JBOLT"."JB_SYSTEM_LOG"."OPEN_TYPE" IS '打开类型URL还是Dialog';
COMMENT ON TABLE "JBOLT"."JB_SYSTEM_LOG" IS '系统操作日志表';

-- ----------------------------
-- Table structure for JB_SYS_NOTICE
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_SYS_NOTICE";
CREATE TABLE "JBOLT"."JB_SYS_NOTICE" (
  "ID" NUMBER(19,0) NOT NULL,
  "TITLE" NVARCHAR2(255) NOT NULL,
  "CONTENT" NCLOB NOT NULL,
  "TYPE" NUMBER(9,0) NOT NULL,
  "PRIORITY_LEVEL" NUMBER(9,0) NOT NULL,
  "READ_COUNT" NUMBER(9,0),
  "CREATE_TIME" TIMESTAMP(6) NOT NULL,
  "UPDATE_TIME" TIMESTAMP(6),
  "CREATE_USER_ID" NUMBER(19,0),
  "UPDATE_USER_ID" NUMBER(19,0),
  "RECEIVER_TYPE" NUMBER(9,0),
  "RECEIVER_VALUE" NCLOB,
  "FILES" NVARCHAR2(255),
  "DEL_FLAG" CHAR(1) DEFAULT '0' NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE"."TITLE" IS '标题';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE"."CONTENT" IS '消息内容';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE"."TYPE" IS '通知类型';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE"."PRIORITY_LEVEL" IS '优先级';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE"."READ_COUNT" IS '已读人数';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE"."CREATE_USER_ID" IS '创建人';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE"."UPDATE_USER_ID" IS '更新人';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE"."RECEIVER_TYPE" IS '接收人类型';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE"."RECEIVER_VALUE" IS '接收人值';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE"."FILES" IS '附件';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE"."DEL_FLAG" IS '删除标志';
COMMENT ON TABLE "JBOLT"."JB_SYS_NOTICE" IS '系统通知';

-- ----------------------------
-- Table structure for JB_SYS_NOTICE_READER
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_SYS_NOTICE_READER";
CREATE TABLE "JBOLT"."JB_SYS_NOTICE_READER" (
  "ID" NUMBER(19,0) NOT NULL,
  "SYS_NOTICE_ID" NUMBER(19,0) NOT NULL,
  "USER_ID" NUMBER(19,0) NOT NULL,
  "CREATE_TIME" TIMESTAMP(6) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE_READER"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE_READER"."SYS_NOTICE_ID" IS '通知ID';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE_READER"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "JBOLT"."JB_SYS_NOTICE_READER"."CREATE_TIME" IS '创建时间';
COMMENT ON TABLE "JBOLT"."JB_SYS_NOTICE_READER" IS '通知阅读用户关系表';

-- ----------------------------
-- Table structure for JB_TODO
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_TODO";
CREATE TABLE "JBOLT"."JB_TODO" (
  "ID" NUMBER(19,0) NOT NULL,
  "TITLE" NVARCHAR2(255) NOT NULL,
  "CONTENT" NCLOB,
  "USER_ID" NUMBER(19,0) NOT NULL,
  "STATE" NUMBER(9,0) NOT NULL,
  "SPECIFIED_FINISH_TIME" DATE NOT NULL,
  "TYPE" NUMBER(9,0) NOT NULL,
  "URL" NVARCHAR2(512),
  "PRIORITY_LEVEL" NUMBER(9,0) NOT NULL,
  "REAL_FINISH_TIME" TIMESTAMP(6),
  "CANCEL_TIME" TIMESTAMP(6) NULL,
  "CREATE_USER_ID" NUMBER(19,0) NOT NULL,
  "UPDATE_USER_ID" NUMBER(19,0),
  "CREATE_TIME" TIMESTAMP(6) NOT NULL,
  "UPDATE_TIME" TIMESTAMP(6) NOT NULL,
  "SOURCE_MSG_ID" NVARCHAR2(64) NULL,
  "SOURCE_REQUEST_ID" NVARCHAR2(64) NULL,
  "SOURCE_URL" NVARCHAR2(512) NULL,
  "SEND_USER_KEY" NVARCHAR2(64) NULL,
  "RECEIVE_USER_KEY" NVARCHAR2(64) NULL,
  "SOURCE_SYS" NVARCHAR2(64) NULL,
  "IS_READED" CHAR(1) DEFAULT '0' NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_TODO"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."TITLE" IS '标题';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."CONTENT" IS '详情内容';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."USER_ID" IS '所属用户';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."STATE" IS '状态';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."SPECIFIED_FINISH_TIME" IS '规定完成时间';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."TYPE" IS '类型 链接还是内容 还是都有';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."URL" IS '链接';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."PRIORITY_LEVEL" IS '优先级';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."CREATE_USER_ID" IS '创建人ID';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."UPDATE_USER_ID" IS '更新人ID';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."REAL_FINISH_TIME" IS '完成时间';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."CANCEL_TIME" IS '取消时间';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."SOURCE_MSG_ID" IS '第三方系统消息主键';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."SOURCE_REQUEST_ID" IS '第三方系统流程主键';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."SOURCE_URL" IS '第三方url';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."SEND_USER_KEY" IS '发送人第三方系统标识';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."RECEIVE_USER_KEY" IS '接收人第三方系统标识';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."SOURCE_SYS" IS '来源系统';
COMMENT ON COLUMN "JBOLT"."JB_TODO"."IS_READED" IS '是否已读';
COMMENT ON TABLE "JBOLT"."JB_TODO" IS '待办事项';

-- ----------------------------
-- Table structure for JB_TOPNAV
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_TOPNAV";
CREATE TABLE "JBOLT"."JB_TOPNAV" (
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(40),
  "ICON" NVARCHAR2(40),
  "ENABLE" CHAR(1) DEFAULT '0' NOT NULL,
  "SORT_RANK" NUMBER(9,0)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for JB_TOPNAV_MENU
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_TOPNAV_MENU";
CREATE TABLE "JBOLT"."JB_TOPNAV_MENU" (
  "ID" NUMBER(19,0) NOT NULL,
  "TOPNAV_ID" NUMBER(19,0),
  "PERMISSION_ID" NUMBER(19,0)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for JB_USER
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_USER";
CREATE TABLE "JBOLT"."JB_USER" (
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(20) NOT NULL,
  "PASSWORD" NVARCHAR2(128) NOT NULL,
  "USERNAME" NVARCHAR2(20) NOT NULL,
  "AVATAR" NVARCHAR2(255),
  "CREATE_TIME" TIMESTAMP(6),
  "PHONE" NVARCHAR2(40),
  "EMAIL" NVARCHAR2(100),
  "SEX" NUMBER(4,0),
  "PINYIN" NVARCHAR2(255),
  "ROLES" NVARCHAR2(255),
  "CREATE_USER_ID" NUMBER(19,0),
  "IS_SYSTEM_ADMIN" CHAR(1) DEFAULT '0' NOT NULL,
  "ENABLE" CHAR(1) DEFAULT '0' NOT NULL,
  "PWD_SALT" NVARCHAR2(128),
  "LOGIN_IP" NVARCHAR2(40),
  "LOGIN_COUNTRY" NVARCHAR2(40),
  "LOGIN_PROVINCE" NVARCHAR2(40),
  "LOGIN_CITY" NVARCHAR2(40),
  "LOGIN_TIME" TIMESTAMP(6),
  "IS_REMOTE_LOGIN" CHAR(1) DEFAULT '0' NOT NULL,
  "DEPT_ID" NUMBER(19,0),
  "POSTS" NVARCHAR2(255)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_USER"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_USER"."NAME" IS '姓名';
COMMENT ON COLUMN "JBOLT"."JB_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "JBOLT"."JB_USER"."USERNAME" IS '用户名';
COMMENT ON COLUMN "JBOLT"."JB_USER"."AVATAR" IS '头像地址';
COMMENT ON COLUMN "JBOLT"."JB_USER"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_USER"."PHONE" IS '手机';
COMMENT ON COLUMN "JBOLT"."JB_USER"."EMAIL" IS '电子邮箱';
COMMENT ON COLUMN "JBOLT"."JB_USER"."SEX" IS '性别';
COMMENT ON COLUMN "JBOLT"."JB_USER"."ROLES" IS '角色集';
COMMENT ON COLUMN "JBOLT"."JB_USER"."CREATE_USER_ID" IS '创建人ID';
COMMENT ON COLUMN "JBOLT"."JB_USER"."IS_SYSTEM_ADMIN" IS '是否系统超管';
COMMENT ON COLUMN "JBOLT"."JB_USER"."ENABLE" IS '启用';
COMMENT ON COLUMN "JBOLT"."JB_USER"."PWD_SALT" IS '密码盐值';
COMMENT ON COLUMN "JBOLT"."JB_USER"."LOGIN_IP" IS '登录IP';
COMMENT ON COLUMN "JBOLT"."JB_USER"."LOGIN_COUNTRY" IS '登录国家';
COMMENT ON COLUMN "JBOLT"."JB_USER"."LOGIN_PROVINCE" IS '登录省份';
COMMENT ON COLUMN "JBOLT"."JB_USER"."LOGIN_CITY" IS '登录城市';
COMMENT ON COLUMN "JBOLT"."JB_USER"."LOGIN_TIME" IS '登录时间';
COMMENT ON COLUMN "JBOLT"."JB_USER"."IS_REMOTE_LOGIN" IS '是否异地登录';
COMMENT ON COLUMN "JBOLT"."JB_USER"."DEPT_ID" IS '部门ID';
COMMENT ON COLUMN "JBOLT"."JB_USER"."POSTS" IS '岗位IDS';
COMMENT ON TABLE "JBOLT"."JB_USER" IS '系统后台用户';

-- ----------------------------
-- Table structure for JB_USER_CONFIG
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_USER_CONFIG";
CREATE TABLE "JBOLT"."JB_USER_CONFIG" (
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(255) NOT NULL,
  "CONFIG_KEY" NVARCHAR2(255) NOT NULL,
  "CONFIG_VALUE" NVARCHAR2(255) NOT NULL,
  "USER_ID" NUMBER(19,0) NOT NULL,
  "CREATE_TIME" TIMESTAMP(6) NOT NULL,
  "UPDATE_TIME" TIMESTAMP(6) NOT NULL,
  "VALUE_TYPE" NVARCHAR2(40) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_USER_CONFIG"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_USER_CONFIG"."NAME" IS '配置名';
COMMENT ON COLUMN "JBOLT"."JB_USER_CONFIG"."CONFIG_KEY" IS '配置KEY';
COMMENT ON COLUMN "JBOLT"."JB_USER_CONFIG"."CONFIG_VALUE" IS '配置值';
COMMENT ON COLUMN "JBOLT"."JB_USER_CONFIG"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "JBOLT"."JB_USER_CONFIG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_USER_CONFIG"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "JBOLT"."JB_USER_CONFIG"."VALUE_TYPE" IS '取值类型';
COMMENT ON TABLE "JBOLT"."JB_USER_CONFIG" IS '用户系统样式自定义设置表';

-- ----------------------------
-- Table structure for JB_WECHAT_ARTICLE
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_WECHAT_ARTICLE";
CREATE TABLE "JBOLT"."JB_WECHAT_ARTICLE" (
  "ID" NUMBER(19,0) NOT NULL,
  "TITLE" NVARCHAR2(255),
  "CONTENT" NVARCHAR2(255) NOT NULL,
  "CREATE_TIME" TIMESTAMP(6) NOT NULL,
  "USER_ID" NUMBER(19,0) NOT NULL,
  "UPDATE_TIME" TIMESTAMP(6) NOT NULL,
  "UPDATE_USER_ID" NUMBER(19,0) NOT NULL,
  "BRIEF_INFO" NVARCHAR2(120) NOT NULL,
  "POSTER" NVARCHAR2(255),
  "VIEW_COUNT" NUMBER(9,0) NOT NULL,
  "MEDIA_ID" NVARCHAR2(255) NOT NULL,
  "MP_ID" NUMBER(19,0) NOT NULL,
  "URL" NVARCHAR2(255) NOT NULL,
  "TYPE" NUMBER(9,0) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_ARTICLE"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_ARTICLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_ARTICLE"."USER_ID" IS '用户 ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_ARTICLE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_ARTICLE"."UPDATE_USER_ID" IS '更新用户 ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_ARTICLE"."BRIEF_INFO" IS '文章摘要';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_ARTICLE"."VIEW_COUNT" IS '阅读数';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_ARTICLE"."MEDIA_ID" IS '微信素材 ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_ARTICLE"."MP_ID" IS '微信 ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_ARTICLE"."URL" IS '图文链接地址';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_ARTICLE"."TYPE" IS '本地图文 公众号图文素材 外部图文';
COMMENT ON TABLE "JBOLT"."JB_WECHAT_ARTICLE" IS '微信图文信息';

-- ----------------------------
-- Table structure for JB_WECHAT_AUTOREPLY
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_WECHAT_AUTOREPLY";
CREATE TABLE "JBOLT"."JB_WECHAT_AUTOREPLY" (
  "ID" NUMBER(19,0) NOT NULL,
  "MP_ID" NUMBER(19,0) NOT NULL,
  "TYPE" NUMBER(9,0) NOT NULL,
  "NAME" NVARCHAR2(40) NOT NULL,
  "REPLY_TYPE" NUMBER(9,0) NOT NULL,
  "CREATE_TIME" TIMESTAMP(6) NOT NULL,
  "USER_ID" NUMBER(19,0) NOT NULL,
  "ENABLE" CHAR(1) DEFAULT '0' NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_AUTOREPLY"."MP_ID" IS '微信 ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_AUTOREPLY"."TYPE" IS '类型 关注回复 无内容时回复 关键词回复';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_AUTOREPLY"."NAME" IS '规则名称';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_AUTOREPLY"."REPLY_TYPE" IS '回复类型 全部还是随机一条';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_AUTOREPLY"."CREATE_TIME" IS '记录创建时间';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_AUTOREPLY"."USER_ID" IS '用户 ID';
COMMENT ON TABLE "JBOLT"."JB_WECHAT_AUTOREPLY" IS '微信公众号自动回复规则';

-- ----------------------------
-- Table structure for JB_WECHAT_CONFIG
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_WECHAT_CONFIG";
CREATE TABLE "JBOLT"."JB_WECHAT_CONFIG" (
  "ID" NUMBER(19,0) NOT NULL,
  "MP_ID" NUMBER(19,0) NOT NULL,
  "CONFIG_KEY" NVARCHAR2(255) NOT NULL,
  "CONFIG_VALUE" NVARCHAR2(255),
  "NAME" NVARCHAR2(255) NOT NULL,
  "TYPE" NUMBER(9,0) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_CONFIG"."MP_ID" IS '微信 ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_CONFIG"."CONFIG_KEY" IS '配置key';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_CONFIG"."CONFIG_VALUE" IS '配置值';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_CONFIG"."NAME" IS '配置项名称';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_CONFIG"."TYPE" IS '配置类型';
COMMENT ON TABLE "JBOLT"."JB_WECHAT_CONFIG" IS '微信公众号配置表';

-- ----------------------------
-- Table structure for JB_WECHAT_KEYWORDS
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_WECHAT_KEYWORDS";
CREATE TABLE "JBOLT"."JB_WECHAT_KEYWORDS" (
  "ID" NUMBER(19,0) NOT NULL,
  "MP_ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(40) NOT NULL,
  "TYPE" NUMBER(9,0) NOT NULL,
  "AUTO_REPLY_ID" NUMBER(19,0) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_KEYWORDS"."MP_ID" IS '微信 ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_KEYWORDS"."NAME" IS '关键词';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_KEYWORDS"."TYPE" IS '模糊 全匹配';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_KEYWORDS"."AUTO_REPLY_ID" IS '回复规则ID';
COMMENT ON TABLE "JBOLT"."JB_WECHAT_KEYWORDS" IS '微信关键词回复中的关键词定义';

-- ----------------------------
-- Table structure for JB_WECHAT_MEDIA
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_WECHAT_MEDIA";
CREATE TABLE "JBOLT"."JB_WECHAT_MEDIA" (
  "ID" NUMBER(19,0) NOT NULL,
  "TITLE" NVARCHAR2(500) NOT NULL,
  "DIGEST" NCLOB,
  "TYPE" NVARCHAR2(255) NOT NULL,
  "MP_ID" NUMBER(19,0) NOT NULL,
  "MEDIA_ID" NVARCHAR2(255) NOT NULL,
  "THUMB_MEDIA_ID" NVARCHAR2(255),
  "CONTENT_SOURCE_URL" NVARCHAR2(255),
  "URL" NVARCHAR2(255),
  "AUTHOR" NVARCHAR2(255),
  "UPDATE_TIME" TIMESTAMP(6) NOT NULL,
  "SERVER_URL" NVARCHAR2(255)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MEDIA"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MEDIA"."TITLE" IS '标题';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MEDIA"."DIGEST" IS '描述';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MEDIA"."TYPE" IS '类型 image video voice news';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MEDIA"."MP_ID" IS '微信 ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MEDIA"."MEDIA_ID" IS '微信素材ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MEDIA"."THUMB_MEDIA_ID" IS '封面图ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MEDIA"."CONTENT_SOURCE_URL" IS '原文地址';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MEDIA"."URL" IS '访问地址';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MEDIA"."AUTHOR" IS '图文作者';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MEDIA"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MEDIA"."SERVER_URL" IS '存服务器URL';
COMMENT ON TABLE "JBOLT"."JB_WECHAT_MEDIA" IS '微信公众平台素材库同步管理';

-- ----------------------------
-- Table structure for JB_WECHAT_MENU
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_WECHAT_MENU";
CREATE TABLE "JBOLT"."JB_WECHAT_MENU" (
  "ID" NUMBER(19,0) NOT NULL,
  "MP_ID" NUMBER(19,0) NOT NULL,
  "TYPE" NVARCHAR2(40) NOT NULL,
  "NAME" NVARCHAR2(40) NOT NULL,
  "PID" NUMBER(19,0) NOT NULL,
  "SORT_RANK" NUMBER(9,0) NOT NULL,
  "VALUE" NVARCHAR2(255),
  "APP_ID" NVARCHAR2(255),
  "PAGE_PATH" NVARCHAR2(255)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MENU"."MP_ID" IS '微信 ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MENU"."SORT_RANK" IS '排序';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MENU"."APP_ID" IS '微信小程序APPID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MENU"."PAGE_PATH" IS '微信小程序页面地址';
COMMENT ON TABLE "JBOLT"."JB_WECHAT_MENU" IS '微信菜单';

-- ----------------------------
-- Table structure for JB_WECHAT_MPINFO
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_WECHAT_MPINFO";
CREATE TABLE "JBOLT"."JB_WECHAT_MPINFO" (
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(255) NOT NULL,
  "LOGO" NVARCHAR2(255),
  "CREATE_TIME" TIMESTAMP(6) NOT NULL,
  "USER_ID" NUMBER(19,0) NOT NULL,
  "ENABLE" CHAR(1) DEFAULT '0' NOT NULL,
  "UPDATE_TIME" TIMESTAMP(6) NOT NULL,
  "UPDATE_USER_ID" NUMBER(19,0) NOT NULL,
  "BRIEF_INFO" NVARCHAR2(255),
  "REMARK" NVARCHAR2(255),
  "TYPE" NUMBER(9,0) NOT NULL,
  "IS_AUTHENTICATED" CHAR(1) DEFAULT '0' NOT NULL,
  "SUBJECT_TYPE" NUMBER(9,0) NOT NULL,
  "WECHAT_ID" NVARCHAR2(255),
  "QRCODE" NVARCHAR2(255),
  "LINK_APP_ID" NUMBER(19,0)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."ID" IS '主键';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."NAME" IS '平台名称';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."LOGO" IS '头像LOGO';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."ENABLE" IS '是否启用';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."UPDATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."UPDATE_USER_ID" IS '更新人ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."BRIEF_INFO" IS '简介';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."REMARK" IS '备注';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."TYPE" IS '类型 订阅号、服务号、小程序、企业号';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."IS_AUTHENTICATED" IS '是否已认证';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."SUBJECT_TYPE" IS '申请认证主体的类型 个人还是企业';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."WECHAT_ID" IS '微信号';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."QRCODE" IS '二维码';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_MPINFO"."LINK_APP_ID" IS '关联应用ID';
COMMENT ON TABLE "JBOLT"."JB_WECHAT_MPINFO" IS '微信公众号与小程序';

-- ----------------------------
-- Table structure for JB_WECHAT_REPLY_CONTENT
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_WECHAT_REPLY_CONTENT";
CREATE TABLE "JBOLT"."JB_WECHAT_REPLY_CONTENT" (
  "ID" NUMBER(19,0) NOT NULL,
  "TYPE" NVARCHAR2(40) NOT NULL,
  "TITLE" NVARCHAR2(64),
  "POSTER" NVARCHAR2(255),
  "URL" NVARCHAR2(255),
  "AUTO_REPLY_ID" NUMBER(19,0) NOT NULL,
  "CREATE_TIME" TIMESTAMP(6) NOT NULL,
  "USER_ID" NUMBER(19,0),
  "MEDIA_ID" NVARCHAR2(255),
  "MP_ID" NUMBER(19,0) NOT NULL,
  "SORT_RANK" NUMBER(9,0) NOT NULL,
  "ENABLE" CHAR(1 CHAR) DEFAULT 0 NOT NULL,
  "CONTENT" NVARCHAR2(1000) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_REPLY_CONTENT"."TYPE" IS '类型 图文 文字 图片 音频 视频';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_REPLY_CONTENT"."AUTO_REPLY_ID" IS '回复规则ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_REPLY_CONTENT"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_REPLY_CONTENT"."USER_ID" IS '用户 ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_REPLY_CONTENT"."MEDIA_ID" IS '关联数据';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_REPLY_CONTENT"."MP_ID" IS '微信 ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_REPLY_CONTENT"."SORT_RANK" IS '排序';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_REPLY_CONTENT"."ENABLE" IS '启用';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_REPLY_CONTENT"."CONTENT" IS '回复内容';
COMMENT ON TABLE "JBOLT"."JB_WECHAT_REPLY_CONTENT" IS '自动回复内容';

-- ----------------------------
-- Table structure for JB_WECHAT_USER
-- ----------------------------
--- DROP TABLE "JBOLT"."JB_WECHAT_USER";
CREATE TABLE "JBOLT"."JB_WECHAT_USER" (
  "ID" NUMBER(19,0) NOT NULL,
  "NICKNAME" NVARCHAR2(255) NOT NULL,
  "OPEN_ID" NVARCHAR2(255) NOT NULL,
  "UNION_ID" NVARCHAR2(255),
  "SEX" NUMBER(9,0),
  "LANGUAGE" NVARCHAR2(255),
  "SUBSCIBE" CHAR(1) DEFAULT '0' NOT NULL,
  "COUNTRY" NVARCHAR2(255),
  "PROVINCE" NVARCHAR2(255),
  "CITY" NVARCHAR2(255),
  "HEAD_IMG_URL" NVARCHAR2(255),
  "SUBSCRIBE_TIME" TIMESTAMP(6),
  "REMARK" NVARCHAR2(255),
  "GROUP_ID" NUMBER(19,0),
  "TAG_IDS" NVARCHAR2(255),
  "SUBSCRIBE_SCENE" NVARCHAR2(255),
  "QR_SCENE" NUMBER(9,0),
  "QR_SCENE_STR" NVARCHAR2(255),
  "REALNAME" NVARCHAR2(255),
  "PHONE" NVARCHAR2(255),
  "CHECK_CODE" NVARCHAR2(255),
  "IS_CHECKED" CHAR(1) DEFAULT '0' NOT NULL,
  "SOURCE" NUMBER(9,0),
  "SESSION_KEY" NVARCHAR2(255),
  "ENABLE" CHAR(1) DEFAULT '0' NOT NULL,
  "CREATE_TIME" TIMESTAMP(6),
  "CHECKED_TIME" TIMESTAMP(6),
  "MP_ID" NUMBER(19,0),
  "WEIXIN" NVARCHAR2(255),
  "UPDATE_TIME" TIMESTAMP(6),
  "LAST_LOGIN_TIME" TIMESTAMP(6) DEFAULT NULL,
  "FIRST_AUTH_TIME" TIMESTAMP(6),
  "LAST_AUTH_TIME" TIMESTAMP(6),
  "FIRST_LOGIN_TIME" TIMESTAMP(6),
  "BIND_USER" NVARCHAR2(255),
  "PHONE_COUNTRY_CODE" NVARCHAR2(40)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."ID" IS '用户ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."NICKNAME" IS '用户昵称';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."OPEN_ID" IS 'openId';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."UNION_ID" IS 'unionID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."SEX" IS '性别 1男 2女 0 未知';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."LANGUAGE" IS '语言';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."SUBSCIBE" IS '是否已关注';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."COUNTRY" IS '国家';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."PROVINCE" IS '省';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."CITY" IS '城市';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."HEAD_IMG_URL" IS '头像';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."SUBSCRIBE_TIME" IS '关注时间';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."REMARK" IS '备注';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."GROUP_ID" IS '分组';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."TAG_IDS" IS '标签';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."SUBSCRIBE_SCENE" IS '关注渠道';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."QR_SCENE" IS '二维码场景-开发者自定义';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."QR_SCENE_STR" IS '二维码扫码场景描述-开发者自定义';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."REALNAME" IS '真实姓名';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."PHONE" IS '手机号';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."CHECK_CODE" IS '手机验证码';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."IS_CHECKED" IS '是否已验证';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."SOURCE" IS '来源 小程序还是公众平台';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."SESSION_KEY" IS '小程序登录SessionKey';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."ENABLE" IS '禁用访问';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."CHECKED_TIME" IS '验证绑定手机号时间';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."MP_ID" IS '所属公众平台ID';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."WEIXIN" IS '微信号';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."LAST_LOGIN_TIME" IS '最后登录时间';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."FIRST_AUTH_TIME" IS '首次授权时间';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."LAST_AUTH_TIME" IS '最后一次授权时间';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."FIRST_LOGIN_TIME" IS '首次登录时间';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."BIND_USER" IS '绑定其他用户信息';
COMMENT ON COLUMN "JBOLT"."JB_WECHAT_USER"."PHONE_COUNTRY_CODE" IS '手机号国家代码';
COMMENT ON TABLE "JBOLT"."JB_WECHAT_USER" IS '微信用户信息_模板表';
-- ----------------------------
-- Primary Key structure for table JB_APPLICATION
-- ----------------------------
ALTER TABLE "JBOLT"."JB_APPLICATION" ADD CONSTRAINT "SYS_C007348" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_APPLICATION
-- ----------------------------
ALTER TABLE "JBOLT"."JB_APPLICATION" ADD CONSTRAINT "SYS_C006997" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_APPLICATION" ADD CONSTRAINT "SYS_C006998" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_APPLICATION" ADD CONSTRAINT "SYS_C006999" CHECK ("APP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_APPLICATION" ADD CONSTRAINT "SYS_C007000" CHECK ("APP_SECRET" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_APPLICATION" ADD CONSTRAINT "SYS_C007001" CHECK ("ENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_APPLICATION" ADD CONSTRAINT "SYS_C007002" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_APPLICATION" ADD CONSTRAINT "SYS_C007003" CHECK ("UPDATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_APPLICATION" ADD CONSTRAINT "SYS_C007004" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_APPLICATION" ADD CONSTRAINT "SYS_C007005" CHECK ("UPDATE_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_APPLICATION" ADD CONSTRAINT "SYS_C007006" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_APPLICATION" ADD CONSTRAINT "SYS_C007007" CHECK ("NEED_CHECK_SIGN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_APPLICATION" ADD CONSTRAINT "SYS_C0017007" CHECK ("IS_INNER" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_DEPT
-- ----------------------------
ALTER TABLE "JBOLT"."JB_DEPT" ADD CONSTRAINT "SYS_C007352" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_DEPT
-- ----------------------------
ALTER TABLE "JBOLT"."JB_DEPT" ADD CONSTRAINT "SYS_C007240" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_DEPT" ADD CONSTRAINT "SYS_C007241" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_DEPT" ADD CONSTRAINT "SYS_C007242" CHECK ("FULL_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_DEPT" ADD CONSTRAINT "SYS_C007243" CHECK ("ENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_DICTIONARY
-- ----------------------------
ALTER TABLE "JBOLT"."JB_DICTIONARY" ADD CONSTRAINT "SYS_C007353" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_DICTIONARY
-- ----------------------------
ALTER TABLE "JBOLT"."JB_DICTIONARY" ADD CONSTRAINT "SYS_C007016" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_DICTIONARY" ADD CONSTRAINT "SYS_C007017" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_DICTIONARY" ADD CONSTRAINT "SYS_C007018" CHECK ("TYPE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_DICTIONARY" ADD CONSTRAINT "SYS_C007019" CHECK ("PID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_DICTIONARY" ADD CONSTRAINT "SYS_C007020" CHECK ("SORT_RANK" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_DICTIONARY_TYPE
-- ----------------------------
ALTER TABLE "JBOLT"."JB_DICTIONARY_TYPE" ADD CONSTRAINT "SYS_C007354" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_DICTIONARY_TYPE
-- ----------------------------
ALTER TABLE "JBOLT"."JB_DICTIONARY_TYPE" ADD CONSTRAINT "SYS_C007021" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_DICTIONARY_TYPE" ADD CONSTRAINT "SYS_C007022" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_DICTIONARY_TYPE" ADD CONSTRAINT "SYS_C007023" CHECK ("MODE_LEVEL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_DICTIONARY_TYPE" ADD CONSTRAINT "SYS_C007024" CHECK ("TYPE_KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_GLOBAL_CONFIG
-- ----------------------------
ALTER TABLE "JBOLT"."JB_GLOBAL_CONFIG" ADD CONSTRAINT "SYS_C007356" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_GLOBAL_CONFIG
-- ----------------------------
ALTER TABLE "JBOLT"."JB_GLOBAL_CONFIG" ADD CONSTRAINT "SYS_C007029" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_GLOBAL_CONFIG" ADD CONSTRAINT "SYS_C007030" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_GLOBAL_CONFIG" ADD CONSTRAINT "SYS_C007031" CHECK ("CONFIG_KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_GLOBAL_CONFIG" ADD CONSTRAINT "SYS_C007032" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_GLOBAL_CONFIG" ADD CONSTRAINT "SYS_C007033" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_GLOBAL_CONFIG" ADD CONSTRAINT "SYS_C007034" CHECK ("UPDATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_GLOBAL_CONFIG" ADD CONSTRAINT "SYS_C007035" CHECK ("UPDATE_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_GLOBAL_CONFIG_TYPE
-- ----------------------------
ALTER TABLE "JBOLT"."JB_GLOBAL_CONFIG_TYPE" ADD CONSTRAINT "SYS_C007357" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_GLOBAL_CONFIG_TYPE
-- ----------------------------
ALTER TABLE "JBOLT"."JB_GLOBAL_CONFIG_TYPE" ADD CONSTRAINT "SYS_C007036" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_GLOBAL_CONFIG_TYPE" ADD CONSTRAINT "SYS_C007037" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_GLOBAL_CONFIG_TYPE" ADD CONSTRAINT "SYS_C007038" CHECK ("TYPE_KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_GLOBAL_CONFIG_TYPE" ADD CONSTRAINT "SYS_C007039" CHECK ("SORT_RANK" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_JBOLT_FILE
-- ----------------------------
ALTER TABLE "JBOLT"."JB_JBOLT_FILE" ADD CONSTRAINT "SYS_C007366" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_JBOLT_FILE
-- ----------------------------
ALTER TABLE "JBOLT"."JB_JBOLT_FILE" ADD CONSTRAINT "SYS_C007077" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_JBOLT_FILE" ADD CONSTRAINT "SYS_C007078" CHECK ("LOCAL_PATH" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_JBOLT_FILE" ADD CONSTRAINT "SYS_C007079" CHECK ("LOCAL_URL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_JBOLT_FILE" ADD CONSTRAINT "SYS_C007080" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_JBOLT_FILE" ADD CONSTRAINT "SYS_C007082" CHECK ("FILE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_JBOLT_FILE" ADD CONSTRAINT "SYS_C007083" CHECK ("FILE_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_JBOLT_FILE" ADD CONSTRAINT "SYS_C007084" CHECK ("FILE_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_LOGIN_LOG
-- ----------------------------
ALTER TABLE "JBOLT"."JB_LOGIN_LOG" ADD CONSTRAINT "SYS_C007369" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_LOGIN_LOG
-- ----------------------------
ALTER TABLE "JBOLT"."JB_LOGIN_LOG" ADD CONSTRAINT "SYS_C007094" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_LOGIN_LOG" ADD CONSTRAINT "SYS_C007095" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_LOGIN_LOG" ADD CONSTRAINT "SYS_C007096" CHECK ("LOGIN_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_ONLINE_USER
-- ----------------------------
ALTER TABLE "JBOLT"."JB_ONLINE_USER" ADD CONSTRAINT "SYS_C007371" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_ONLINE_USER
-- ----------------------------
ALTER TABLE "JBOLT"."JB_ONLINE_USER" ADD CONSTRAINT "SYS_C007102" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_ONLINE_USER" ADD CONSTRAINT "SYS_C007103" CHECK ("SESSION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_ONLINE_USER" ADD CONSTRAINT "SYS_C007104" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_ONLINE_USER" ADD CONSTRAINT "SYS_C007105" CHECK ("LOGIN_LOG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_ONLINE_USER" ADD CONSTRAINT "SYS_C007106" CHECK ("LOGIN_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_ONLINE_USER" ADD CONSTRAINT "SYS_C007107" CHECK ("UPDATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_ONLINE_USER" ADD CONSTRAINT "SYS_C007108" CHECK ("EXPIRATION_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_ONLINE_USER" ADD CONSTRAINT "SYS_C007109" CHECK ("SCREEN_LOCKED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_ONLINE_USER" ADD CONSTRAINT "SYS_C007110" CHECK ("ONLINE_STATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_PERMISSION
-- ----------------------------
ALTER TABLE "JBOLT"."JB_PERMISSION" ADD CONSTRAINT "SYS_C007375" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_PERMISSION
-- ----------------------------
ALTER TABLE "JBOLT"."JB_PERMISSION" ADD CONSTRAINT "SYS_C007145" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_PERMISSION" ADD CONSTRAINT "SYS_C007146" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_PERMISSION" ADD CONSTRAINT "SYS_C007147" CHECK ("PID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_PERMISSION" ADD CONSTRAINT "SYS_C007148" CHECK ("SORT_RANK" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_PERMISSION" ADD CONSTRAINT "SYS_C007149" CHECK ("PERMISSION_LEVEL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_PERMISSION" ADD CONSTRAINT "SYS_C007150" CHECK ("PERMISSION_KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_PERMISSION" ADD CONSTRAINT "SYS_C007151" CHECK ("IS_MENU" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_PERMISSION" ADD CONSTRAINT "SYS_C007152" CHECK ("IS_SYSTEM_ADMIN_DEFAULT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_POST
-- ----------------------------
ALTER TABLE "JBOLT"."JB_POST" ADD CONSTRAINT "SYS_C007376" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_POST
-- ----------------------------
ALTER TABLE "JBOLT"."JB_POST" ADD CONSTRAINT "SYS_C007244" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_POST" ADD CONSTRAINT "SYS_C007245" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_POST" ADD CONSTRAINT "SYS_C007246" CHECK ("ENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_PRIVATE_MESSAGE
-- ----------------------------
ALTER TABLE "JBOLT"."JB_PRIVATE_MESSAGE" ADD CONSTRAINT "SYS_C007344" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_PRIVATE_MESSAGE
-- ----------------------------
ALTER TABLE "JBOLT"."JB_PRIVATE_MESSAGE" ADD CONSTRAINT "SYS_C007327" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_PRIVATE_MESSAGE" ADD CONSTRAINT "SYS_C007329" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_PRIVATE_MESSAGE" ADD CONSTRAINT "SYS_C007331" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_PRIVATE_MESSAGE" ADD CONSTRAINT "SYS_C007332" CHECK ("FROM_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_PRIVATE_MESSAGE" ADD CONSTRAINT "SYS_C007333" CHECK ("TO_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_REMOTE_LOGIN_LOG
-- ----------------------------
ALTER TABLE "JBOLT"."JB_REMOTE_LOGIN_LOG" ADD CONSTRAINT "SYS_C007377" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_REMOTE_LOGIN_LOG
-- ----------------------------
ALTER TABLE "JBOLT"."JB_REMOTE_LOGIN_LOG" ADD CONSTRAINT "SYS_C007153" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_ROLE
-- ----------------------------
ALTER TABLE "JBOLT"."JB_ROLE" ADD CONSTRAINT "SYS_C007378" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_ROLE
-- ----------------------------
ALTER TABLE "JBOLT"."JB_ROLE" ADD CONSTRAINT "SYS_C007154" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_ROLE" ADD CONSTRAINT "SYS_C007155" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_ROLE" ADD CONSTRAINT "SYS_C007156" CHECK ("PID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_ROLE_PERMISSION
-- ----------------------------
ALTER TABLE "JBOLT"."JB_ROLE_PERMISSION" ADD CONSTRAINT "SYS_C007379" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_ROLE_PERMISSION
-- ----------------------------
ALTER TABLE "JBOLT"."JB_ROLE_PERMISSION" ADD CONSTRAINT "SYS_C007157" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_ROLE_PERMISSION" ADD CONSTRAINT "SYS_C007158" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_ROLE_PERMISSION" ADD CONSTRAINT "SYS_C007159" CHECK ("PERMISSION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_SYSTEM_LOG
-- ----------------------------
ALTER TABLE "JBOLT"."JB_SYSTEM_LOG" ADD CONSTRAINT "SYS_C007390" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_SYSTEM_LOG
-- ----------------------------
ALTER TABLE "JBOLT"."JB_SYSTEM_LOG" ADD CONSTRAINT "SYS_C007226" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_SYS_NOTICE
-- ----------------------------
ALTER TABLE "JBOLT"."JB_SYS_NOTICE" ADD CONSTRAINT "SYS_C007347" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_SYS_NOTICE
-- ----------------------------
ALTER TABLE "JBOLT"."JB_SYS_NOTICE" ADD CONSTRAINT "SYS_C007319" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_SYS_NOTICE" ADD CONSTRAINT "SYS_C007320" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_SYS_NOTICE" ADD CONSTRAINT "SYS_C007321" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_SYS_NOTICE" ADD CONSTRAINT "SYS_C007322" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_SYS_NOTICE" ADD CONSTRAINT "SYS_C007323" CHECK ("PRIORITY_LEVEL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_SYS_NOTICE" ADD CONSTRAINT "SYS_C007324" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_SYS_NOTICE_READER
-- ----------------------------
ALTER TABLE "JBOLT"."JB_SYS_NOTICE_READER" ADD CONSTRAINT "SYS_C007345" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_SYS_NOTICE_READER
-- ----------------------------
ALTER TABLE "JBOLT"."JB_SYS_NOTICE_READER" ADD CONSTRAINT "SYS_C007325" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_SYS_NOTICE_READER" ADD CONSTRAINT "SYS_C007326" CHECK ("SYS_NOTICE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_SYS_NOTICE_READER" ADD CONSTRAINT "SYS_C007328" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_SYS_NOTICE_READER" ADD CONSTRAINT "SYS_C007330" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_TODO
-- ----------------------------
ALTER TABLE "JBOLT"."JB_TODO" ADD CONSTRAINT "SYS_C007346" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_TODO
-- ----------------------------
ALTER TABLE "JBOLT"."JB_TODO" ADD CONSTRAINT "SYS_C007334" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_TODO" ADD CONSTRAINT "SYS_C007335" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_TODO" ADD CONSTRAINT "SYS_C007336" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_TODO" ADD CONSTRAINT "SYS_C007337" CHECK ("STATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_TODO" ADD CONSTRAINT "SYS_C007338" CHECK ("SPECIFIED_FINISH_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_TODO" ADD CONSTRAINT "SYS_C007339" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_TODO" ADD CONSTRAINT "SYS_C007340" CHECK ("PRIORITY_LEVEL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_TODO" ADD CONSTRAINT "SYS_C007341" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_TODO" ADD CONSTRAINT "SYS_C007342" CHECK ("UPDATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_TODO" ADD CONSTRAINT "SYS_C007343" CHECK ("CREATE_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_TOPNAV
-- ----------------------------
ALTER TABLE "JBOLT"."JB_TOPNAV" ADD CONSTRAINT "SYS_C007391" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_TOPNAV
-- ----------------------------
ALTER TABLE "JBOLT"."JB_TOPNAV" ADD CONSTRAINT "SYS_C007227" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_TOPNAV_MENU
-- ----------------------------
ALTER TABLE "JBOLT"."JB_TOPNAV_MENU" ADD CONSTRAINT "SYS_C007392" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_TOPNAV_MENU
-- ----------------------------
ALTER TABLE "JBOLT"."JB_TOPNAV_MENU" ADD CONSTRAINT "SYS_C007228" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_USER
-- ----------------------------
ALTER TABLE "JBOLT"."JB_USER" ADD CONSTRAINT "SYS_C007394" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_USER
-- ----------------------------
ALTER TABLE "JBOLT"."JB_USER" ADD CONSTRAINT "SYS_C007234" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_USER" ADD CONSTRAINT "SYS_C007235" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_USER" ADD CONSTRAINT "SYS_C007236" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_USER" ADD CONSTRAINT "SYS_C007237" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_USER" ADD CONSTRAINT "SYS_C007238" CHECK ("IS_SYSTEM_ADMIN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_USER" ADD CONSTRAINT "SYS_C007239" CHECK ("ENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_USER_CONFIG
-- ----------------------------
ALTER TABLE "JBOLT"."JB_USER_CONFIG" ADD CONSTRAINT "SYS_C007395" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_USER_CONFIG
-- ----------------------------
ALTER TABLE "JBOLT"."JB_USER_CONFIG" ADD CONSTRAINT "SYS_C007247" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_USER_CONFIG" ADD CONSTRAINT "SYS_C007248" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_USER_CONFIG" ADD CONSTRAINT "SYS_C007249" CHECK ("CONFIG_KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_USER_CONFIG" ADD CONSTRAINT "SYS_C007250" CHECK ("CONFIG_VALUE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_USER_CONFIG" ADD CONSTRAINT "SYS_C007251" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_USER_CONFIG" ADD CONSTRAINT "SYS_C007252" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_USER_CONFIG" ADD CONSTRAINT "SYS_C007253" CHECK ("UPDATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_USER_CONFIG" ADD CONSTRAINT "SYS_C007254" CHECK ("VALUE_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_WECHAT_ARTICLE
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_ARTICLE" ADD CONSTRAINT "SYS_C007396" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_WECHAT_ARTICLE
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_ARTICLE" ADD CONSTRAINT "SYS_C007255" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_ARTICLE" ADD CONSTRAINT "SYS_C007256" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_ARTICLE" ADD CONSTRAINT "SYS_C007257" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_ARTICLE" ADD CONSTRAINT "SYS_C007258" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_ARTICLE" ADD CONSTRAINT "SYS_C007259" CHECK ("UPDATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_ARTICLE" ADD CONSTRAINT "SYS_C007260" CHECK ("UPDATE_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_ARTICLE" ADD CONSTRAINT "SYS_C007261" CHECK ("BRIEF_INFO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_ARTICLE" ADD CONSTRAINT "SYS_C007262" CHECK ("VIEW_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_ARTICLE" ADD CONSTRAINT "SYS_C007263" CHECK ("MEDIA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_ARTICLE" ADD CONSTRAINT "SYS_C007264" CHECK ("MP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_ARTICLE" ADD CONSTRAINT "SYS_C007265" CHECK ("URL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_ARTICLE" ADD CONSTRAINT "SYS_C007266" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_WECHAT_AUTOREPLY
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_AUTOREPLY" ADD CONSTRAINT "SYS_C007397" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_WECHAT_AUTOREPLY
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_AUTOREPLY" ADD CONSTRAINT "SYS_C007267" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_AUTOREPLY" ADD CONSTRAINT "SYS_C007268" CHECK ("MP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_AUTOREPLY" ADD CONSTRAINT "SYS_C007269" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_AUTOREPLY" ADD CONSTRAINT "SYS_C007270" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_AUTOREPLY" ADD CONSTRAINT "SYS_C007271" CHECK ("REPLY_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_AUTOREPLY" ADD CONSTRAINT "SYS_C007272" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_AUTOREPLY" ADD CONSTRAINT "SYS_C007273" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_AUTOREPLY" ADD CONSTRAINT "SYS_C007274" CHECK ("ENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_WECHAT_CONFIG
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_CONFIG" ADD CONSTRAINT "SYS_C007398" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_WECHAT_CONFIG
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_CONFIG" ADD CONSTRAINT "SYS_C007275" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_CONFIG" ADD CONSTRAINT "SYS_C007276" CHECK ("MP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_CONFIG" ADD CONSTRAINT "SYS_C007277" CHECK ("CONFIG_KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_CONFIG" ADD CONSTRAINT "SYS_C007278" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_CONFIG" ADD CONSTRAINT "SYS_C007279" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_WECHAT_KEYWORDS
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_KEYWORDS" ADD CONSTRAINT "SYS_C007399" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_WECHAT_KEYWORDS
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_KEYWORDS" ADD CONSTRAINT "SYS_C007280" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_KEYWORDS" ADD CONSTRAINT "SYS_C007281" CHECK ("MP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_KEYWORDS" ADD CONSTRAINT "SYS_C007282" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_KEYWORDS" ADD CONSTRAINT "SYS_C007283" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_KEYWORDS" ADD CONSTRAINT "SYS_C007284" CHECK ("AUTO_REPLY_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_WECHAT_MEDIA
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_MEDIA" ADD CONSTRAINT "SYS_C007400" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_WECHAT_MEDIA
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_MEDIA" ADD CONSTRAINT "SYS_C007285" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MEDIA" ADD CONSTRAINT "SYS_C007286" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MEDIA" ADD CONSTRAINT "SYS_C007287" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MEDIA" ADD CONSTRAINT "SYS_C007288" CHECK ("MP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MEDIA" ADD CONSTRAINT "SYS_C007289" CHECK ("MEDIA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MEDIA" ADD CONSTRAINT "SYS_C007290" CHECK ("UPDATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_WECHAT_MENU
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_MENU" ADD CONSTRAINT "SYS_C007401" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_WECHAT_MENU
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_MENU" ADD CONSTRAINT "SYS_C007291" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MENU" ADD CONSTRAINT "SYS_C007292" CHECK ("MP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MENU" ADD CONSTRAINT "SYS_C007293" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MENU" ADD CONSTRAINT "SYS_C007294" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MENU" ADD CONSTRAINT "SYS_C007295" CHECK ("PID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MENU" ADD CONSTRAINT "SYS_C007296" CHECK ("SORT_RANK" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_WECHAT_MPINFO
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_MPINFO" ADD CONSTRAINT "SYS_C007402" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_WECHAT_MPINFO
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_MPINFO" ADD CONSTRAINT "SYS_C007297" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MPINFO" ADD CONSTRAINT "SYS_C007298" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MPINFO" ADD CONSTRAINT "SYS_C007299" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MPINFO" ADD CONSTRAINT "SYS_C007300" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MPINFO" ADD CONSTRAINT "SYS_C007301" CHECK ("ENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MPINFO" ADD CONSTRAINT "SYS_C007302" CHECK ("UPDATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MPINFO" ADD CONSTRAINT "SYS_C007303" CHECK ("UPDATE_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MPINFO" ADD CONSTRAINT "SYS_C007304" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MPINFO" ADD CONSTRAINT "SYS_C007305" CHECK ("IS_AUTHENTICATED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_MPINFO" ADD CONSTRAINT "SYS_C007306" CHECK ("SUBJECT_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_WECHAT_REPLY_CONTENT
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_REPLY_CONTENT" ADD CONSTRAINT "SYS_C007403" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_WECHAT_REPLY_CONTENT
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_REPLY_CONTENT" ADD CONSTRAINT "SYS_C007307" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_REPLY_CONTENT" ADD CONSTRAINT "SYS_C007308" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_REPLY_CONTENT" ADD CONSTRAINT "SYS_C007309" CHECK ("AUTO_REPLY_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_REPLY_CONTENT" ADD CONSTRAINT "SYS_C007310" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_REPLY_CONTENT" ADD CONSTRAINT "SYS_C007311" CHECK ("MP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_REPLY_CONTENT" ADD CONSTRAINT "SYS_C007312" CHECK ("SORT_RANK" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_REPLY_CONTENT" ADD CONSTRAINT "SYS_C007313" CHECK ("ENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_REPLY_CONTENT" ADD CONSTRAINT "SYS_C007314" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_WECHAT_USER
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_USER" ADD CONSTRAINT "SYS_C007404" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_WECHAT_USER
-- ----------------------------
ALTER TABLE "JBOLT"."JB_WECHAT_USER" ADD CONSTRAINT "SYS_C007315" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_USER" ADD CONSTRAINT "SYS_C007316" CHECK ("NICKNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_USER" ADD CONSTRAINT "SYS_C007317" CHECK ("OPEN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_WECHAT_USER" ADD CONSTRAINT "SYS_C007318" CHECK ("SUBSCIBE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;


-- ----------------------------
-- Table structure for JB_QINIU
-- ----------------------------
--DROP TABLE "JBOLT"."JB_QINIU";
CREATE TABLE "JBOLT"."JB_QINIU" (
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(255) NOT NULL,
  "SN" NVARCHAR2(40) NOT NULL,
  "AK" NVARCHAR2(64) NOT NULL,
  "SK" NVARCHAR2(64) NOT NULL,
  "TYPE" NUMBER(11,0) NOT NULL,
  "BUCKET_COUNT" NUMBER(11,0) NOT NULL,
  "IS_DEFAULT" NCHAR(1) NOT NULL,
  "ENABLE" NCHAR(1) NOT NULL,
  "REMARK" NVARCHAR2(255),
  "CREATE_TIME" DATE NOT NULL,
  "UPDATE_TIME" DATE NOT NULL,
  "CREATE_USER_ID" NUMBER(19,0) NOT NULL,
  "UPDATE_USER_ID" NUMBER(19,0) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_QINIU"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_QINIU"."NAME" IS '账号';
COMMENT ON COLUMN "JBOLT"."JB_QINIU"."SN" IS '编号SN';
COMMENT ON COLUMN "JBOLT"."JB_QINIU"."AK" IS 'AK';
COMMENT ON COLUMN "JBOLT"."JB_QINIU"."SK" IS 'SK';
COMMENT ON COLUMN "JBOLT"."JB_QINIU"."TYPE" IS '账号类型';
COMMENT ON COLUMN "JBOLT"."JB_QINIU"."BUCKET_COUNT" IS '空间个数';
COMMENT ON COLUMN "JBOLT"."JB_QINIU"."IS_DEFAULT" IS '是否默认';
COMMENT ON COLUMN "JBOLT"."JB_QINIU"."ENABLE" IS '是否启用';
COMMENT ON COLUMN "JBOLT"."JB_QINIU"."REMARK" IS '备注';
COMMENT ON COLUMN "JBOLT"."JB_QINIU"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_QINIU"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "JBOLT"."JB_QINIU"."CREATE_USER_ID" IS '创建人';
COMMENT ON COLUMN "JBOLT"."JB_QINIU"."UPDATE_USER_ID" IS '更新人';
COMMENT ON TABLE "JBOLT"."JB_QINIU" IS '七牛账号表';

-- ----------------------------
-- Table structure for JB_QINIU_BUCKET
-- ----------------------------
--DROP TABLE "JBOLT"."JB_QINIU_BUCKET";
CREATE TABLE "JBOLT"."JB_QINIU_BUCKET" (
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" NVARCHAR2(64) NOT NULL,
  "SN" NVARCHAR2(40) NOT NULL,
  "QINIU_ID" NUMBER(19,0) NOT NULL,
  "DOMAIN_URL" NVARCHAR2(255),
  "CALLBACK_URL" NVARCHAR2(255),
  "CALLBACK_BODY" NVARCHAR2(255),
  "CALLBACK_BODY_TYPE" NVARCHAR2(64),
  "EXPIRES" NUMBER(11,0),
  "IS_DEFAULT" NCHAR(1) NOT NULL,
  "ENABLE" NCHAR(1) NOT NULL,
  "REMARK" NVARCHAR2(255),
  "CREATE_USER_ID" NUMBER(19,0) NOT NULL,
  "CREATE_TIME" DATE NOT NULL,
  "UPDATE_USER_ID" NUMBER(19,0) NOT NULL,
  "UPDATE_TIME" DATE,
  "REGION" NVARCHAR2(20) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."NAME" IS 'bucket名称';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."SN" IS '编码';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."QINIU_ID" IS '所属七牛账号';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."DOMAIN_URL" IS '绑定域名';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."CALLBACK_URL" IS '回调地址';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."CALLBACK_BODY" IS '回调body定义';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."CALLBACK_BODY_TYPE" IS '回调Body类型';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."EXPIRES" IS '有效期(秒)';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."IS_DEFAULT" IS '是否默认';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."ENABLE" IS '是否启用';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."REMARK" IS '备注';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."CREATE_USER_ID" IS '创建人';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."UPDATE_USER_ID" IS '更新人';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "JBOLT"."JB_QINIU_BUCKET"."REGION" IS '地区';
COMMENT ON TABLE "JBOLT"."JB_QINIU_BUCKET" IS '七牛bucket配置';

-- ----------------------------
-- Primary Key structure for table JB_QINIU
-- ----------------------------
ALTER TABLE "JBOLT"."JB_QINIU" ADD CONSTRAINT "SYS_C0010961" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_QINIU
-- ----------------------------
ALTER TABLE "JBOLT"."JB_QINIU" ADD CONSTRAINT "SYS_C0010937" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU" ADD CONSTRAINT "SYS_C0010938" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU" ADD CONSTRAINT "SYS_C0010939" CHECK ("SN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU" ADD CONSTRAINT "SYS_C0010940" CHECK ("AK" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU" ADD CONSTRAINT "SYS_C0010941" CHECK ("SK" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU" ADD CONSTRAINT "SYS_C0010942" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU" ADD CONSTRAINT "SYS_C0010943" CHECK ("BUCKET_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU" ADD CONSTRAINT "SYS_C0010944" CHECK ("IS_DEFAULT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU" ADD CONSTRAINT "SYS_C0010945" CHECK ("ENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU" ADD CONSTRAINT "SYS_C0010946" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU" ADD CONSTRAINT "SYS_C0010947" CHECK ("UPDATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU" ADD CONSTRAINT "SYS_C0010948" CHECK ("CREATE_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU" ADD CONSTRAINT "SYS_C0010949" CHECK ("UPDATE_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JB_QINIU_BUCKET
-- ----------------------------
ALTER TABLE "JBOLT"."JB_QINIU_BUCKET" ADD CONSTRAINT "SYS_C0010960" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JB_QINIU_BUCKET
-- ----------------------------
ALTER TABLE "JBOLT"."JB_QINIU_BUCKET" ADD CONSTRAINT "SYS_C0010950" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU_BUCKET" ADD CONSTRAINT "SYS_C0010951" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU_BUCKET" ADD CONSTRAINT "SYS_C0010952" CHECK ("SN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU_BUCKET" ADD CONSTRAINT "SYS_C0010953" CHECK ("QINIU_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU_BUCKET" ADD CONSTRAINT "SYS_C0010954" CHECK ("IS_DEFAULT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU_BUCKET" ADD CONSTRAINT "SYS_C0010955" CHECK ("ENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU_BUCKET" ADD CONSTRAINT "SYS_C0010956" CHECK ("CREATE_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU_BUCKET" ADD CONSTRAINT "SYS_C0010957" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU_BUCKET" ADD CONSTRAINT "SYS_C0010958" CHECK ("UPDATE_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_QINIU_BUCKET" ADD CONSTRAINT "SYS_C0010959" CHECK ("REGION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;



CREATE TABLE "JBOLT"."JB_SENSITIVE_WORD" (
"ID" NUMBER(19,0) NOT NULL,
"CONTENT" NVARCHAR2(40) NOT NULL,
"ENABLE" CHAR(1) DEFAULT '1' NOT NULL
)
    LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "JBOLT"."JB_SENSITIVE_WORD"."ID" IS '主键ID';
COMMENT ON COLUMN "JBOLT"."JB_SENSITIVE_WORD"."NAME" IS '敏感词内容';
COMMENT ON COLUMN "JBOLT"."JB_SENSITIVE_WORD"."ENABLE" IS '启用';
COMMENT ON TABLE "JBOLT"."JB_SENSITIVE_WORD" IS '敏感词词库';

-- ----------------------------
-- Primary Key structure for table JB_SENSITIVE_WORD
-- ----------------------------
ALTER TABLE "JBOLT"."JB_SENSITIVE_WORD" ADD CONSTRAINT "JBOLT_SENSITIVE_WORD_ID" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JBOLT_SENSITIVE_WORD
-- ----------------------------
ALTER TABLE "JBOLT"."JB_SENSITIVE_WORD" ADD CONSTRAINT "JBOLT_SENSITIVE_WORD_ID_1" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_SENSITIVE_WORD" ADD CONSTRAINT "JBOLT_SENSITIVE_WORD_CONTENT" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JBOLT"."JB_SENSITIVE_WORD" ADD CONSTRAINT "JBOLT_SENSITIVE_WORD_ENABLE" CHECK ("ENABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
